### ISSUE TITLE
Pass info about restart from MD code

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#100]
This was formerly part of issue #35 . I think we can do it as it would decrease the likelihood of mistakes, but it is definitely less urgent. I leave it here so that it is on the todo list. The way to implement this portably is:
* add a check in the MD code that plumed version is high enough to accept the new cmd
* in case so, pass the new command

In 325a73458113e741ea26a208dc185223bf482bb3 this has been done to pass kbT from MD code

**Comment by GiovanniBussi** [comment]
I pushed on branch fix-100 a fix that works with gromacs. This will add a new "cmd" for PLUMED, and also slightly change the behavior. Namely, restart will be on by default when using cpt from gromacs. Can I merge it on master?

**Comment by carlocamilloni** [comment]
Fine by me!
Carlo
