### ISSUE TITLE
maze tutorial

### ISSUE THREAD

**Issue by amarye** [plumed/plumed2#1012]
Could you please provide us with a maze tutorial?

**Comment by jakryd** [comment]
Hi @amarye, I'm currently working on a more user-friendly maze plugin with a tutorial and plan to finish it in a couple of months.

@GiovanniBussi, we can keep this issue open until I am done.

**Comment by aniruddha-seal** [comment]
The maze tutorial is now online https://www.plumed-tutorials.org/lessons/24/008/data/NAVIGATION.html

**Comment by amarye** [comment]
Thank you for offering the maze tutorial; it is truly amazing!
