### ISSUE TITLE
Confusion is energy units of free energy in well-tempered metadynamics. 

### ISSUE THREAD

**Issue by Anujkumarp** [plumed/plumed2#1041]
What would be the units of free energy in plumed2-2.8.1 version. I choose distance as a CV in WT-MetaD.

**Comment by GiovanniBussi** [comment]
Please read the manual. It is literally sufficient to search for "UNITS" in the search bar and you will find [this page](https://www.plumed.org/doc-v2.8/user-doc/html/_u_n_i_t_s.html)
