### ISSUE TITLE
Issue with coverage build

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#1060]
@gtribello it looks like your last commit (9b644057a06e98bf9fbf0831ba0666904e87d41c) introduces a bug that makes the coverage scan build hang on regtest `dimred/rt-smap1`.

You can see what's happening by comparing these CI runs:
- https://github.com/plumed/plumed2/actions/runs/8696322701/job/23849320890
- https://github.com/plumed/plumed2/actions/runs/8696318196/job/23849304595

Can you have a look at it? I guess it's some subtle bug, but maybe it can be identified knowing which regtest is hanging and the small list of modifications you made. Thanks!

**Comment by gtribello** [comment]
I fixed this @GiovanniBussi
