### ISSUE TITLE
bug: ENERGY cv not working with gromacs

### ISSUE THREAD

**Issue by invemichele** [plumed/plumed2#1085]
@gtribello This seem to be related to the way `hack-the-three` handles ENERGY 

see https://groups.google.com/g/plumed-users/c/hv7u5dRmPug/m/K9QNfD2CAwAJ

Note: in Qinghua's tests OPES_EXPANDED starts to add bias at 200ps, so the simulation crashes as soon as the ENERGY dependent bias is applied

**Comment by gtribello** [comment]
I think should now be fixed.  Sorry it took a while to get to it.
