### ISSUE TITLE
Consider releasing the GIL in the Python interface

### ISSUE THREAD

**Issue by Luthaf** [plumed/plumed2#1128]
The current Python interface to PLUMED uses cython to call the C++ code, and by default cython takes and hold the Global Interpreter Lock (GIL).

Unfortunately, this conflicts with the `metatensor` (and likely `pytorch`) modules, because PyTorch checks that the GIL is not held when running `backward()` (i.e. computing gradients): 

https://github.com/pytorch/pytorch/blob/f69bf005f7b3be70b9a38ba663e6bc825dfe7ffd/torch/csrc/autograd/python_engine.cpp#L130-L135

This means that trying to use PLUMED with a `METATENSOR` action from Python will always fail with the above error.

Would it be possible to annotate the functions in `python/cplumed.pxd` with `@cython.nogil`? (cf https://cython.readthedocs.io/en/latest/src/userguide/nogil.html)

This would fix the above problem, and should be fine to do as long a there is no function call from PLUMED back to the Python interpreter. I'm not sure if the latter is the case or not though (i.e. can someone define custom CV as pure Python scripts?)

**Comment by GiovanniBussi** [comment]
Yes, PLUMED [could call Python](https://github.com/plumed/plumed2/pull/1001).

However, I see that one could release the lock while PLUMED is doing the c++ stuff.

@Iximiel @tonigi is it possible to hold the lock when we call pycv? The idea would be:
- When we call plumed from python, the lock is not held
- When we call metatensor (from C++), the lock is not held
- When we call pycv, the lock is held

Giovanni

**Comment by GiovanniBussi** [comment]
I see so this means that in theory we could use nogil as @Luthaf suggested?

I have no idea how to do it. @Luthaf can you perhaps try, so that you can also confirm that the problem with metatensor disappears? Thanks!

**Comment by Luthaf** [comment]
Sure, I'll give it a try! If `pycv` is using pybind11, everything should just work™. 

Although I'm wondering if someone tried to use a Python CV with PLUMED called itself from Python? This might result in a deadlock with the current implementation, unless pybind11 is clever enough to realise the GIL is already held.

**Comment by GiovanniBussi** [comment]
Closed in https://github.com/plumed/plumed2/pull/1129
