### ISSUE TITLE
sum_hills error

### ISSUE THREAD

**Issue by KrishnenduSinha12** [plumed/plumed2#1135]
I am trying to get free energy surface after metadynamics simulation but sum_hills shows following error :
"terminate called after throwing an instance of 'std::length_error'
  what():  cannot create std::vector larger than max_size()
Aborted (core dumped)"
My HILLs file is attached
[HILLS.csv](https://github.com/user-attachments/files/17364171/HILLS.csv)

**Comment by GiovanniBussi** [comment]
You are using too many CVs (10) and sum_hills cannot allocate the required memory.

You can try to use reweighting as explained in tutorials to recover the free energy profile as a function of a limited number of CVs
