### ISSUE TITLE
Issue with PBMETAD + SELECTOR

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#1143]
@carlocamilloni @maxbonomi can you cross check this?

[This test](https://github.com/plumed/plumed2/blob/v2.10/regtest/basic/rt-coverage-pbmetad-selector/plumed.dat) has been added [recently](https://github.com/plumed/plumed2/pull/1140) to v2.9. It succeeds there, but it fails in v2.10 and master on mac. I checked on my mac and it fails as well, so it's not some odd Github Actions thing.

I am not sure how SELECTOR work. I suspect it's not correct if you don't have also a SELECTOR_ID. If this is the case, I think the regtest should be removed (or changed) but an error should be added if SELECTOR_ID is not passed.

**Comment by carlocamilloni** [comment]
I do not know sorry

**Comment by GiovanniBussi** [comment]
I think I fixed it. For the records: using `SELECTOR` with `PBMETAD` also relies on the value of `SELECTOR_ID`. If `SELECTOR_ID` is not passed, it was an uninizialized variable.

With the fix, if `SELECTOR_ID` is not passed, it is set to zero. This is by the way the value that would be returned if one uses a non existing `SELECTOR` action

I will wait for this to pass the tests on Github for all the branches (2.9, 2.10, and master) and then close this issue.

@maxbonomi this should be sufficient to pass the tests and avoid undefined behavior. Possible improvements that you might consider to implement if you wish:
- Give an error when `SELECTOR` is used within `PBMETAD` without also specifying a `SELECTOR_ID` (now it defaults to zero).
- Make sure that, if a `SELECTOR` action with a corresponding name does not exist, an error is triggered (now the value is just set to zero)

I do not implement them because I don't know if they are good ideas
