### ISSUE TITLE
Hardcoded path of plumed patches

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#129]
@carlocamilloni commented in #107 about the fact that it is not intuitive to use the flag --standalone-executable when moving plumed executable to another machine. Presently, if the new machine doesn't have /patch directory in the right place plumed will give an error. A workaround (actually used by @tonigi in Windows static executable) is the flag --standalone-executable

Possible solutions, in order of difference from now:
1. In the error messege add a hint to the --standalone-executable flag
2. Convert the error in a warning (keeping it silent when one uses --standalone-executable)
3. In case patches are not found in the hardcoded path, look according to env var PLUMED_ROOT (e.g. $PLUMED_ROOT/patches)
4. First look in $PLUMED_ROOT/patches, then in hardcoded path.

I would avoid 4 since it can be very error prone for people installing several plumed versions side by side with different suffix (I don't, I prefer tclmodules). Also, I do not think we should allow people to move the executable to a new machine and then patch a code there based on another PLUMED_ROOT, because it would be difficult to know which patch they actually used.

For me a good compromise would be 2.

@carlocamilloni what do you think?

**Comment by maxbonomi** [comment]
I would prefer installing both documentation and patches with "make install" and then use environmental variables to be able to use different versions of plumed and keep a single plumed source directory.

**Comment by GiovanniBussi** [comment]
Hi max it is already like that when you install. Indeed you can even remove source directory after install. What I do is install different versions in different directories and then change BIN env var to choose the version (with moduletcl). That's exactly the reason to hardcode PLUMED_ROOT var in the executable so that one is sure that there is no mismatch. Or maybe I did not understand properly your point?

**Comment by maxbonomi** [comment]
I see, patches are installed, but If I remember correctly they are looked for in the sources directory

**Comment by GiovanniBussi** [comment]
when you install also patches are copied. Indeed, in the installed executable the PLUMED_ROOT variable is not the source directory (if not it is a bug!) but the install one.

**Comment by maxbonomi** [comment]
ok, but that variable is hardcoded, instead of read it from the environmental variable. So when the code is moved, everything stops working

**Comment by maxbonomi** [comment]
I would go for option 4

**Comment by maxbonomi** [comment]
gromacs-like

**Comment by carlocamilloni** [comment]
I would go for option 4, with multiple versions installed it will be enough to change the path and PLUMED_ROOT. In particular because with options 1 or 2  you would get a warning also when using plumed sum_hills or kt, while this is a problem only for plumed patch.

**Comment by GiovanniBussi** [comment]
For me it is ok (in the end I never install different versions with suffixes, I prefer modules). In gromacs does GMXLIB override the hardcoded one or is it appended?

The only dangerous thing that I could do in my setup will be to launch plumed with explicit path to patch and obtain a patch to another version of plumed. To avoid this I just have to be sure that PLUMED_ROOT is never set. So I would prefer not to set PLUMED_ROOT in the sourceme.sh file, nor in the module file.

As a side note, consider that path to shared libraries will remain hardcoded (otherwise it is a nightmare) so unless you compile a static executable the two machines should be very similar to each other.

Is that ok?

**Comment by carlocamilloni** [comment]
Yes I think this perfect. As far as I remember GMXLIB override the hardcoded one
