### ISSUE TITLE
Doc for parallelization and GPUs

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#142]
In the questionnaire it was mentioned that PLUMED should work with GPUs and that should be better parallelized. Whereas this for sure makes sense for highly expensive CVs, I think most of the users are not even aware of the speedup that one can get on GPUs with GROMACS+PLUMED with proper settings or how to set up openMP (relevant for just released 2.2). I think we should explain it in the documentation, perhaps with an ad hoc tutorial collecting all the speed up techniques.

**Comment by carlocamilloni** [comment]
@plumed/all I added a page in the documentation where to add indication on how to optimise your performances with PLUMED 
0bddd1050519faae1fa611198648f050aa073ed5
Please amend it with your hints!
