### ISSUE TITLE
Patch for dl_poly

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#144]
It has been asked on the questionnaire to add a patch for dlpoly. This is discussed here:
https://groups.google.com/d/msgid/plumed-users/09bac058-2c2e-4d0e-af58-5d0f65722e44%40googlegroups.com?utm_medium=email&utm_source=footer

We could add it to the PLUMED distribution so that users can try it. Meanwhile, I think @gtribello is trying to make it include directly into official DL_POLY distribution.

**Comment by gtribello** [comment]
I have patches for dlpoly 2 and dlpoly 4.  Before sharing them I would like to check the viral, which haven't yet found the time to do.  I will add this to my to do list, however, and will try and do it before the end of the month.

**Comment by GiovanniBussi** [comment]
@gtribello great! If you look here http://plumed.github.io/doc-v2.2/developer-doc/html/_how_to_plumed_your_m_d.html at section "Check virial contribution" I added some comment about how to debug it (at least for isotropic pressure). It is sufficient to change the barostat pressure from dl_poly and add a compensating pressure from plumed.

**Comment by gtribello** [comment]
@GiovanniBussi 

I was just looking through the issues and I found this one.  I think it is resolved.   DL_POLY 4 now natively supports PLUMED.  That is to say, DL_POLY 4 contains the code to load PLUMED as a dynamic library.   We have no support for DL_POLY_CLASSIC (formerly 2) but that code is not supported by CCP5 anymore so I don't think we should be encouraging people to use it.

What do you think?

**Comment by GiovanniBussi** [comment]
@gtribello I think we can close this issue. Can you send me a link so that I put it in the first page of the manual? Thanks!

**Comment by gtribello** [comment]
@GiovanniBussi 

I think the link is this one.

http://www.scd.stfc.ac.uk//research/app/ccg/software/DL_POLY/44516.aspx
