### ISSUE TITLE
bug somewhere in bias-sharing functions

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#168]
the symptom is that bias-exchange with neutral replicas doesn't work anymore with plumed2.2 and the master branch, while with v2.1 it works as usual (i.e. running multiple replicas some with MetaD some without the code hangs waiting for something)

**Comment by GiovanniBussi** [comment]
Can you check what happens if in the plumed file of the neutral replica you put a PRINT statement with same stride as replex?

**Comment by carlocamilloni** [comment]
It doesn’t change, it stops also without replex, with only -multi

**Comment by GiovanniBussi** [comment]
I see. And what if you replace METAD with e.g. RESTRAINT? If this works then the problem could be in Metad.cpp

**Comment by carlocamilloni** [comment]
You are right, with RESTRAINT it works (with and without replex)

**Comment by GiovanniBussi** [comment]
I just fixed it (it was my fault) I will push the fix in a minute
