### ISSUE TITLE
HISTOGRAM with FREE-ENERGY and RUN does not work

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#175]
When using FREE-ENERGY in HISTOGRAM keyword it is necessary to use USE_ALL_DATA. Otherwise, results are not accumulated properly.

**Comment by GiovanniBussi** [comment]
Same happens with UNNORMALIZED.

**Comment by carlocamilloni** [comment]
@gtribello @GiovanniBussi can this be closed now?

**Comment by gtribello** [comment]
I believe it can be closed.  Thanks for pointing this out.
