### ISSUE TITLE
 PLUMED ERROR: You are outside the GRID!. Please increase GRID size.

### ISSUE THREAD

**Issue by mihirdate** [plumed/plumed2#178]
Hi,
I am running metadynamics with plumed version 1.3.0, ACEMD MD engine package and Amber ff (ff99SB). 
I have two CVs with walls on both on them. 
1st CV is distance and 2nd CV is torsion.
````
DISTANCE LIST <g1_CG_pocket> <g2_CG_lig> SIGMA 0.3
TORSION LIST <g1_CG_alpha_F> <g2_CG_alpha_E> <g3_CG_Nter_beta> <g2_CG_lig> SIGMA 0.15

GRID CV 1 MIN -5 MAX 40 NBIN 400
GRID CV 2 MIN -pi MAX +pi NBIN 300 PBC


UWALL CV1 LIMIT 15.0 KAPPA 1000.0

LWALL CV 2 LIMIT -0.977384 KAPPA 1000.0
UWALL CV 2 LIMIT 2.16421 KAPPA 1000.0
````
In running metadynamics with this plumed script, I constantly get error message of "PLUMED ERROR: You are outside the GRID!. Please increase GRID size." Looking at the manual, the solution is to increase the grid size. I think my bin size is good. Is KAPPA enough? I think with Amber ff99SB units, Angstrom for distance, ````KAPPA 1000.0```` is more than enough.
The 2nd CV, which is torsion CV is periodic and it cannot go outside the GRID.
So the only culprit could be distance CV.
I started grid size 
````GRID CV 1 MIN 0 MAX 20 NBIN 400````
This is already bigger than the WALL limits on distance CV. With this setup, the metadynamics run was stopped with the same error message, you are outside the GRID. I tried the bigger grid 
````GRID CV 1 MIN -5 MAX 40 NBIN 400````
And still the simulation stops with the same error message. 

I checked the value of distance CV in HILLS and COLVAR files and it is not outside UWALL limit of 15.
I also calculated the value of distance CV by processing the trajectory. And at no instance it went outside 15. 

What could be the possible reason of CV outside the grid?

**Comment by GiovanniBussi** [comment]
Hi @mihirdate !

This github repository is for plumed2, so I will close the issue. Please post to the mailing list. Also notive that we currently provide limited support for plumed < 2.x.

Giovanni

**Comment by mihirdate** [comment]
Hi 
Thanks. Could you direct me to the github repository for plumed 1.3.0 so that I can post it there?

**Comment by GiovanniBussi** [comment]
The development version of plumed 1.x has never been made publicly available, so there is not such a repository.

Giovanni

**Comment by mihirdate** [comment]
Alright. So which is the best place to raise this issue? Can you suggest?

**Comment by GiovanniBussi** [comment]
You can write try on the plumed mailing list (http://groups.google.com/forum/#!forum/plumed-users)
