### ISSUE TITLE
INTERVAL with periodic variables

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#181]
The code should crash if one tries to use INTERVAL in METAD on a periodic variable.

**Comment by carlocamilloni** [comment]
It depends, if the interval are outside the period definition then it could be fine, I say this because in pbmetad you need to define the intervals for all your cvs

**Comment by GiovanniBussi** [comment]
If interval is applied with a range that is wider than periodic domain it should have no effect on the simulation right?

In the other case (interval narrower than periodic range) one can easily get a nonsense result due to the way interval is implemented.

**Comment by carlocamilloni** [comment]
Yes this is what I mean, if It is defined outside the periodicity is innocuous, otherwise it should fail

**Comment by maxbonomi** [comment]
> On Jan 18, 2016, at 17:55, Carlo Camilloni <notifications@github.com> wrote:
> 
> It depends, if the interval are outside the period definition then it could be fine, I say this because in pbmetad you need to define the intervals for all your cvs

Why you need to?


> 
> 
> Sent from my iPhone
>

**Comment by carlocamilloni** [comment]
I think that you either define it for all of them or for none, but you cannot define it just for some as it is the syntax now.

**Comment by GiovanniBussi** [comment]
I think that PBMETAD is implemented in a separate action, so I will forbid periodic arguments with INTERVAL in METAD even if the periodic domain is narrower than interval - I think it is more clear. @carlocamilloni is that ok?
