### ISSUE TITLE
Gromacs 5.1 stops compiling after Plumed patch

### ISSUE THREAD

**Issue by alexvoronov** [plumed/plumed2#186]
Hi,

Gromacs 5.1 compilation breaks on Mac OS X 10.10.5 (Yosemite) after running `plumed patch -p`. I get the following error message:

```
ld: library not found for -lgomp
```

Without Plumed patch, Gromacs compiles just fine.

Do you know why it breaks?

Alex

**Comment by GiovanniBussi** [comment]
Try to patch with "--shared" option (or "--runtime" if you prefer, see the manual for the differences). Let us know if this works. I have the impression this could solve many linking issues on mac, I would make it the default.

**Comment by alexvoronov** [comment]
Thanks a lot, "--shared" solved the problem!
