### ISSUE TITLE
More strings for MOLINFO

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#195]
As of now we can recognize anything in the form:
XXX-YYY
where XXX is the name of a special group or the type of an atom, and YYY is the number of a residue (optionally preceded by the letter identifying the chain).

I would like to add other strings:
nucleic  : all atoms in a DNA or RNA residue
protein  : all atoms in a protein residue
water    : all atoms in a water residue
ions       : all atoms with names matching those of ions
hydrogens : all hydrogens of the system
nonhydrogens : all heavy atoms

Other ideas are welcome!

**Comment by tonigi** [comment]
Perhaps atom specifications like :15.A@CA to indicate CA of residue 15 chain A.  Or any other choice of separator. The colon/dot/@ syntax follows Amber's and Chimera's http://www.cgl.ucsf.edu/chimera/1.1700/docs/UsersGuide/midas/atom_spec.html . While I guess vmd's would be too complicated to implement.

**Comment by GiovanniBussi** [comment]
@tonigi this issue is related to special strings (e.g. phi/psi) not to atom selection. Atom selection was #32 and has been sort of closed.

Let me summarize the status of molinfo strings:
- Strings in the form `@XXX-YYY` are currently considered as special strings.
- `YYY` should be the number of a residue, optionally containing a chain number.
- `XXX` should be a special group name (`chi`, `psi`, etc) or an atom name (`CA`).

Thus your selection would be `@CA-15A`. The reason to start with `@` + letter is that `@` is a reserved prefix for unlabelled plumed actions which receive a default label equal to `@num` where num is their progressive number. This allows to avoid name clashes.

The limitations now are that:
- only proteins and nucleic acids are detected (no way to do `@OW-1000` to pick 1000th water oxygen)
- I would like to add extra special groups without the residue number (e.g. `@nucleic`)

I think both are relatively easy to fix
