### ISSUE TITLE
Missing #include <ctime>  in Metainference.cpp

### ISSUE THREAD

**Issue by tonigi** [plumed/plumed2#198]
I guess this could be added in src/bias/Metainference.cpp , which calls `time()`:

```
#include <ctime>
```

Thanks!

**Comment by GiovanniBussi** [comment]
@carlocamilloni I think it would be better not to use srand()/rand() since this affects a global random number generator that could be in principle also used by the MD code. Would it be possible to use the PLMD::Random class?

**Comment by carlocamilloni** [comment]
Yes, in our branch this is already done, i will update soon
