### ISSUE TITLE
Multi-RMSD and PBC

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#200]
the keyword NOPBC is not removed but also not read, so if one tries to set it the code crashes.
@gtribello  I think that in the case of MULTI-DRMSD NOPBC could be actually used.

**Comment by gtribello** [comment]
Hello @carlocamilloni 

I added something to try and fix this problem.  Does it fix whatever you were trying?

**Comment by carlocamilloni** [comment]
Hi @gtribello 

it doesn't work because I think you need to read the keyword in the collective variable Multi-RMSD.cpp in colvar but only if you are doing MULTI-DRMSD
( what I am trying is to calculate multi-rmsd type=multi-drmsd after making the domains whole).

**Comment by gtribello** [comment]
@carlocamilloni 

Can you try the following: put 

REMARK NOPBC 

Into your PDB file defining the reference structure.  This should I think work.  If it does we can discuss whether or not to allow this information to be passed from the underlying action.  I'm in two minds as I would like to have a consistent syntax for MULTI-RMSD with PATH and all other things.  In those actions the information on RMSD is in the REMARK part of the pdb reference file.

I hope this helps

**Comment by carlocamilloni** [comment]
@gtribello Ok, sounds good and it works. I cherry-picked your changes for v2.3 and removed the keyword NOPBC from MultiRMSD (this was the first source of misunderstanding, the keyword was listed in the manual for MultiRMSD) and I have extended a bit the documentation. Thanks! (could you also check the bug about Virtual Atoms and DUMPMULTICOLVAR please, because we are trying to use it for some analysis but we cannot find a way to fix it..)
