### ISSUE TITLE
DRMSD TYPE=INTER-RMSD does not work

### ISSUE THREAD

**Issue by OleinikovasV** [plumed/plumed2#202]
Hi!

I am testing the new "flavour" of DRMSD metric (using the master branch downloaded yesterday) based on an example syntax in plumed-2.4-dev/src/colvar/DRMSD.cpp:

> \verbatim
> DRMSD REFERENCE=file.pdb LOWER_CUTOFF=0.1 UPPER_CUTOFF=0.8 TYPE=INTER-RMSD
> \endverbatim

But I get this error:

```
+++ Internal PLUMED error +++ file reference/../../reference/MetricRegister.h, line 80 +++ message:
assertion failed check(ftype), metric INTER-RMSD does not exist
Aborted 
```
It does work, however, for the regular DRMSD, but I would be really keen to try INTER- and INTRA- contacts RMSD. Any ideas how to fix this?

Many thanks!

**Comment by carlocamilloni** [comment]
The correct syntax is DRMSD REFERENCE=file.pdb LOWER_CUTOFF=0.1 UPPER_CUTOFF=0.8 TYPE=INTER-DRMSD

the manual has been updated.

**Comment by carlocamilloni** [comment]
Try
> DRMSD REFERENCE=file.pdb LOWER_CUTOFF=0.1 UPPER_CUTOFF=0.8 TYPE=INTER-DRMSD
>
