### ISSUE TITLE
DUMPMULTICOLVAR and VIRTUAL ATOMS issue (plumed 2.2 and 2.3)

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#203]
It looks like that DUMPMULTICOLVAR does not work with virtual atoms...
the following input segfaults (with plumed 2.2 and 2.3) 

ce1: CENTER ATOMS=2-10
ce2: CENTER ATOMS=20-30
ce3: CENTER ATOMS=40-50
ce4: CENTER ATOMS=60-70

DISTANCES GROUP=ce1,ce2,ce3,ce4 LESS_THAN={RATIONAL R_0=1.0} LABEL=d3

DUMPMULTICOLVAR DATA=d3 FILE=d3.xyz

**Comment by gtribello** [comment]
@carlocamilloni 

I think I have sussed out what is wrong here and fixed it.  I am just a bit confused, which branch should I fix this on v2.3 and master?  Should I back fix this on v2.2 as well?

**Comment by carlocamilloni** [comment]
@gtribello

We will release two more v2.2 updates before dismissing support for it so the patch should go in v2.2, btw there there is already a regtest that is currently failing that i added to check for this bug

**Comment by gtribello** [comment]
@carlocamilloni 

Sorry one more question.  Can I merge v2.2 into v2.3 or do I have to cherry pick the commit from v2.2 into v2.3?  Thanks

**Comment by carlocamilloni** [comment]
@gtribello 
merge is fine, no need to cherry-pick

**Comment by gtribello** [comment]
OK it is fixed.  Thanks Carlo
