### ISSUE TITLE
MATHEVAL of MultiColvar

### ISSUE THREAD

**Issue by whitead** [plumed/plumed2#219]
I'm interested in using the MATHEVAL function on a multicolvar, specifically multiplying DISTANCES and COORDINATIONNUMBER to replicate my work in [this paper](http://aip.scitation.org/doi/abs/10.1063/1.4974837). It doesn't appear to be possible currently. I'm happy to write the code myself but was wondering if @GiovanniBussi or other developers had made progress in this or had thoughts about it. Thanks!

**Comment by GiovanniBussi** [comment]
@gtribello more likely will know the answer

**Comment by gtribello** [comment]
Hello

I don't think I would implement it in quite the way you suggest as the input would be rather complicated for the user.  I would instead write a multicolvar to calculate just the quantity in the second summation in equation (1) of your paper.  In fact I had a go at writing that bit myself so if you want me to send you the file just tell me your email address (it seems I can't attach cpp files here).  I would then have a multicolvar bias to implement the terms in the first sum that this is multiplied by.  To see what you can do with multicolvar bias take a look in the manyrestraints module at what is done by UWALLS.  If you inherit from ManyRestraintsBase you can apply one bias on each of the quantities calculated in a multicolvar. 

I hope this is clear.  Please ask if it isn't.

Thanks
Gareth

**Comment by whitead** [comment]
Thanks! I'll give that a shot and reoen if I have trouble. Email is andrew dot white@rochester.edu
