### ISSUE TITLE
Simplify multi-replica input

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#221]
I was thinking if we can do something to simplify umbrella sampling setup, and I thought perhaps it is worth doing something more general.

I propose to implement the following syntax:

    RESTRAINT ARG=d KAPPA=1.0 AT=@multi:1.0,2.0,3.0

so as to use a single input file for all replicas. Notice that currently one has to use a script to generate multiple `plumed.dat` files which is error prone. The implementation should just require the following changes:
1. Pass the number of current replica to parsing tools
2. Whenever a keyword is parsed, if it starts with `@multi:` treat it as a vector and only parse the element corresponding to the current replica.

In case each element is already a vector (e.g. in multidimensional umbrella sampling), it would be possible to work with braces, e.g.

    RESTRAINT ARG=d,e KAPPA=1.0,2.0 AT=@multi:{{1.0,2.0},{3.0,4.0}}

In principle, once implemented this would work for any possible argument, e.g. for bias exchange one could choose the biased variable:

    METAD ARG=@multi:{a,b,c} ...

Using a keyword starting with @ would allow to avoid clashes with atom groups and action names, since actions can only start with `@[numbers]` whereas default atom groups have form `@chi-1`.

Comments are welcome!

Giovanni

**Comment by sreisser** [comment]
Hi, looks nice. How about combinations, e.g. in MAXENT I have 
TYPE=INEQUAL> AT=...list of reference values...
So it should be possible to give 
AT=1.,@multi:{...},56.,34.,1.6,@multi:{...}
Here, brackets would have to be compulsory (contrarily to your first example (RESTRAINT ARG=d KAPPA=1.0 AT=@multi:1.0,2.0,3.0)
Cheers
Sabine

**Comment by GiovanniBussi** [comment]
Hi @sreisser thanks for the suggestion. This is slightly more complicated but feasible, and might be useful if most of the parameters are the same across replicas.

However, because of the way curly braces are treated in plumed, the right syntax would be:

     AT=1.0,{@multi:{2.0,3.0,4.0}},3.0

The reason is that the outer curly braces are removed when initially splitting the line in words so as to allow spaces (as opposed to commas) as separators. An equivalent job would be done indeed by

     AT={1.0 @multi:{2.0 3.0 4.0} 3.0}

Giovanni

**Comment by richardcunha** [comment]
Hi, also to me it looks nice and most importantly useful.
Just a question, if I give PLUMED something like this:
METAD ARG=@multi:{{a,b},{c}} HEIGHT=0.1 ...
I can expect that I'll receive back a complaint that I'm giving two groups of CV but only one parameter for the height, right?!

Richard

**Comment by GiovanniBussi** [comment]
For HEIGHT there's no problem. The problem is for SIGMA, and, yes, you would receive an error since on replica 0 plumed find a single value for SIGMA instead of a vector with size 2.

**Comment by gtribello** [comment]
I think this looks cool.  I think it is better than the option with files.  Is there a word other than multi though?  I am wondering if we (by which I mean I) are not overusing the word multi.  Would @replicas work instead?

**Comment by GiovanniBussi** [comment]
@gtribello that's a straightforward replacement.

I was first thinking by analogy with the --multi flag of the driver (which is actually taken from the -multi flag of gromacs), but I now recall that MULTI is used in other contexts as well :-)

Giovanni
