### ISSUE TITLE
Add replica suffix to all read/written files

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#228]
Currently replica suffixes are added consistently to all files manipulated using the IFile and OFile tools. This however does not include the following cases:
1. Trajectories read by driver
2. PDB files read by RMSD/FIT_TO_TEMPLATE etc.

I realized this writing the explanations for a tutorial. I think it would be easier to explain if the suffix was appended also to PDB and trajectory files.

**Comment by GiovanniBussi** [comment]
Actually, trajectory files are already done... I think only PDB files are wrong.

**Comment by carlocamilloni** [comment]
But pdb files then would mean also in molinfo and this would be rather annoying 

Inviato da iPhone
