### ISSUE TITLE
Extend COMMITTOR to avoid stopping

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#232]
I think it would be very useful to extend the COMMITTOR action to do the following:

1. When it reaches one basin, write it (already doing it) but without stopping.
2. Keep track of the last visited basin to avoid writing until you reach another basin.

This would allow the counts needed for MSM using so-called coring methods to be estimated on the fly.

**Comment by carlocamilloni** [comment]
@GiovanniBussi the new implementation adds the possibility to not stop the code and to add a line in the COMMIT output file every time the system moves to a new basin or return to the same basin after leaving it
