### ISSUE TITLE
Website

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#242]
@plumed/all I think that the plumed.org website is a bit obsolete at the moment. Do you think it is worth rethinking and restyling it (like only one page with links to GitHub, standalone versions of the code for download, manual and news) or maybe just using it as a link to the plumed GitHub page?

**Comment by GiovanniBussi** [comment]
I agree! Actually you did right now the most important thing: removing the (outdated) list of MD engines.

I think another problem is that the website is not very nice. I think we might consider two options:
1. Using the new google site (the one we used for the Trieste meeting)
2. Using [github pages](https://pages.github.com/), [mapping it](https://help.github.com/articles/using-a-custom-domain-with-github-pages/) to plumed.org. Some of the templates are nice.

The advantage of the latter is that maintenance could be much easier from the command line. I guess github is expected to be stable and reliable in the future.

**Comment by carlocamilloni** [comment]
I agree that is also not nice, I would go for the GitHub pages and mapping it to plumed.org, unless maybe we can just easily apply a new template, but for example I can imagine that by using GitHub it will be easier to post news/announcement directly on the website

**Comment by maxbonomi** [comment]
I am for GitHub too!

**Comment by GiovanniBussi** [comment]
We can make a draft page with gh-pages (maybe in a separate repo github.com/plumed/site) and once it is ready remap it.

I think github hosts either static html (which means you need to use your own website editor, I would avoid it) or [jekyll](https://help.github.com/articles/using-jekyll-as-a-static-site-generator-with-github-pages/) which has nice templates and can be used as a blog directly adding text files. I think we should absolutely use a template that works with mobile phones.

**Comment by GiovanniBussi** [comment]
If you go [here](https://github.com/plumed/site/settings) and click "choose a theme" you can see possible templates

**Comment by maxbonomi** [comment]
Very are simple and clean.
I like Cayman, Minimal, and Tactile!

**Comment by carlocamilloni** [comment]
I like Minimal too

**Comment by gtribello** [comment]
I think Minimal is boring.  Tactile is nice and I quite like slate and architect.

**Comment by maxbonomi** [comment]
We can certainly a couple of flying pigeons if the template is too boring.
