### ISSUE TITLE
Lepton vs Matheval

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#244]
Hi @plumed/all 

I was thinking whether we could replace [matheval](https://www.gnu.org/software/libmatheval/) (or use it side by side) with [lepton](https://simtk.org/projects/lepton).

I cc also @peastman, who is the author of lepton and might have some comment (hi Peter!)

Here a few differences:

|                  | Matheval | Lepton |
|----------|-----------|----------|
| License    | GPL         | BSD-like |
| Language | C             | C++        |
| Maintained | No         | Looks so (it is part of other projects, see below) |
| Installable  | Yes (autoconf) | No |
| Dependencies | yes (guile + flex) | Apparently none |
| Could be embedded in plumed | Looks difficult | Looks easy (see below) |
| Easy to customize | No | Looks easy (adding new functions is documented) |

The most important difference is that whereas libmatheval is installable as a library (e.g. with `apt-get install libmatheval` or `port install libmatheval`) there is no apparent way to install lepton. In addition we should consider that there appear not to be an official lepton repository. The one [here](https://simtk.org/projects/lepton) looks a bit outdated, and lepton is included directly at least in a couple of other repositories ([openmm](https://github.com/pandegroup/openmm/) and [opensim-core](https://github.com/opensim-org/opensim-core)) with slight local modifications.

However, since it looks like lepton has no dependencies, we could think about including it in plumed directly (as done in the two examples mentioned above) provided that: (a) license allows it (I think so) and (b) @peastman agrees and thinks it is a good idea. If this is possible, the good thing is that users will have matheval-like features in plumed without the need of installing an extra library. In addition, lepton seems way easier than matheval to customize.

In particular, lepton could be included in a src/lepton module similarly to [molfile](https://github.com/plumed/plumed2/tree/master/src/molfile) module that we included from VMD. In this manner it would have a dedicated licence file. It could be imported with a script that applies some of the formatting required to be included in PLUMED, e.g.:
- plumed-compatible guards in header files
- headers should go in a single directory src/lepton together with source, and include commands should be changed accordingly
- namespace will be nested inside `namespace PLMD`. This would avoid clashes if we link plumed against other software also including a possibly incompatible version of lepton (e.g. openmm).
- source code will be astyled as the rest of the code.

Using a script to import the library would allow to keep it easily in sync with upstream changes. Since the three versions above are slightly different, we should choose which is the best one to start from.

If this procedure is acceptable, and if performances are similar to matheval (to be checked) we might even drop out matheval completely. Otherwise, we can keep them side by side, perhaps choosing which library to use from some env var or in the input file (something like `FUNC=@lepton{sin(x)}`).

Feedbacks are welcome!

Giovanni

**Comment by peastman** [comment]
The actively developed version of Lepton is the one in the OpenMM repository.  Every now and then I package up the latest code and post it as a new release, but the OpenMM repository is where all development happens, so that's where you'll always find the latest code.

It would be easy enough to build a library for it that could be installed separately.  I've just never done that, because I've never had a need to.  For my purposes, compiling it directly into another program was more convenient.

Lepton doesn't have any required dependencies, but it can optionally use asmjit (also included in the libraries folder of the OpenMM repository) to do JIT compilation of `CompiledExpressions`.  That helps performance a lot.  It also uses a BSD style license, so redistribution isn't a problem.

**Comment by GiovanniBussi** [comment]
@plumed/all I have a draft implementation for this in branch v2.4-lepton.
The way it works is the following:
- At runtime, if env var PLUMED_USE_LEPTON is undefined, same as before.
- At runtime, if env var PLUMED_USE_LEPTON is defined (e.g. by `export PLUMED_USE_LEPTON=yes`), lepton is used as a replacement for matheval

In the second case one can use `MATHEVAL` (function and switching function) also when libmatheval was not linked.

Input syntax is unchanged. I made a quick check with switching function MATHEVAL and it looks like lepton is even faster than matheval. However, I would prefer to add more tests before making it the default. In addition, it might be useful to add the missing functions and constants to make them totally compatible. For instance, I had to add explicitly `pi=3.14159265358979` to allow lepton to reproduce a matheval regtest where pi was used. We could go through [matheval documentation](https://www.gnu.org/software/libmatheval/manual/libmatheval.html) to be sure we include all of them.

**Comment by maxbonomi** [comment]
Shall we rename the directive MATHEVAL to something more general independent
on the fact that you are using Matheval or Lepton?

**Comment by GiovanniBussi** [comment]
@gtribello was suggesting to keep the name MATHEVAL to allow people not changing their input files.

**Comment by maxbonomi** [comment]
I find it a bit confusing, but ok

**Comment by carlocamilloni** [comment]
But in principle we can easily add a synonymous of MATHEVAL so that MATHEVAL is still there but we already introduce a new keyword

**Comment by GiovanniBussi** [comment]
That's true. I can do

    PLUMED_REGISTER_ACTION(Matheval,"MATHEVAL")
    PLUMED_REGISTER_ACTION(Matheval,"ANYFUNC")

Then replace MATHEVAL with ANYFUNC anywhere in the code and just leave a short MATHEVAL manual that points to ANYFUNC manual.

For the switching function is even easier, it is just matter of changing an `if` statement.

Obviously ANYFUNC is not the correct name... which name should we use?

**Comment by maxbonomi** [comment]
ASSEMBLE
CUSTOM

**Comment by carlocamilloni** [comment]
CUSTOMCV

**Comment by maxbonomi** [comment]
Can you use it for bias also?

**Comment by carlocamilloni** [comment]
Not directly in the sense that you cannot apply a force, you can use it with BIASVALUE

**Comment by carlocamilloni** [comment]
This makes me think that it would be nice to have a shortcut “BIAS” as a method in any CV that allows to use that CV as a BIAS without the need of explicitly using BIASVALUE

**Comment by maxbonomi** [comment]
I don’t like the fact that then we have COMBINE and not COMBINECV

Max

**Comment by carlocamilloni** [comment]
Yes I agree, CUSTOM is probably better

**Comment by maxbonomi** [comment]
Too bad we used COMBINE instead of like POLYNOMIAL for polynomial combinations.

**Comment by carlocamilloni** [comment]
But in principle we can add an alias also there and slowly switch

**Comment by GiovanniBussi** [comment]
I think `COMBINE` is mostly useful because it has sensible defaults. I often do

    COMBINE ARG=*.bias PERIODIC=NO

**Comment by maxbonomi** [comment]
I see, still it sounds a bit too general compared to what it really does

**Comment by GiovanniBussi** [comment]
The implementation using env var was merged in v2.4 branch as of 7c5b10470bf5806c7b431e71125b91310101fa64.

Instructions:
- lepton is always compiled
- lepton is enabled as a replacement of libmatheval only if PLUMED_USE_LEPTON env var is defined. In perspective (v2.5) we could eliminate libmatheval.
- lepton is also used to interpret constant inputs (see #250)

I let this issue open since the renaming/aliasing is still to be done (we were thinking about using CUSTOM as an alias to MATHEVAL). In addition, the possibility of using formulas in input constants should be documented.

**Comment by GiovanniBussi** [comment]
Still to do: add CUSTOM as an alternative name for MATHEVAL
