### ISSUE TITLE
Travis failing regtest basic/rt-drift-3

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#246]
Code is unchanged so the new regtest is triggering some kind of bug, but I cannot reproduce it on my Mac using the debug flags.

**Comment by GiovanniBussi** [comment]
Notice that the failing test compiles with `--enable-debug-glibcxx`, which checks boundaries. As far as I remember, STL on mac have a bug that do not support this flag, so probably there is no way to reproduce the failure on the mac. I will also check it

**Comment by GiovanniBussi** [comment]
@carlocamilloni  I found the problem. When, by chance, last domain in particle decomposition has zero atoms, there is an access out of boundary in Driver. This only affects `driver --debug=pd` and has no impact on people using plumed with MD. I will push a fix soon. We might backport it to v2.3, but anyway it is only relevant for regtests.
