### ISSUE TITLE
Better report error with weights in RMSD

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#247]
I think that when one passes all-zeroes weight to RMSD we should report an error instead of computing NaNs.

**Comment by GiovanniBussi** [comment]
@gtribello I am not able to do it for `RMSD TYPE=SIMPLE`. Apparently, in that case the normalization of the weights is not done in `tools/RMSD.cpp`. Can you point me to the place where weights are normalized in the `reference` module?

**Comment by gtribello** [comment]
SingleDomainRMSD.cpp.  The function is readReference.
