### ISSUE TITLE
EUCLIDEAN : ARG is missing

### ISSUE THREAD

**Issue by liyigerry** [plumed/plumed2#252]
I patch plumed-master to gromacs5.1.4.

When I run ADAPTIVE_PATH,
I got this error:
```
+++ Internal PLUMED error
+++ file ReferenceConfiguration.cpp, line 91
+++ message: error reading reference configuration of type EUCLIDEAN : ARG is
missing
```

**Comment by gtribello** [comment]
Hello @liyigerry 

The reference file input should look like this:

REMARK TYPE=EUCLIDEAN
REMARK ARG=d1.x,d1.y
REMARK d1.x=1.2247   d1.y=-0.7208
END

Notice the bit that says ARG=d1.x,d1.y.  Is this missing from your input files?  The error message that you have suggests it might be. ;-)
