### ISSUE TITLE
Automatize astyle and header

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#258]
I would like to automatize two boring tasks that we often forget to do, namely:
- run make astyle
- run header.sh to fix header dates

The plan is the following and could be implemented at the end of the CPPCHECK job on travis-ci:
- run make astyle
- if the repository was modified, commit the changes and push a branch called `currenthash-astyle` on plumedbot/plumed2 repository. `currenthash` is the hash of the current commit.
- open a pull request from that branch to the branch being built using [this tool](https://github.com/github/hub).
- run header.sh and do the same, possibly opening a pull request on a branch called `currenthash-headers`.

The comments in the pull request might contain the git user id of the user that pushed the commit, so that he is notified.

In this manner, we would be able to apply astyle and/or header (after having checked that they work on travis-ci) with a single click from the web interface.

**Comment by carlocamilloni** [comment]
I don't like the spam to all users, also because we will still receive the failure from travis, so I don't think this is a good solution in practice

**Comment by GiovanniBussi** [comment]
Yes that's the main problem. I thought it was possible to notify only the committer but it is not...  

Notice that we could add some tag the the email so that it can be filtered from the inbox if one does not care. What I found really distracting is that sometimes I commit, then switch branch, recompile, and after ten minutes I receive the notification and I have to go back, fix, commit, recompile, etc.

Anyway, I will momentarily merge it _commenting out the opening of the pull request_ (so that the branch is created on the plumedbot account but there is no notification). This would be useful anyway for me (I think I can merge from the web) and I guess does not cause trouble to anyone.

In case later we change our mind, we can just reenable the pull request maybe with some email filter.

**Comment by GiovanniBussi** [comment]
Thought better about it, it's not so important.

I will just find a way to just check headers. I momentarily close the issue

**Comment by GiovanniBussi** [comment]
I solved the issue using a [small extra repository](https://github.com/PlumedBot/plumed2-fix-headers). Periodically (I could set it to monthly) the repo does the following:
- clone plumed2
- check and fix headers for supported branches (v2.3/v2.4/master)
- if necessary, open a pull request.

It should not be very noisy
