### ISSUE TITLE
Multicolvar components

### ISSUE THREAD

**Issue by tonigi** [plumed/plumed2#266]
I was wondering if it was sensible to have a way to access a multicolvar's components. Could be any of those...

* Most general: mcv.1 , mcv.2 ...  could all be defined by default. 
* Explicitly:  `cv1: COMPONENT DATA=mcv INDEX=1`
* Just printing: `PRINT DATA=mcv` (in analogy with `UWALLS DATA ...`)

**Comment by gtribello** [comment]
Hello @tonigi 

Sorry for not replying sooner.  If you want to get all the quantities calculated by a multicolvar you can output them to a file using DUMPMULTICOLVAR.  This outputs an xyz file with 5 columns containing:

1) Atom symbols
2) x positions
3) y positions
4) z positions
5) the value of the multi colvars

For things like q6 it is a bit more complicated as each quantity calculated by the multicolvar is a complex vector.  I am working on a new version of the code to make this all more streamlined but it won't be ready for a while yet.

Also, if you are interested, I am working on a python interface that allows you to call plumed directly from within python.  You just do

include plumed 

and then you can create a plumed object using

p=plumed.plumed()

and use the cmd command using 

p.cmd("setPositions",pos)

with pos being a numpy array.

I know you are a big python guy so would you be interested in trying this out and seeing how much you can break it. :-)

**Comment by tonigi** [comment]
Ok thanks Gareth! The idea was to "demultiplex" the multicolvar so one could use its components... e.g., to check all of them at once in the VMD GUI; and for the sake of completeness.
