### ISSUE TITLE
Delete statements to be double checked

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#268]
https://github.com/plumed/plumed2/blob/7299aff5aa766802ab756e5d704eaf83e09eff4c/src/tools/CubicInterpolation.cpp#L227

@gtribello can you double check this line (I think you are the original author)? I am looking for `new`/`delete` pairs so as to, when possible, replace pointers with `std::vector` or C++11 smart pointers. I don't understand these `delete` statements. Where are the pointers allocated?

Also notice that [this class is not regtested](https://plumed.github.io/doc-v2.3/developer-doc/coverage/tools/CubicInterpolation.cpp.gcov.html).

**Comment by gtribello** [comment]
Erm... this is embarrassing but I think you can delete the whole tool as it is not used anywhere in plumed.  I had it for something I was experimenting with ages ago.  The whole idea never worked and I deleted most of it.  I clearly missed these files though. Sorry.
