### ISSUE TITLE
Improve PLUMED_CONFIG_ENABLE for C++ libs

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#274]
PLUMED_CONFIG_ENABLE presently can only deal with C libraries. The reason is that it is based on AC_CHECK_LIB which tries to link the searched function to a C program (see [here](https://nerdland.net/2009/07/detecting-c-libraries-with-autotools/)).

As a workaround, for `boost_graph` we currently search for `exit` (always found). This makes the check succeed, though does not add a `-lboost_graph` to `Makefile.conf`. In this specific case the fix is fine since `boost_graph` is header only (I guess). For general C++ libraries this is not sufficient.

I think we should improve PLUMED_CONFIG_ENABLE in order to allow this.

Meanwhile, the suggested workaround is that the library should be specified on the `./configure` arguments as well, e.g.
````
./configure --enable-mycxxlib LIBS=-lmycxxlib
````

See also [this thread](https://groups.google.com/d/msgid/plumed-users/1dfd0604-39e9-461b-96c6-d065feacfed9%40googlegroups.com?utm_medium=email&utm_source=footer)

**Comment by carlocamilloni** [comment]
I found this example googling around: 
AC_LANG(C++)
SAVED_LDFLAGS=$LDFLAGS
LDFLAGS="$LDFLAGS -lgmock"
AC_LINK_IFELSE(
  [AC_LANG_PROGRAM([#include <gmock/gmock.h>], 
    [testing::Cardinality dummy])],
  [TEST_LIBS="$TEST_LIBS -lgmock"] [HAVE_GMOCK=1], 
  [AC_MSG_WARN([libgmock is not installed.])])
LDFLAGS=$SAVED_LDFLAGS

**Comment by HanatoK** [comment]
I changed the line of PLUMED_CHECK_PACKAGE to:
`PLUMED_CHECK_PACKAGE([boost/serialization/vector.hpp],[main],__PLUMED_HAS_BOOST_SERIALIZATION],[boost_serialization])`
Using main instead of exit seems working.

**Comment by GiovanniBussi** [comment]
@carlocamilloni thanks, I think we should implement a generic test (so that one can just write a short c++ program to be tested) similar to the one you posted.

@HanatoK I will check how that works, perhaps it is sufficient to always link main
