### ISSUE TITLE
Enhancing performance at high parallelism - atom distribution

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#28]
I experimented a bit on BlueGeneQ and it seems that we could gain performance in atom distribution. In particular, an useful trick I found useful is to use asynchronous distribution of atoms to a subset of the processors and then using an intra-group broadcast. This is not difficult to implement, but it is a bit difficult to choose the parameters.

**Comment by carlocamilloni** [comment]
related to #145 and #241

**Comment by carlocamilloni** [comment]
I close this and open a "BENCHMARK issue"
