### ISSUE TITLE
Strength of the chemical shift restraints

### ISSUE THREAD

**Issue by juanmit** [plumed/plumed2#282]
Hi,

In that tutorial(belfast-9a)---NMR restraint simulations. 
I see  AT=0. KAPPA=0. 
AT: target
Kappa: strength of the restraints.  Why set up to 0? 

Could we control the strength of the chemical shift restrain simulations?   set up some different Kappa values?
Thanks for helping.

--Hongbin

**Comment by carlocamilloni** [comment]
Use the mailing list for questions
