### ISSUE TITLE
Missing header page for module DRR

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#296]
@HanatoK could you please add a header page for your DRR module?

In this way it will appear in the [page with the list of additional modules](https://plumed.github.io/doc-v2.4/user-doc/html/_add_mod.html). I think it should be sufficient to add a file to the `user-doc` directory (see e.g. ISDB and EDS modules).

Thanks!

**Comment by HanatoK** [comment]
@GiovanniBussi 
Sorry for my late reply.
I have changed the module name to "Extended-System Adaptive Biasing Force" since it's more popular, though the bias method name "DRR" and cltool name "drr_tool" left unchanged.
