### ISSUE TITLE
Fix GMX patch with ENERGY

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#316]
See discussion at these posts:
[old](https://groups.google.com/d/msg/plumed-users/0qn8tmEY8Dg/5XbRxwpaCAAJ)
[recent](https://groups.google.com/d/msgid/plumed-users/CAAW8t5J9QQyPZh3JdCcM24HLS5h13%3DW4ooNx6TJedA%2BKO7iqFA)

It looks like the solution is already proposed in the post, we should check it and include it.

**Comment by carlocamilloni** [comment]
addressed here 430b6a9bdcaa5e9b51af22bacc7070d7e619201f and here 7d2d64e65775695a5cc043c5650dd60a61e2d861
I would still leave a note that is safer to use nstcalcener=1 but at least on CPU all the cases I tested worked well

**Comment by GiovanniBussi** [comment]
@carlocamilloni this is closed now right?

**Comment by carlocamilloni** [comment]
It should 

Sent from my iPhone
