### ISSUE TITLE
Make patch -p more robust when patching multiple times

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#330]
When I compile `gromacs-plumed` from MacPorts, if I kill it while compiling and install it again it crashes complaining that the code was already patched. This is because plumed patch correctly detects that the code was already patched.

It would be nice to add a flag to patch that allows running it multiple times (e.g. `patch -p --repeat`) without giving errors. This option could be used from within MacPorts at least.

**Comment by maxbonomi** [comment]
Why not making by default, so that -p patches in any cases?

**Comment by GiovanniBussi** [comment]
Maybe you are right. In the end it would work in the same way as `make`: if you do it twice it's harmless
