### ISSUE TITLE
Disable make prefix=/path

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#332]
Currently, `src/lib/Makefile` is overly complicated by the fact that `prefix` might be overwritten during install. This is in principle to allow something like

    ./configure --prefix=/somewhere
    make
    make install prefix=/somewhere-else

In particular, the way it is implemented now might require recompiling all the objects where paths are hardcoded. In order to simplify `src/lib/Makefile` I plan to eliminate this feature. The only way to choose a posteriori where to install will be to run `./configure --prefix=/somewhere-else` again.

I'll do it when I will have time, if someone finds this change problematic please comment on this thread.

**Comment by carlocamilloni** [comment]
I think this solution is perfectly fine, I have never used the make install prefix feature
