### ISSUE TITLE
Selecting atoms in systems with > 100000 atoms

### ISSUE THREAD

**Issue by bdega** [plumed/plumed2#335]
Dear PLUMED community,

I've got a system, built up using VMD  and the  Charmm force field,  that  contains more than 100000 atoms. VMD enumerates  the exceeding atoms in the extended pdb format - hybrid-36 serial and sequence number (alphanumerically)....is there any way to select these atoms in PLUMED?

Thanks

G

**Comment by GiovanniBussi** [comment]
Hi,

this has been addresses here #226 . As far as I remember,  VMD does not save hybrid-36. You need some external script to convert the atom numbers. Check [this page](https://plumed.github.io/doc-v2.4/user-doc/html/pdbreader.html) in the plumed doc.

Giovanni

**Comment by GiovanniBussi** [comment]
Hi @bdega sorry maybe I misinterpreted your request. PLUMED expects h36 syntax only in PDB files. Within the PLUMED input you can safely use numbers > 100000 (E.g. `DISTANCE ATOMS=1,100000`).
