### ISSUE TITLE
RANDOM_EXCHANGES

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#342]
@carlocamilloni I was checking this line:
https://github.com/plumed/plumed2/blob/9b82f8fb52f7e1bd89b1938ce70f9254381af1b1/patches/gromacs-2016.4.diff/src/programs/mdrun/repl_ex.cpp#L1182

The code is like this:
````
   /* PLUMED */
    if(plumed_test_exchange_pattern>0) {
      for (i = 0; i < re->nrepl; i++)
      {
          re->ind[i] = i;
      }
    }
    /* END PLUMED */

    /* record which moves were made and accepted */
    for (i = 0; i < re->nrepl; i++)
    {
        re->nmoves[re->ind[i]][pind[i]] += 1;
        re->nmoves[pind[i]][re->ind[i]] += 1;
    }
    fflush(fplog); /* make sure we can see what the last exchange was */
}
````
Is it correct to reset the ind before accumulating statistics? Shouldn't it be the opposite?

Giovanni

**Comment by carlocamilloni** [comment]
I cannot remember, the code is quite old by now. I would say that yes, there was a good reason for this…

**Comment by carlocamilloni** [comment]
I just checked this while checking the new GMX2019 patch and I confirm that it works correctly as it is
