### ISSUE TITLE
Changing patch --static in order to always use a static library

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#352]
Dear all, I plan to make some simplification on the `src/lib/Makefile` but I want to be sure not to disrupt some functionality. In particular, I want to simplify the `plumed patch --static` case (see Explanation below if you are interested). If you are using this feature and want to make sure it will be functional in the future on your operating system please make the test below and report if you find any trouble. It would be particularly useful if someone can report success cases (or failures!) in uncommon operating systems (e.g.: cross compiling, AIX, etc) since unfortunately I do not have access to these kinds of machines. Thanks!

## Test

Install plumed normally, from recent master branch:

````
> git clone https://github.com/plumed/plumed2.git
> cd plumed2
> git checkout master
> prefix=/path/to/somewhere
> ./configure --prefix=$prefix
> make
> make install
````

Check if the `libplumed.a` static library has been created

````
> ls $prefix/lib/libplumed.a
````

**If not, please report it on this thread.**

Patch your favorite MD code using the just installed PLUMED.

````
> cd /root/dir/of/your/md/code
> $prefix/bin/plumed-patch --static -p
````

Compile your MD code.

**If the MD code does not link correctly, please report it on this thread**

Then try to see if the MD code works. Please try a short PLUMED file, e.g.

````
d: DISTANCE ATOMS=1,2
PRINT ARG=d
````
just to make sure that CVs are actually available.

**If it does not work correctly, please report it on this thread.**

## Explanation
PLUMED 2.4 installs some object files (in `$prefix/lib/plumed/obj/`). The master branch instead tries to install a static library (`$prefix/lib/libplumed.a`). In order to link constructors of C++ static objects, that are needed to properly register all PLUMED actions, most the objects are prelinked to a single object with `ld -r`. The `libplumed.a` file only contains a couple of pre-linked `.o` files and the linker should not be able to discard static constructors.

The static library can only be produced if both `ld -r` and `ar` work as expected, as it is now verified by `./configure` (this is the first test mentioned above). In the future, I plan to just **disable static patches** when this is not true. Patches with `--shared` or `--runtime` will still be available (although I guess that the only reason to use `--static` patches is that the other two types are not working correctly, so I don't think this will be a practical solution).

The main advantage of using a `libplumed.a` static library is that it is more standard. Some practical consequences:

- I had, from time to time, troubles in making `cmake` understand correctly that I am linking a list of object files instead of a library. This should not happen anymore.
- Other packages (e.g. MD codes) could be able to detect the presence of PLUMED just using `autoconf` (or `cmake`), even when PLUMED needs to be statically linked. Clearly, this would require passing also the list of the libraries required by PLUMED. This can be done with `pkg-config` (pkg-config files are already installed by PLUMED).

**Comment by carlocamilloni** [comment]
@GiovanniBussi I tested it on Marconi (CINECA) and it works

**Comment by marcodelapierre** [comment]
@GiovanniBussi just finished testing at Pawsey Supercomputing Centre in Perth, Australia
Linux cluster: good to go!
CRAY supercomputer: good to go!

**Comment by carlocamilloni** [comment]
@GiovanniBussi I think we can close this

**Comment by GiovanniBussi** [comment]
OK I close this. In the next days I will disable the object file installation

Giovanni
