### ISSUE TITLE
getPosition(AtomNumber) incompatible with NUMERICAL_DERIVATIVES

### ISSUE THREAD

**Issue by tonigi** [plumed/plumed2#357]
Looks like an unintended asymmetry in `src/core/ActionAtomistic.h`...

```c++
inline   // this method works
const Vector & ActionAtomistic::getPosition(int i)const {
  return positions[i];
}

inline  // this works, but NUMERICAL_DERIVATIVES are all 0
const Vector & ActionAtomistic::getPosition(AtomNumber i)const {
  return atoms.positions[i.index()];
}
```

I suspect the positions array in the latter case is not modifiable by the  differentiation code (`calculateAtomicNumericalDerivatives` in `src/core/ActionAtomistic.cpp`).

**Comment by GiovanniBussi** [comment]
@tonigi I think the asymmetry is a bit difficult to resolve. The way it works now is the following:

1. Every action has a local copy of the requested atoms, accessed by "index in the list of requested atoms".
2. If you want to access an atom by absolute index, you use the global array.

Local modifications, such as as numerical derivatives and makeWhole(), are not touching the global array. The original idea was to only use the second variant in very specific cases where it is necessary to optimize the code and we do not want to copy the atoms locally. In particular, in these cases:
````
macbook: (master) src$ git grep doNotRetrieve
core/ActionAtomistic.h:  void doNotRetrieve() {donotretrieve=true;}
generic/FitToTemplate.cpp:  // not used anymore (see notes below at doNotRetrieve())
generic/FitToTemplate.cpp:  // doNotRetrieve();
generic/WholeMolecules.cpp:  doNotRetrieve();
generic/WrapAround.cpp:  doNotRetrieve();
````
It's difficult to search c++ code for a specific overload, so I cannot tell where the second variant of getPosition is used, but I would suspect that it is exactly in the cases above. Perhaps we can just remove it and recompile to look for errors...

Is it ok for you to use the first variant?

Do you think it is sufficient to annotate in the documentation that the second variant should be used only in very special cases?

**Comment by tonigi** [comment]
I am happily using the first variant now that I found the problem :)   No issue with keeping the current behavior - I'd guess a comment is enough.    Thanks and feel free to close!

**Comment by tonigi** [comment]
On a second thought, perhaps the method can just be renamed, so it is clear that it is not equivalent...
