### ISSUE TITLE
configure can choose bad compiler combo, breaking Python wrapper

### ISSUE THREAD

**Issue by dwhswenson** [plumed/plumed2#375]
It seems like `configure` can choose bad compiler options that break the `plumed` Python package. Manually setting `CC` seems to fix the problem, but it might be good to check for incompatible options before installing. (At the very least, this issue on GitHub will help others search for the problem and find a workaround.)

*Platform:* Mac OS X 10.11.6; Python 2.7.15 (installed via MacPorts) (so old stuff, but still should work)
*PLUMED version:* 2.5.0-dev (at commit 026364f)

### Problem

By default, I didn't have `CC` (or related variables) set in my environment. When I ran `configure`, it selected `CC=gcc` and `CXX=clang++`, `LD=clang++` (as seen in `Makefile.conf`). I did not notice any problems when I ran `make test`, but when I ran `cd && source ~/plumed2/sourceme.sh && python -c "import plumed"` I got:

```pytb
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: dlopen(/Users/dwhs/plumed2/python/plumed.so, 2): Symbol not found: __ZTINSt8ios_base7failureB5cxx11E
  Referenced from: /Users/dwhs/plumed2/python/plumed.so
  Expected in: flat namespace
 in /Users/dwhs/plumed2/python/plumed.so
```

### Workaround

I set `CC` manually so you wouldn't mix `clang` and `gcc` object code: `export CC=clang` before running the installation procedure. Then it imports without complaint.

#### My installation procedure:

```bash
make clean
./configure --prefix=$HOME
make -j 4 all
make install
```

#### Testing:
```bash
make test
cd && source ~/plumed2/sourceme.sh && python -c "import plumed"
```

**Comment by GiovanniBussi** [comment]
@dwhswenson thanks for your comment!

I think it is difficult to guess the name of the CC compiler given the CXX compiler. Anyway, it's true that since v2.5 (now master) by default we will pick `clang++` on OSX. Given this, I would propose changing the first choice for CC to be `clang` on OSX.

Do you think this would solve the issue?

Thanks again for reporting!

Giovanni

**Comment by dwhswenson** [comment]
Yes, I think that would probably solve it (about 99.9% of the time, at least). I would assume that if someone has `clang++` they also have `clang`! (And that's a lot easier than trying to identify families of compilers in the makefile.) Thanks!
