### ISSUE TITLE
Virial not passed properly to Lammps

### ISSUE THREAD

**Issue by PabloPiaggi** [plumed/plumed2#377]
I have made the virial contribution test described [here](http://plumed.github.io/doc-master/developer-doc/html/_how_to_plumed_your_m_d.html) and it seems that in the latest version of lammps (master branch) the virial is not passed properly. Older versions of lammps, for instance 14May16, passed the test.

I would therefore say that currently it is not safe to perform simulations at constant pressure using Lammps.

**Comment by GiovanniBussi** [comment]
Hi I think @gtribello just found the same problem and is working on a patch. Thanks for reporting and for taking the time to find with which version the problem appeared! Giovanni

**Comment by gtribello** [comment]
Hello @PabloPiaggi 

I am working on a patch.  I am having some difficulties with some of the tests, however, so it might not be ready for a while.  If you want to get up and running quick go into fix_plumed.cpp and look for the following line:

virial_flag=1;

add below it:

thermo_virial=1;

and then that test should be running.  Alternatively, if you want to take a look at what I am doing (I have made a number of changes) look at my fork of LAMMPS on github.  I think you should be able to clone this.

Lastly, if you want to help me out with this I would greatly appreciate it as I am a little stuck ;-)

**Comment by PabloPiaggi** [comment]
Hello @gtribello and @GiovanniBussi ,
 
I had tried to fix the patch but I didn't realize that thermo_virial=1 was missing. Thanks for the tip.

I have a few comments/thoughts regarding the patch:

1) I think that Lammps has a standard way to add a virial contribution in a fix and it is through the function v_tally (see for example fix_shake.cpp). I think that the lines:

`// retransform virial to lammps representation:`
`Fix::virial[0]=-plmd_virial[0][0];`
`Fix::virial[1]=-plmd_virial[1][1];`
`Fix::virial[2]=-plmd_virial[2][2];`
`Fix::virial[3]=-plmd_virial[0][1];`
`Fix::virial[4]=-plmd_virial[0][2];`
`Fix::virial[5]=-plmd_virial[1][2];`

could be changed to something like:

`double v_lmp[6];`
`v_lmp[0]=-plmd_virial[0][0]-virial[0];`
`v_lmp[1]=-plmd_virial[1][1]-virial[1];`
`v_lmp[2]=-plmd_virial[2][2]-virial[2];`
`v_lmp[3]=-plmd_virial[0][1]-virial[3];`
`v_lmp[4]=-plmd_virial[0][2]-virial[4];`
`v_lmp[5]=-plmd_virial[1][2]-virial[5];`
`v_tally(nlocal,list,1.0,v_lmp);`

where list=[0,1,...,nlocal-1] should be calculated beforehand. This would be cleaner and would also have the advantage of setting properly the per-atom stress.

2) It seems that the potential energy is calculated at every timestep regardless of whether plumed needs it or not. Perhaps its calculation should be triggered only when needed.

3) I think it is possible to "tally" the bias potential in order to add it to the energy of the system. I believe this would allow one to do monte carlo simulations (e.g. fix gcmc) using the bias from plumed.

I hope you find these ideas useful. I don't have much time available but I'm happy to help.

Pablo
