### ISSUE TITLE
Use Plumed2 with LAMMPS

### ISSUE THREAD

**Issue by yuanchaohu** [plumed/plumed2#378]
Hi, 

I am a new comer to Plumed2 and want to use it with lammps? How can I install lammps with plumed? Which version of lammps should I choose? I don't found the fix_plumed command in lammps?

Thank you very much!

**Comment by GiovanniBussi** [comment]
@yuanchaohu notice that the PLUMED interface has been [permanently inserted into LAMMPS](https://github.com/lammps/lammps/pull/1180) a few days ago. This means that as of the next LAMMPS version you will find a package [USER-PLUMED](https://github.com/lammps/lammps/tree/master/src/USER-PLUMED).

I close this issue. If you have further questions, please write on our mailing list.
