### ISSUE TITLE
Conditional execution of things (e.g. for DUMPATOMS)

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#38]
This could be a simple way to emulate the -interval option of driver in plumed 1. Doing it in the input file would allow to do it on the fly during the simulation.

**Comment by LizheZhu** [comment]
Hi, Giovanni. This issue has been there for quite a while. But I do believe implementing the -interval option in plumed2 is necessary and makes plumed2 more complete. Is there any plan to implement this in near future?
