### ISSUE TITLE
UFED calculations with PLUMED 2, it is implemented ?

### ISSUE THREAD

**Issue by DanielWicz** [plumed/plumed2#381]
The UFED (Unified Free Energy Dynamics) is implemented in the PLUMED 2 already? Since I cannot find it, I found only that the method is implemented in the PLUMED 1.3 release and was successfully used in the release.

**Comment by HanatoK** [comment]
Hi @DanielWicz ,
You can take a look at the EXTENDED_LAGRANGIAN bias. As far as I know UFED is a combination of TAMD and metadynamics. For example, you can choose a high temperature to perform TAMD and then add metadynamics bias on the fictitious CVs.
```
phi: TORSION ATOMS=5,7,9,15
psi: TORSION ATOMS=7,9,15,17
ex: EXTENDED_LAGRANGIAN ARG=phi,psi KAPPA=20,20.0 TAU=0.1,0.1 FRICTION=10,10 TEMP=3000
METAD ARG=ex.phi_fict,ex.psi_fict PACE=100 SIGMA=0.35,0.35 HEIGHT=0.1
# monitor the two variables
PRINT STRIDE=10 ARG=phi,psi,ex.phi_fict,ex.psi_fict FILE=COLVAR
```

**Comment by GiovanniBussi** [comment]
Hi! I guess this can be closed. Feel free to reopen it if there is further clarification needed.
