### ISSUE TITLE
Add PHASES to COM

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#395]
I think it should be done in v2.5, for consistency with CENTER. Should be easy.

**Comment by carlocamilloni** [comment]
Is this closed now?

**Comment by GiovanniBussi** [comment]
No, PHASES is only in CENTER new. We should add it to COM. Perhaps CENTER and COM should share some code since they basically do the same thing.

**Comment by carlocamilloni** [comment]
Actually I think we should remove COM, because CENTER with MASS is already doing it

**Comment by GiovanniBussi** [comment]
Yes but it's always annoying to rewrite input files... Maybe we can:
- delete vatom::COM class
- register vatom::Center twice (with names COM and CENTER)
- when used with name COM, switch on MASSES

In principle this should go through all regtests and work without any
change.

What do you think?

**Comment by carlocamilloni** [comment]
Yes I was thinking the same

C

**Comment by carlocamilloni** [comment]
I merged the two implementation as we mentioned above, this closes this issue
