### ISSUE TITLE
Can not configure plumed in my system(Windows terminal)

### ISSUE THREAD

**Issue by yamahachou** [plumed/plumed2#397]
I am a beginner using PLUMED and had some troubles when configuring and compiling PLUMED and I just could not solve it. 
I first used the command git clone https://github.com/plumed/plumed2.git to download to files needed, making a directory called "plumed2_build" and then entering plumed2 to execute the command: ./configure --prefix=/projects/${USER}/src/plumed2_build. However, it ended up with the warning as follows: 
[problem1.JPG](https://ppt.cc/fB8bxx)

I actually didn't quite understand this warning. I followed the suggestion, adding the two lines to my .bashrc file. I then temporarily neglected the problem and used the command "make -j 4" and "make install" to install PLUMED. However, in the step of "make -j 4", I encountered a series of warnings as follows:

[problem2.JPG](https://ppt.cc/fYINAx)

Then, I used the command "make install" to install PLUMED. After that, I tried to use the command "/projects/${USER}/src/plumed2_build/bin/plumed patch -p" to patch PLUMED with GROMACS 2018.3. As a result, I had the following error and could not continue:

[problem3.JPG](https://ppt.cc/f0emjx)

I have made sure that the libplumedKernel.so exists in the plumed2_build/lib/ directory but I could not solve this error after many different trials. I'm wondering if the series of warning in the step of "make -j 4" and this error were related to the first warning I got when configuring PLUMED. Do you have any ideas what can cause these problems and how I can resolve it?

p.s I am using Windows terminal

Thank you so much

**Comment by GiovanniBussi** [comment]
The same question was answered today on the mailing list:
https://groups.google.com/d/msgid/plumed-users/a3de7153-fd09-41b2-b1b1-48f32cb0461d%40googlegroups.com?utm_medium=email&utm_source=footer

In case the answer is not clear or not solving your problem, please answer to that email.
