### ISSUE TITLE
Adaptive hills (GEOM) cannot be used with ENERGY

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#4]
The gradients of ENERGY are never stored, so that it is not possible to use the adaptive hills based on projections of gradients. It is possible to remove this constraint, but it takes a bit of work and, to me, it is not clear if it is useful.

**Comment by carlocamilloni** [comment]
Shall we merge this commit?

**Comment by GiovanniBussi** [comment]
@carlocamilloni thanks for checking all issues (including this very old one).

I think we had no answer about this and probably no one is interested. Since this was based on a very old version it would be likely difficult to merge it. I thus close the issue. The commit will stay there anyway on github if someone is interested later.
