### ISSUE TITLE
NAMD 2.13 seems not to work with patch --shared

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#406]
This has been reported in #404 by @dvdesolve.

It looks like we are making some mess in the Makefile while adding plumed flags.

**Comment by dvdesolve** [comment]
Nevertheless I think that it's problem with static/shared charm-6.8.2. I've just rebuilt NAMD-2.13 with charm-6.8.2 with the next options:

## charm-6.8.2
`./build charm++ multicore-linux64 --build-shared --with-production`

## NAMD-2.13
```
./config Linux-x86_64-g++ --charm-arch multicore-linux64 --with-fftw3 --with-cuda
/opt/plumed/plumed24/bin/plumed patch -p -e namd-2.13
cd Linux-x86_64-g++
make
```

After that there are a lot of `*.so` files in `lib_so` directory and NAMD builds successfully (but some warnings are shown after linking)
[build-with-shared.txt](https://github.com/plumed/plumed2/files/2550333/build-with-shared.txt)

And there are dynamic dependencies for the binary `namd2`:
```
namd2
	linux-vdso.so.1 (0x00007ffe9a798000)
	/opt/plumed/plumed24/lib/libplumed.so (0x0000148b0ea87000)
	libmoduleGreedyRefineLB.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleGreedyRefineLB.so (0x0000148b0ea74000)
	libmoduleCkLoop.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleCkLoop.so (0x0000148b0ea63000)
	libmoduleCkMulticast.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleCkMulticast.so (0x0000148b0ea5e000)
	libmoduleGreedyLB.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleGreedyLB.so (0x0000148b0ea4e000)
	libmoduleRefineLB.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleRefineLB.so (0x0000148b0ea41000)
	libmoduleHybridLB.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleHybridLB.so (0x0000148b0ea37000)
	libmoduleNeighborLB.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleNeighborLB.so (0x0000148b0ea2c000)
	libckmain.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libckmain.so (0x0000148b0ea27000)
	libck.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libck.so (0x0000148b0e807000)
	libmemory-default.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmemory-default.so (0x0000148b0e7ff000)
	libthreads-default.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libthreads-default.so (0x0000148b0e7f8000)
	libconv-cplus-y.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libconv-cplus-y.so (0x0000148b0e7de000)
	libconv-core.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libconv-core.so (0x0000148b0e78a000)
	libtmgr.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libtmgr.so (0x0000148b0e782000)
	libconv-util.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libconv-util.so (0x0000148b0e751000)
	libconv-partition.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libconv-partition.so (0x0000148b0e74c000)
	libldb-rand.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libldb-rand.so (0x0000148b0e746000)
	libconv-ldb.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libconv-ldb.so (0x0000148b0e715000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x0000148b0e6a2000)
	libckqt.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libckqt.so (0x0000148b0e69b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x0000148b0e696000)
	librt.so.1 => /usr/lib/librt.so.1 (0x0000148b0e68c000)
	libmoduleNDMeshStreamer.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmoduleNDMeshStreamer.so (0x0000148b0e687000)
	libmodulecompletion.so => /home/viktor/build/src/namd/Linux-x86_64-g++/.rootdir/charm-6.8.2/multicore-linux64/lib_so/libmodulecompletion.so (0x0000148b0e670000)
	libm.so.6 => /usr/lib/libm.so.6 (0x0000148b0e4eb000)
	libmvec.so.1 => /usr/lib/libmvec.so.1 (0x0000148b0e4be000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000148b0e32d000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x0000148b0e313000)
	libc.so.6 => /usr/lib/libc.so.6 (0x0000148b0e14f000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x0000148b1af6e000)
	libgsl.so.23 => /usr/lib/libgsl.so.23 (0x0000148b0dccc000)
	libgslcblas.so.0 => /usr/lib/libgslcblas.so.0 (0x0000148b0da8d000)
	libz.so.1 => /usr/lib/libz.so.1 (0x0000148b0d876000)
	libmatheval.so.1 => /usr/lib/libmatheval.so.1 (0x0000148b0d866000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x0000148b0cf84000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x0000148b0cd30000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x0000148b0cd00000)
	libfl.so.2 => /usr/lib/libfl.so.2 (0x0000148b0cafc000)
	libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x0000148b0c880000)
	libquadmath.so.0 => /usr/lib/../lib/libquadmath.so.0 (0x0000148b0c83d000)
```

Nice to see that `libplumed.so` is in place. Not sure what to do with these absolute paths to Charm++ modules...

**Comment by GiovanniBussi** [comment]
Notice that `PLUMED_LOAD` is set to the absolute path of `libplumed.so`. If I remember correctly, on Linux if you link against the absolute path and soname is not set, the soname will be set to the absolute path. As a consequence, `libplumed.so` will be found correctly later. Notice that in PLUMED 2.5 the soname **is added** and is equal to the file name. So, if you patch with plumed 2.5, namd will look for `libplumed.so` (no full path!).

Then, if a dependence is stored as a soname the dynamic linker will look for it in standard places + `LD_LIBRARY_PATH`, and then in places stored in the Rpath. Probably the makefile is setting Rpath and thus it is able to find the libraries. In case you have troubles with finding libplumed.so at runtime, you might have to add `/opt/plumed/plumed24/lib` to `LD_LIBRARY_PATH`.

Do you think I can close the issue?

**Comment by dvdesolve** [comment]
There is no problem with `libplumed.so`, because we're using env-modules and can set `LD_LIBRARY_PATH` conveniently while loading module for NAMD.

Regarding this issue: seems like `PLUMED` by itself not messing anything in the `Makefile` and the problem with linking is related to the `charmc` compiler script in charm-6.8.2.
So, I think we should instead file a bug for Charm++ and you can close current issue

Thank you!

**Comment by jcphill** [comment]
Have you tried not using "--build-shared" but rather "--no-build-shared" when building Charm++?

**Comment by dvdesolve** [comment]
According to the `build` script inside Charm++ package, **--no-build-shared** option is set by default

**Comment by dvdesolve** [comment]
Filed [a bug](https://charm.cs.illinois.edu/redmine/issues/2026) on Charm++ tracker

**Comment by jcphill** [comment]
> According to the `build` script inside Charm++ package, **--no-build-shared** option is set by default

In your first comment above you are setting --build-shared.

**Comment by dvdesolve** [comment]
Oh, sorry, I was a bit unclear
the log from file with.txt refers to the classic build way: `./build charm++ multicore-linux64 --with-production`
In that way --no-build-shared is set implicitly
After that I tried to recompile the whole package with explicit --build-shared

**Comment by jcphill** [comment]
OK, I can follow this now. What is PLUMED_LOAD defined as?

**Comment by dvdesolve** [comment]
According to the plumed distribution files PLUMED_LOAD gets differents contents in different patch modes:
```
[viktor@desolve-lab /opt/plumed/plumed24/lib/plumed/src/lib]$ cat Plumed.inc
PLUMED_RUNTIME_LOAD= "/opt/plumed/plumed24/lib/libplumedWrapper.a" -ldl  
PLUMED_STATIC_LOAD= "/opt/plumed/plumed24/lib/plumed/obj/kernel.o" "/opt/plumed/plumed24/lib/plumed/obj/PlumedStatic.o" -ldl  -lgsl -lgslcblas -lz -lmatheval -ldl -llapack -lblas  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -rdynamic -fopenmp 
PLUMED_SHARED_LOAD= "/opt/plumed/plumed24/lib/libplumed.so" -ldl  
PLUMED_RUNTIME_DEPENDENCIES=
PLUMED_STATIC_DEPENDENCIES= "/opt/plumed/plumed24/lib/plumed/obj/kernel.o" "/opt/plumed/plumed24/lib/plumed/obj/PlumedStatic.o"
PLUMED_SHARED_DEPENDENCIES= "/opt/plumed/plumed24/lib/libplumed.so"

[viktor@desolve-lab /opt/plumed/plumed24/lib/plumed/src/lib]$ cat Plumed.inc.runtime 
# PLUMED: runtime installation
PLUMED_LOAD= "/opt/plumed/plumed24/lib/libplumedWrapper.a" -ldl  
PLUMED_DEPENDENCIES=

[viktor@desolve-lab /opt/plumed/plumed24/lib/plumed/src/lib]$ cat Plumed.inc.shared 
# PLUMED: shared installation
PLUMED_LOAD= "/opt/plumed/plumed24/lib/libplumed.so" -ldl  
PLUMED_DEPENDENCIES= "/opt/plumed/plumed24/lib/libplumed.so"

[viktor@desolve-lab /opt/plumed/plumed24/lib/plumed/src/lib]$ cat Plumed.inc.static 
# PLUMED: static installation
PLUMED_LOAD= "/opt/plumed/plumed24/lib/plumed/obj/kernel.o" "/opt/plumed/plumed24/lib/plumed/obj/PlumedStatic.o" -ldl  -lgsl -lgslcblas -lz -lmatheval -ldl -llapack -lblas  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -rdynamic -fopenmp 
PLUMED_DEPENDENCIES= "/opt/plumed/plumed24/lib/plumed/obj/kernel.o" "/opt/plumed/plumed24/lib/plumed/obj/PlumedStatic.o"
```

I think that @GiovanniBussi can help here

**Comment by jcphill** [comment]
OK, in this case it is apparently "/opt/plumed/plumed23/lib/libplumed.so" -ldl

One thing I can think of is that this bit in charmc should probably have a *.so pattern added:

        -l*|*.a)
                if [ -n "$POST_LANGUAGE" ]
                then
                        POST_LIBRARIES="$POST_LIBRARIES $arg"
                else
                        PRE_LIBRARIES="$PRE_LIBRARIES $arg"
                fi
                INPUT_GIVEN="1"
                ;;

Otherwise I think you're hitting this bit:

        *.o|*.so|*.so.*|*.sl|*.a|*.dylib|*.co)
                # make sure to link against shared charm library if creating a shared object:
                case $FILE in
                        *.so|*.so.*|*.dylib) CHARM_SHARED=1 ;;
                esac
                [ ! -s $FILE ] && Abort "$FILE: file not recognized: File truncated"
                OBJECTFILES="$OBJECTFILES $FILE"
                ;;

**Comment by jcphill** [comment]
I think the best workaround would be to use PLUMED_LOAD="L/path/to/plumed/lib -lplumed -ldl" rather than listing /path/to/plumed/lib/libplumed.so explicitly as a file.

**Comment by dvdesolve** [comment]
In that case maybe it is worth to make appropriate changes in Plumed scripts

**Comment by dvdesolve** [comment]
> I think the best workaround would be to use PLUMED_LOAD="-L/path/to/plumed/lib -lplumed -ldl" rather than listing /path/to/plumed/lib/libplumed.so explicitly as a file.

I've just built NAMD-2.13 with plumed-shared successfully. Here is the diff of PLUMED distribution files:
```patch
--- Plumed.inc	2018-11-05 21:31:05.000000000 +0300
+++ Plumed.inc	2018-11-06 12:36:27.662132129 +0300
@@ -1,6 +1,6 @@
 PLUMED_RUNTIME_LOAD= "/opt/plumed/plumed24/lib/libplumedWrapper.a" -ldl  
 PLUMED_STATIC_LOAD= "/opt/plumed/plumed24/lib/plumed/obj/kernel.o" "/opt/plumed/plumed24/lib/plumed/obj/PlumedStatic.o" -ldl  -lgsl -lgslcblas -lz -lmatheval -ldl -llapack -lblas  -Wl,-O1,--sort-common,--as-needed,-z,relro,-z,now -rdynamic -fopenmp 
-PLUMED_SHARED_LOAD= "/opt/plumed/plumed24/lib/libplumed.so" -ldl  
+PLUMED_SHARED_LOAD= "-L/opt/plumed/plumed24/lib" -lplumed -ldl  
 PLUMED_RUNTIME_DEPENDENCIES=
 PLUMED_STATIC_DEPENDENCIES= "/opt/plumed/plumed24/lib/plumed/obj/kernel.o" "/opt/plumed/plumed24/lib/plumed/obj/PlumedStatic.o"
-PLUMED_SHARED_DEPENDENCIES= "/opt/plumed/plumed24/lib/libplumed.so"
+#PLUMED_SHARED_DEPENDENCIES= "/opt/plumed/plumed24/lib/libplumed.so"
--- Plumed.inc.shared	2018-11-05 21:31:05.000000000 +0300
+++ Plumed.inc.shared	2018-11-06 12:37:11.834960032 +0300
@@ -1,3 +1,3 @@
 # PLUMED: shared installation
-PLUMED_LOAD= "/opt/plumed/plumed24/lib/libplumed.so" -ldl  
-PLUMED_DEPENDENCIES= "/opt/plumed/plumed24/lib/libplumed.so"
+PLUMED_LOAD= "-L/opt/plumed/plumed24/lib" -lplumed -ldl
+#PLUMED_DEPENDENCIES= "/opt/plumed/plumed24/lib/libplumed.so"
```

Linking log and `ldd` output are in attached files
[ldd.txt](https://github.com/plumed/plumed2/files/2552621/ldd.txt)
[linking.txt](https://github.com/plumed/plumed2/files/2552622/linking.txt)

Building process is the default:
```
./build charm++ multicore-linux64 --with-production
./config Linux-x86_64-g++ --charm-arch multicore-linux64 --with-fftw3 --with-cuda
/opt/plumed/plumed24/bin/plumed patch -p -e namd-2.13
cd Linux-x86_64-g++
make
```
All things seems fine

@GiovanniBussi is my diff correct? Should we make commit with patch?

@jcphill thank you for the suggestion!

**Comment by GiovanniBussi** [comment]
Concerning this (*I am not sure which is the precedence between -L options and LIBRARY_PATH directories*), maybe the answer is in [this page](https://gcc.gnu.org/onlinedocs/gcc/Environment-Variables.html):

*Linking using GCC also uses these directories when searching for ordinary libraries for the -l option (but directories specified with -L come first).*

 If `-L` has the priority over `LIBRARY_PATH`, I would be happy to use it (at least in PLUMED 2.5). It would be good if anyone can comment about these priorities in general (I am not sure how system and compiler dependent they are).

**Comment by dvdesolve** [comment]
Actually we have a few options for PLUMED-2.4:
1. Use static linking mode while patching NAMD source
1. Use shared linking mode while patching NAMD source (but we need shared version of Charm++ too)
1. With shared linking patch-mode for the case of NAMD source we also apply patch to fix `charmc` script to recognize `*.so` (or may be only `libplumed.so`) the same way as `*.a` libs

But as for me two first ways deserves special notion in the documentation

**Comment by GiovanniBussi** [comment]
I would vote for option 2. I think using shared libraries rather than
static libraries has no disadvantages, and I cannot imagine why one would
need charm linked as a static library and plumed linked as a shared library

Giovanni

**Comment by jcphill** [comment]
One more stupid compiler trick that might solve this:
PLUMED_SHARED_LOAD= -Wl,"/opt/plumed/plumed24/lib/libplumed.so" -ldl
(-Wl,... passes comma-separated list ... to ld as space-separated arguments.)

**Comment by GiovanniBussi** [comment]
@jcphill I have small doubt on this: what would happen if someone tries to use `$(PLUMED_LOAD)` on the command line of the linker rather than that of the compiler? I suppose the linker cannot interpret correctly the `-Wl,` prefix.

**Comment by jcphill** [comment]
You could have the plumed patch add -Wl, to PLUMED_LOAD in the NAMD Makefile then, so it wouldn't affect other codes.

**Comment by GiovanniBussi** [comment]
@jcphill this is not straightforward to implement. Currently, the `Plumed.inc` files where these variables are defined are included by the MD code Makefile (pretty much like a C include file), so they are not customized per MD code. I think this is the correct (and scalable) approach. For instance, there are already several MD codes around that use our `Plumed.inc` files. We cannot make a specific case for all of them within PLUMED.

Maybe a good solution would be to use some Makefile function to modify the variable within the NAMD makefile. We can of course ship this function together with our patch for NAMD (it would be included in the NAMD makefile). However, makefile syntax is not really user friendly....

Do you know if NAMD makefile is limited to GNUMake or is it expected to support other make versions?

**Comment by jcphill** [comment]
I think NAMD requires gmake, although nothing recent.

**Comment by GiovanniBussi** [comment]
@dvdesolve could you please try if the modified NAMD patch (in branch v2.4-namd-patches2) solves the issue with patching with `--shared`?

Thanks!

Giovanni

**Comment by dvdesolve** [comment]
Seems like you have forgotten change numbers for patch alignment. During the building of NAMD patched with new plumed version (from the branch you've mentioned) I have the following error:
```
PLUMED patching tool

MD engine: namd-2.13
PLUMED location: /opt/plumed/plumed24-git/lib/plumed
diff file: /opt/plumed/plumed24-git/lib/plumed/patches/namd-2.13.diff
sourcing config file: /opt/plumed/plumed24-git/lib/plumed/patches/namd-2.13.config
Linking Plumed.h, Plumed.inc, and Plumed.cmake (shared mode)
Patching with stored diff
patching file ./Makefile
patch: **** malformed patch at line 22:  COLVARSGXXFLAGS= $(GXXFLAGS)

patching file ./src/ComputeMgr.C
Hunk #1 succeeded at 92 with fuzz 4 (offset 12 lines).
Hunk #2 succeeded at 1171 (offset 263 lines).
patching file ./src/SimParameters.C
Hunk #1 succeeded at 1770 (offset 446 lines).
Hunk #2 succeeded at 5451 with fuzz 1 (offset 1145 lines).
Hunk #3 succeeded at 5537 (offset 1146 lines).
patching file ./src/SimParameters.h
Hunk #1 succeeded at 548 with fuzz 3 (offset 118 lines).
```

If you take look at `patches/namd-2.13.diff` from the `master` and `v2.4-namd-patches2` you can see that you've forgotten to change number of lines changed in the patch definition:

```
--- ./Makefile.preplumed
+++ ./Makefile
@@ -359,16 +359,18 @@
```

I think that for new patch it should be like this:
```
--- ./Makefile.preplumed
+++ ./Makefile
@@ -359,16 +359,21 @@
```

**Comment by GiovanniBussi** [comment]
Mm, I tried to edit the patch file by hand, bad idea...

I pushed fresh ones to v2.4-namd-patches3. Let me know if they work

Thanks!

Giovanni

**Comment by dvdesolve** [comment]
Seems like patching was done properly:
```
PLUMED patching tool

MD engine: namd-2.13
PLUMED location: /opt/plumed/plumed24-git/lib/plumed
diff file: /opt/plumed/plumed24-git/lib/plumed/patches/namd-2.13.diff
sourcing config file: /opt/plumed/plumed24-git/lib/plumed/patches/namd-2.13.config
Linking Plumed.h, Plumed.inc, and Plumed.cmake (shared mode)
Patching with stored diff
patching file ./Makefile
patching file ./src/ComputeMgr.C
patching file ./src/SimParameters.C
Hunk #1 succeeded at 1770 (offset -8 lines).
Hunk #2 succeeded at 5452 (offset -2 lines).
Hunk #3 succeeded at 5537 (offset -2 lines).
patching file ./src/SimParameters.h
Hunk #1 succeeded at 548 (offset 1 line).
```

Linking is also done properly:
```
namd2
	linux-vdso.so.1 (0x00007ffe27fa8000)
	libfakeroot.so => /usr/lib/libfakeroot/libfakeroot.so (0x000014d756abe000)
	libpthread.so.0 => /usr/lib/libpthread.so.0 (0x000014d756a4b000)
	libdl.so.2 => /usr/lib/libdl.so.2 (0x000014d756a46000)
	librt.so.1 => /usr/lib/librt.so.1 (0x000014d756a3c000)
	/opt/plumed/plumed24-git/lib/libplumed.so (0x000014d756378000)
	libm.so.6 => /usr/lib/libm.so.6 (0x000014d7561f3000)
	libmvec.so.1 => /usr/lib/libmvec.so.1 (0x000014d7561c4000)
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x000014d756035000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x000014d75601b000)
	libc.so.6 => /usr/lib/libc.so.6 (0x000014d755e57000)
	/lib64/ld-linux-x86-64.so.2 => /usr/lib64/ld-linux-x86-64.so.2 (0x000014d762d70000)
	libgsl.so.23 => /usr/lib/libgsl.so.23 (0x000014d7559d4000)
	libgslcblas.so.0 => /usr/lib/libgslcblas.so.0 (0x000014d755795000)
	libz.so.1 => /usr/lib/libz.so.1 (0x000014d75557c000)
	libmatheval.so.1 => /usr/lib/libmatheval.so.1 (0x000014d75556e000)
	liblapack.so.3 => /usr/lib/liblapack.so.3 (0x000014d754c8c000)
	libblas.so.3 => /usr/lib/libblas.so.3 (0x000014d754a38000)
	libgomp.so.1 => /usr/lib/libgomp.so.1 (0x000014d754a08000)
	libfl.so.2 => /usr/lib/libfl.so.2 (0x000014d754a01000)
	libgfortran.so.5 => /usr/lib/libgfortran.so.5 (0x000014d754785000)
	libquadmath.so.0 => /usr/lib/../lib/libquadmath.so.0 (0x000014d754742000)
```

Thank you!

**Comment by jcphill** [comment]
Can someone confirm that this Charm++ patch fixes the original issue?
https://charm.cs.illinois.edu/gerrit/#/c/charm/+/4884/
