### ISSUE TITLE
Problems with configure process for Arch Linux makepkg

### ISSUE THREAD

**Issue by dvdesolve** [plumed/plumed2#407]
PLUMED is available for Arch Linux users via [AUR repo](https://aur.archlinux.org/packages/plumed/). If you try to build it with any AUR helper (e. g. `yay`) or by hand with `makepkg` you get the following configure log:
[makepkg.txt](https://github.com/plumed/plumed2/files/2552977/makepkg.txt)
Please notice the lines
```
configure: I will now check if C++ objects can be linked by C/Fortran compilers
configure: This is relevant if you want to use plumed patch --static on a non-C++ code
checking whether C can link a C++ object... no
checking whether C can link a C++ object with library -lstdc++... no
checking whether C can link a C++ object with library -lc++... no
checking whether C can link a C++ object with library -lmpi_cxx... no
configure: WARNING: You might have problems linking C programs.
configure: WARNING: Please add c++ library to LIBS
checking whether FORTRAN can link a C++ object... no
checking whether FORTRAN can link a C++ object with library -lstdc++... no
checking whether FORTRAN can link a C++ object with library -lc++... no
checking whether FORTRAN can link a C++ object with library -lmpi_cxx... no
configure: WARNING: You might have problems linking FORTRAN programs.
configure: WARNING: Please add c++ library to LIBS
```
Seems like if you not using static patching this is no need to worry about. But sometimes static linking is necessary...

One interesting thing: if you download & untar the same source file by hand and then try to configure package using the same line that is in PKGBUILD you get properly configured source without any warnings:
[manual.txt](https://github.com/plumed/plumed2/files/2552984/manual.txt)
Again, corresponding lines:
```
configure: I will now check if C++ objects can be linked by C/Fortran compilers
configure: This is relevant if you want to use plumed patch --static on a non-C++ code
checking whether C can link a C++ object... no
checking whether C can link a C++ object with library -lstdc++... yes
checking whether FORTRAN can link a C++ object... yes
```

So, why there is the difference between `PKGBUILD` way and manual compiling? Should we use special flags for building PLUMED via `PKGBUILD`?

**Comment by GiovanniBussi** [comment]
Hi,

it might be that the additional flags used by PKGBUILD are incompatible with direct linking of the C++ library. Notice that it is definitely not easy to link a C++ program using a C/FORTRAN linker, since you should tell to the linker where the standard C++ library is. We try to guess its name in `./configure`, but it might be that the path is not reachable.

You could try to do the following:
- Use `ldd libplumedKernel.so` to see where the c++ standard library is
- Configure PLUMED adding to LDFLAGS something like `-L/path/to/c++/lib -lnameoflib`

Giovanni

**Comment by dvdesolve** [comment]
On my work PC I have the following:
```
[viktor@desolve-lab /opt/plumed/plumed24/lib]$ ldd libplumedKernel.so | grep stdc++
	libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000154e72ad1000)
```

Seems like fakeroot environment used by `makepkg` makes libstdc++ unusable

**Comment by GiovanniBussi** [comment]
Can you check if file `/usr/lib/libstdc++.so` exists? It should be a symbolic link to `/usr/lib/libstdc++.so.6`. Or maybe you can add the same commands (`ldd libplumedKernel.so | grep stdc++` and `ls /usr/lib/libstdc++.*`) to the pkgbuild script (if possible) to see what they show

**Comment by dvdesolve** [comment]
All needed libs are in place:
```
[viktor@desolve-lab /tmp/plumed]$ ls -lha /usr/lib | grep stdc++
-rw-r--r--   1 root root  4,8M авг 31 15:44 libstdc++.a
-rw-r--r--   1 root root  1,5M авг 31 15:44 libstdc++fs.a
lrwxrwxrwx   1 root root    19 авг 31 15:44 libstdc++.so -> libstdc++.so.6.0.25
lrwxrwxrwx   1 root root    19 авг 31 15:44 libstdc++.so.6 -> libstdc++.so.6.0.25
-rwxr-xr-x   1 root root   14M авг 31 15:44 libstdc++.so.6.0.25
```

Also I've added debug lines to the `PKGBUILD`:
```
echo `ls /usr/lib/libstdc++.*`
ldd ${pkgdir}/usr/lib/libplumedKernel.so | grep stdc++
```
and as it could be seen from output all files exists:
```
/usr/lib/libstdc++.a /usr/lib/libstdc++.so /usr/lib/libstdc++.so.6 /usr/lib/libstdc++.so.6.0.25
libstdc++.so.6 => /usr/lib/libstdc++.so.6 (0x0000153b43bbe000)
```

**Comment by dvdesolve** [comment]
Seems like patch works fine. Just tested with `master` branch:

```
checking whether C++ objects can be grouped with ld -r -o... yes
checking whether static libraries can be created with ar cr... yes
checking whether static-object constructors can be linked from a static archive... yes
configure: I will now check if C++ objects can be linked by C/Fortran compilers
configure: This is relevant if you want to use plumed patch --static on a non-C++ code
checking whether C can link a C++ object... no
checking whether C can link a C++ object with library -lstdc++... yes
checking whether FORTRAN can link a C++ object... yes
```

Thank you!

**Comment by GiovanniBussi** [comment]
@dvdesolve thanks for reporting this! It was me being lazy. We have two variables there `link_installed` and `link_uninstalled`. Only the former is used from the installed plumed, but the latter contains the path to the compilation directory. I think it is harmless, but I will try to fix it.
