### ISSUE TITLE
Possible bug in GMX 2018 + hrex

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#410]
It looks like there might be a bug in GMX 2018 patch with hrex. It was reported [on the mailing list](https://groups.google.com/d/msgid/plumed-users/88891c49-96e4-4409-b57f-b6d2304bc991%40googlegroups.com?utm_medium=email&utm_source=footer) and should be investigated.

**Comment by carlocamilloni** [comment]
I haven't tried to reproduce the bug, but I double checked the flags used to determine the force calculation and there is no difference between GMX2016 and GMX2018

**Comment by GiovanniBussi** [comment]
I have seen something similar in the past, but it never happened again once I reinstalled gromacs. I close this for now.

**Comment by GiovanniBussi** [comment]
I guess this issue is the same that has been reported [here](https://groups.google.com/d/msgid/plumed-users/18867086-b9cc-488b-bdac-f039a4a71d96%40googlegroups.com?utm_medium=email&utm_source=footer).

Actually there appear to be a solution suggested in that thread! I think we should either:
- Force deactivation of dynamic load balancing when using `-hrex`
- Add in the hrex documentation that one should disable dynamic load balancing

Perhaps the second choice is better since there are many cases where crashes do not show up, I guess results are still correct (hopefully!), and I suspect that disabling dynamic load balancing would just slow down the simulation.

**Comment by GiovanniBussi** [comment]
@carlocamilloni do you think it is ok to just fix the documentation?

**Comment by carlocamilloni** [comment]
I think it is the easiest option, we could also add a message in the preparation scripts 



Sent from my iPhone

**Comment by GiovanniBussi** [comment]
NOTE: this was closed as documentation only
