### ISSUE TITLE
PLUMED with python support contains link to the $srcdir on Arch Linux

### ISSUE THREAD

**Issue by dvdesolve** [plumed/plumed2#413]
When trying to build PLUMED with python support on Arch Linux (packages to install are `python`, `cython` and `python-numpy`) with `makepkg` I have the warning about the link to the `$srcdir` in final package. The file of concern is `$DESTDIR/lib/plumed/python/plumed.cpp`

**Comment by GiovanniBussi** [comment]
@dvdesolve Should be fixed now.

Notice that at some point we might merge #411. Then, it would be possible to install the wrappers separately from PLUMED (as separate packages). That's what I plan to do for MacPorts.
