### ISSUE TITLE
doc for lammps patch needs update

### ISSUE THREAD

**Issue by invemichele** [plumed/plumed2#414]
Plumed manual should be updated with the new instructions for patching lammps.

If someone uses the [present instructions](https://plumed.github.io/doc-master/user-doc/html/lammps-6_apr13.html), they will lead him to an _apparently_ working plumed-lammps setup, that actually does not pass the virial properly, so provides wrong simulations ( #377 ).

If it helps, @PabloPiaggi and I could work on this and write the new instructions.
Regards,

Michele

**Comment by GiovanniBussi** [comment]
As far as I understood patch is not needed anymore. Shouldn't we just remove it?

Instructions are now in the LAMMPS manual

Giovanni

**Comment by invemichele** [comment]
Yes, I was thinking about something like putting a link to the instructions on lammps website https://lammps.sandia.gov/doc/Build_extras.html#user-plumed
and maybe a short typical usage example, for a quick start.

The only issue about completely removing the lammps-6Apr13 patch is that then plumed will be only compatible with the latest stable release of lammps (which should come out in the next days), and not with any of the old versions.
Not sure if this is a problem or a good thing, since the alternative is to add a new intermediate patch that works on last year lammps version but not on new ones...
