### ISSUE TITLE
Removing actions/options with `-` in their name

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#450]
In version 2.6 we can remove the backward compatible aliases (see #449)

**Comment by GiovanniBussi** [comment]
Technically those are values (strings) and not options or actions. It is thus more difficult to find them, since they are not "reserved".

Actually the reason why I found the issue is that I was trying some time ago to put together an input builder to construct the input file from a python jupyter notebook. Something like

```` python
ib=plumed.InputBuilder()
ib.DISTANCE(ATOMS=(10,20))
````

Using the manual, this can work with autocompletion (`ib.DIST<TAB>`). I plan to make it public in the next weeks if I have time to polish it.

I cannot do this
```` python
ib.MULTI-RMSD()
# should be ib.MULTI_RMSD() instead
````
but I can do this
```` python
ib.RMSD(TYPE="OPTIMAL-FAST")
````
since it is a string.

Also if you think at how the parser works, we read `TYPE` as a string. We cannot forbid `-` in strings, or people won't be able to use it e.g. in file names. Maybe we should have options that are like "C enums", with a prescribed list of values declared in the manual, and we could forbid registering enum values with `-`. However it requires to modify the Keywords class and I think might be complicated.

What do you think?

**Comment by carlocamilloni** [comment]
I see, no I was actually thinking it was a flag but it isn't.
Cool!
