### ISSUE TITLE
Problems with large grids allocation

### ISSUE THREAD

**Issue by dvdesolve** [plumed/plumed2#463]
We're trying to do 3-dimensional MetaD with grid because our simulation so long that as a result we're getting about several millions of Gaussian kernels and so performance becomes poor.

NAMD (IBVerbs version) is used as engine for MD and all simulations are held at Lomonosov-2 cluster. One node of cluster gives us 64 Gb of RAM.

When grid size is too large NAMD crashes. I've calibrated memory usage based on grid size. So I get the following for our test system:
```
GRID size | Memory consumption (Mb)
===================================
0         | 542
1000      | 556
125000    | 561
1000000   | 636
27000000  | 3039
125000000 | 12053
```
Seems like every grid point occupies about 92 bytes of memory. Seems a bit strange because according to the `src/tools/Grid.h` grid is defined as STL `std::vector<double> grid_` and in `src/tools/Grid.cpp` grid becomes resized to the product of all number of grid bins. So even with STL's overhead it shouldn't occupy so much space. But it is not the main problem.

Using my calibration I calculated appropriate grid size for using about 60 Gb of RAM. However PLUMED complains about unsuccessful memory allocation and crashes with stack trace. I was able to run my MetaD only with grid size which occupies about 30 Gb of RAM. The possible cause is that STL `vector` container (re)allocates memory from heap and expect contiguous allocated block. In production systems RAM can be fragmented and contiguous allocation of such huge memory block can fail.

So the possible ways to mitigate problem is to use `bad_alloc` exception thrown by `std::vector` allocator and take actions depending on situation. Another way is to use different storage for `grid_` or try to rework allocator for this specific grid storage.

What do you think about it?

**Comment by GiovanniBussi** [comment]
@dvdesolve thanks for reporting this. In principle the memory footprint should be (number of points) x (number of dimensions + 1 ) x sizeof(double), since we store all derivatives along with value. However, I noticed right now that we actually declare the derivatives as
````
  std::vector<double> grid_;
  std::vector< std::vector<double> > der_;
````
which will add a large and unnecessary STL overhead. I think it is not difficult to refactor the code so that we declare `std::vector<double> der_`  with size `maxsize_*dimension_`, it will just need to change all the `[i][j]` access to something like `[i*dimension_+j]`.

Given this, a few comments on your specific issue:
- How did you choose the spacing in the grid? Usually the default is good enough, but you can make it slightly more dense if you want.
- Did you try `SPARSE` option? It is slower but uses much less memory
- I am afraid `bad_alloc` might be not reliable since there would be make cases where the allocation succeeds but memory is swapped with terrible slowdowns. What do you think?

Thanks again!

Giovanni

**Comment by dvdesolve** [comment]
In our work we're forcing the ligand to explore all possible places inside protein cavities. In current test system MetaD is performed along `x`, `y` and `z` axes and grid range is about 17-21 angstroms. Current `sigma`s values are chosen in such way that all available range covered with about 200 `sigma`s. Then the number of bins per each direction are selected to give 3--5 multiple of total `sigma`s count in each direction, so the final grid is about 750x750x750. In case of bigger systems we're just increasing `sigma`s.

No, we haven't tried to test our system with `SPARSE` keyword. May be it can help, need to test. Thank you for a suggestion.

It can be reliable if code can detect when swapping occurs. It can seems a bit complicated, but in principle during preparation of the grid we can perform small timing calibration - for example, allocate some test grids with increasing size and get average specific time of alloc operation. Then during the final allocation of full-sized grid we should measure time elapsed and compare (with some tolerance) with previous value. If some anomalies are observed then we can just alert user about possible swapping bottleneck and let him to choose what to do. In that case `bad_alloc` should save us in situation when no free RAM + swap is left and we can finalize PLUMED softly. This is just in theory, I haven't tested such approach.

**Comment by GiovanniBussi** [comment]
@dvdesolve you might want to try branch fix-465, where I refactored the allocation of derivatives to save memory. It should save a significant amount of memory (I guess it should take 32 bytes per point for a 3D grid).

**Comment by dvdesolve** [comment]
Just checked **fix-465** branch. Here are measurements of memory usage:
```
GRID size | Memory consumption (Mb)
===================================
0         | 508
1000      | 515
125000    | 522
1000000   | 548
27000000  | 1347
125000000 | 4347
```

Now it seems like every grid point uses 32 bytes. Thank you a lot! I think it can be closed now
