### ISSUE TITLE
configure script compiler detection isn't obvious

### ISSUE THREAD

**Issue by dvdesolve** [plumed/plumed2#466]
Even when trying to compile MPI version with Intel compilers I see the following line during `./configure` step:
```
checking whether we are using the GNU C++ compiler... yes
```
Seems like `configure` just checks if test file could be compiled. However it gives no information about true nature of compiler used so on sophisticated environments such as clusters it can be ambiguous which compiler was actually used. The only way to detect if non-GNU compiler was used is to see the following line:
```
checking whether we are using the GNU Fortran compiler... no
```
However, it isn't true for C and C++ compilers.

**Comment by GiovanniBussi** [comment]
Hi, I think that autoconf just check if macro `__GNUC__`, and apparently this macro is also defined by the intel compiler. I don't think this is something that we can solve.

I think you can use the `__INTEL_COMPILER` macro inside the code if, for some reason, you want to know if you are using the intel compiler or not.
