### ISSUE TITLE
Problems with Grid/SparseGrid hierarchy

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#467]
I think there is a problem in the Grid/SparseGrid hierarchy. Now we have
````
Grid -> SparseGrid
````
which means that every SparseGrid is also a Grid. However, Grid contains member `grid_`, whereas SparseGrid contains member `map_` and does not use member `grid_`. This can lead to problems. Indeed, we added a lot of methods to `Grid` that use `grid_` and that thus, when used from a `SparseGrid`, lead to unpredictable behavior. I want to change the structure as follows:
````
GridBase -> Grid
         -> SparseGrid
````
where GridBase only declares virtual methods that are available both in Grid and SparseGrid. In this way, in MetaD we can safely use pointers to `GridBase` using the available methods and allowing for sparse grids. Other methods not interested in SparseGrid might directly use Grid, which will be always dense.

I noticed a single bug induced by this, namely in `METAD` with `TARGET` and `GRID_SPARSE` (due to the fact that `getMaxValue` is not overridden in `SparseGrid`). I will make an ad hoc fix for v2.5, but I think that on master we should change the hierarchy as I proposed above.

@invemichele @valsson I will need to make tiny adjustments to ves, which is the only module using grid. I will open a pull request so that you will be able to cross check them.

**Comment by carlocamilloni** [comment]
This sounds dangerous, maybe we should remove sparse grids if they are not used. 
Anyway your solution sounds good

Carlo

Sent from my iPhone

**Comment by GiovanniBussi** [comment]
I think they are useful with MetaD in multiple dimensions, so I'll try to fix it (I have a draft already)
