### ISSUE TITLE
release 2.5.1 doesn't include the patch for gromacs 2019.2

### ISSUE THREAD

**Issue by xiki-tempula** [plumed/plumed2#472]
The 2.5.1 shown in the plumed website http://www.plumed.org/get-it
as well as the Release 2.5.1 in the release page.
doesn't include the patch code for gromacs 2019.2.

**Comment by dvdesolve** [comment]
Seems like patch for gromacs 2019.2 was added only 15 days ago and 2.5.1 version was uploaded at 1 of April. Just wait for 2.5.2
