### ISSUE TITLE
negative random seeds in pesmd / setSeed requiring a negative value

### ISSUE THREAD

**Issue by hockyg** [plumed/plumed2#493]
A person in my group noticed that pesmd was giving the same result no matter what the random seed (idum) was specified in the input file. I dug into the code, and realized that the random number being used from numerical recipes requires a negative seed/idum. 

The core developers clearly know this, because in most places in plumed, the code is written setSeed(-seed). However, this is not the case in pesmd, where it is setSeed(seed), and seed=idum.
https://github.com/plumed/plumed2/blob/c2fb5676421c7ea2ba80b63c907878b2b1a9ce2f/src/cltools/pesmd.cpp#L177

This is a bit confusing, and we should probably figure out what to do about that, or at least update the docs accordingly. 
https://www.plumed.org/doc-v2.5/user-doc/html/pesmd.html

Additionally, this negative seed issue has to be made clear for future developers, as it seems to be used incorrectly in both the VES module (only in 1 out of several spots) and the EDS module. For reference, doing setSeed(seed>0) is the same as setSeed(-1). 

@valsson @whitead 

Because setSeed is only hit at the beginning of a simulation, maybe we can print a warning inside setSeed if the argument is positive?

**Comment by GiovanniBussi** [comment]
@hockyg would changing the sign directly in `Random::setSeed` be a solution to this issue? Something like

````
void Random::setSeed(int idum_) {
  if(idum_>0) idum_=-idum_; // <- new line
  idum=idum_;
  incPrec=false;
}
````

**Comment by hockyg** [comment]
Yes, I think that would be a good fix. I don’t see any reason to allow the
other case.

**Comment by valsson** [comment]
@GiovanniBussi I agree that this solution should be good. 

Actually I have to admit that I have observed this issue a couple of times in the simplemd code. Thus, I knew about it and in all places in the VES code this should be correct, there is always a check to make sure that the seed given to setSeed is negative (I double check just now), thus if the user gives a N>0 as a seed, the seed given to setSeed is -N. However, it should be much safer to do this check inside setSeed like you propose. 

Omar

**Comment by hockyg** [comment]
p.s. Omar, glad there's not bug in VES. I just noticed one of the lines
says setSeed(seed) and some other places it says setSeed(-seed). I guess
you fixed the problem higher up in the code!
