### ISSUE TITLE
Force components description

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#501]
comment

**Comment by carlocamilloni** [comment]
ERROR in test analysis/rt-calc-dissims2/
+ check file analysis/rt-calc-dissims2/report.txt for more information
+ ERROR in test analysis/rt-calc-dissims/
+ check file analysis/rt-calc-dissims/report.txt for more information
+ ERROR in test analysis/rt-reselect-land/
+ check file analysis/rt-reselect-land/report.txt for more information
+ ERROR in test analysis/rt-reweight-temp-press/
+ check file analysis/rt-reweight-temp-press/report.txt for more information
+ ERROR in test analysis/rt-store-print/
+ check file analysis/rt-store-print/report.txt for more information
+ ERROR in test analysis/rt-wham/
+ check file analysis/rt-wham/report.txt for more information
+ ERROR in test basic/rt26/
+ check file basic/rt26/report.txt for more information
+ ERROR in test basic/rt40/
+ check file basic/rt40/report.txt for more information
+ ERROR in test basic/rt40-mpi/
+ check file basic/rt40-mpi/report.txt for more information
+ ERROR in test basic/rt41/
+ check file basic/rt41/report.txt for more information
+ ERROR in test basic/rt44b/
+ check file basic/rt44b/report.txt for more information
+ ERROR in test basic/rt65-mpi/
+ check file basic/rt65-mpi/report.txt for more information
+ ERROR in test basic/rt74/
+ check file basic/rt74/report.txt for more information
+ ERROR in test basic/rt-close-structure/
+ check file basic/rt-close-structure/report.txt for more information
+ ERROR in test basic/rt-fix-229/
+ check file basic/rt-fix-229/report.txt for more information
+ ERROR in test basic/rt-maxent-3/
+ check file basic/rt-maxent-3/report.txt for more information
+ ERROR in test dimred/rt-mds2/
+ check file dimred/rt-mds2/report.txt for more information
+ ERROR in test dimred/rt-mds/
+ check file dimred/rt-mds/report.txt for more information
+ ERROR in test dimred/rt-pca-2/
+ check file dimred/rt-pca-2/report.txt for more information
+ ERROR in test dimred/rt-pca-osample/
+ check file dimred/rt-pca-osample/report.txt for more information
+ ERROR in test dimred/rt-smap1/
+ check file dimred/rt-smap1/report.txt for more information
+ ERROR in test dimred/rt-smap-osample/
+ check file dimred/rt-smap-osample/report.txt for more information
+ ERROR in test dimred/rt-smap-pointwise/
+ check file dimred/rt-smap-pointwise/report.txt for more information
+ ERROR in test dimred/rt-smap-read/
+ check file dimred/rt-smap-read/report.txt for more information
+ ERROR in test dimred/rt-smap-smacof/
+ check file dimred/rt-smap-smacof/report.txt for more information
+ ERROR in test dimred/rt-store-histo/
+ check file dimred/rt-store-histo/report.txt for more information
+ ERROR in test isdb/rt-bayesgje-2/
+ check file isdb/rt-bayesgje-2/report.txt for more information
+ ERROR in test isdb/rt-bayesgje/
+ check file isdb/rt-bayesgje/report.txt for more information
+ ERROR in test isdb/rt-bayesspe/
+ check file isdb/rt-bayesspe/report.txt for more information
+ ERROR in test isdb/rt-caliber/
+ check file isdb/rt-caliber/report.txt for more information
+ ERROR in test isdb/rt-cs2backbone/
+ check file isdb/rt-cs2backbone/report.txt for more information
+ ERROR in test isdb/rt-cs2backbone-mi/
+ check file isdb/rt-cs2backbone-mi/report.txt for more information
+ ERROR in test isdb/rt-cs2backbone-mpi/
+ check file isdb/rt-cs2backbone-mpi/report.txt for more information
+ ERROR in test isdb/rt-jcouplings/
+ check file isdb/rt-jcouplings/report.txt for more information
+ ERROR in test isdb/rt-jcouplings-mi/
+ check file isdb/rt-jcouplings-mi/report.txt for more information
+ ERROR in test isdb/rt-noe/
+ check file isdb/rt-noe/report.txt for more information
+ ERROR in test isdb/rt-noe-mi/
+ check file isdb/rt-noe-mi/report.txt for more information
+ ERROR in test isdb/rt-noe-mpi/
+ check file isdb/rt-noe-mpi/report.txt for more information
+ ERROR in test isdb/rt-pre/
+ check file isdb/rt-pre/report.txt for more information
+ ERROR in test isdb/rt-pre-mi/
+ check file isdb/rt-pre-mi/report.txt for more information
+ ERROR in test isdb/rt-rdc-gsl/
+ check file isdb/rt-rdc-gsl/report.txt for more information
+ ERROR in test isdb/rt-rdc/
+ check file isdb/rt-rdc/report.txt for more information
+ ERROR in test isdb/rt-rdc-mi/
+ check file isdb/rt-rdc-mi/report.txt for more information
+ ERROR in test isdb/rt-rdc-mpi/
+ check file isdb/rt-rdc-mpi/report.txt for more information
+ ERROR in test isdb/rt-saxs-2/
+ check file isdb/rt-saxs-2/report.txt for more information
+ ERROR in test isdb/rt-saxs/
+ check file isdb/rt-saxs/report.txt for more information
+ ERROR in test isdb/rt-saxs-mi/
+ check file isdb/rt-saxs-mi/report.txt for more information
+ ERROR in test mapping/rt40/
+ check file mapping/rt40/report.txt for more information
+ ERROR in test mapping/rt40-mpi/
+ check file mapping/rt40-mpi/report.txt for more information
+ ERROR in test mapping/rt-adapt/
+ check file mapping/rt-adapt/report.txt for more information
+ ERROR in test multicolvar/rt19/
+ check file multicolvar/rt19/report.txt for more information
+ ERROR in test ves/rt-td-multicanonical-withcv/
+ check file ves/rt-td-multicanonical-withcv/report.txt for more information
+ ERROR in test ves/rt-td-multithermal-multibaric-withcv/
+ check file ves/rt-td-multithermal-multibaric-withcv/report.txt for more information
+++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Final report:
+ 483 tests performed, 0 tests not applicable
+ 53 errors found
+ Find the bug!
+ To replace references, go to the test directory and
+ type 'make reset'

**Comment by carlocamilloni** [comment]
These are all the tests that fail due to missing descriptions of components

**Comment by valsson** [comment]
Hello @carlocamilloni,

I was looking at the reason for the failure of ves/rt-td-multicanonical-withcv/ and ves/rt-td-multithermal-multibaric-withcv/ and it seems that it is because these regtests use the READ action to read in a CV which is named with a component: 

op: READ FILE=COLVAR-READ VALUES=op.morethan IGNORE_FORCES

Thus, the problem is with the READ action that tries to add a component that is not documented. Perhaps this an issue with some other regtests. 

Regards,
Omar

**Comment by carlocamilloni** [comment]
Hi @valsson thanks for checking them. yes there are a subset of action that are responsible for most of the failures.

**Comment by carlocamilloni** [comment]
@GiovanniBussi @gtribello @maxbonomi I don't remember this but from the code I see that for enumerated components we use "-" and not "_" but for some reason "_" is used (by me) in most of the places. Are we happy to keep using "-"? I will update the ISDB action accordingly.
Furthermore, some actions just define components with argument names, this is currently not accepted by our registration procedure. So either we relax the criteria for components registration or we modify these codes adding something

example SORT registers the components as .1, .2 etc. This cannot be described for we either modify it into something like .s-1, .s-2 so that we can describe a generic component s or we change the rules for registering compoments

**Comment by gtribello** [comment]
@carlocamilloni you can call 

ActionWithValue::useCustomisableComponents( keys )

In the registerKeywords action if needs be and use whatever you want as components.  I think this was designed to allow people to do whatever.

**Comment by carlocamilloni** [comment]
nope…

It does not seems to be so :-(

**Comment by carlocamilloni** [comment]
@gtribello to follow up not this addComponents(key, bool) can in principle avoid the issue by setting the bool to false, but we use true everywhere. One could add a bool customComponents to ActionWithValue but ActionWithValue::useCustomisableComponents( keys ) is a static function so it cannot modify a non-static variable

**Comment by gtribello** [comment]
@carlocamilloni now I remember how this was supposed to work.  If in registerKeywords you add the 

ActionWithValue::useCustomisableComponents( keys ) 

then you can add Output Components with any name you so choose and the code will not complain by doing 

addComponent("name", false); 

If, however, you try to do:

addComponent("name",false)

and you don't have the call to ActionWithValue::useCustomisableComponents( keys ) in the registerKeywords methods it will complain.

**Comment by carlocamilloni** [comment]
@gtribello sorry I made a mistake above:
addComponents take only a string in input and then it calls
keywords.outputComponentExists(name,true)
there we may set false and it would work but there is no way to send a bool
We should modify addComponets to allow to take a bool but with a default value of true so to not have to change all the code

**Comment by gtribello** [comment]
@carlocamilloni if you look at the relevant code you see the following.  The call in addComponent is:

if( !keywords.outputComponentExists(name,true) ) {
    warning("a description of component " + name + " has not been added to the manual. Components should be registered like keywords in "
            "registerKeywords as described in the developer docs.");
  }

If you then look in outputComponentExists in registerKeywords you find the following:

if( custom && cstring.find("customizable")!=std::string::npos ) return true;

So there will be no problem if you find the word customizable in the variable cstring, which is set by:

Keywords::setComponentsIntroduction()

which is called as follows in ActionWithValue::useCustomisableComponents()

void ActionWithValue::useCustomisableComponents(Keywords& keys) {
  keys.setComponentsIntroduction("The names of the components in this action can be **customized** by the user in the "
                                 "actions input file.  However, in addition to the components that can be **customized** the "
                                 "following quantities will always be output");
}

So if you change the customisable in the outputComponentsExists to customized then it will work.

Damn my extensive vocabulary causing bugs in the code!!

**Comment by carlocamilloni** [comment]
@gtribello :-)
I am fixing it now... but it looks kind of a crazy way to do it!

**Comment by gtribello** [comment]
The logic was to make sure that people contributing have something to explain in the manual what is being calculated.  If you just have:

addComponent( "name", checkname );

and have checkname as a bool my worry was that people will just set checkname false in order to get rid of the warning and they wouldn't write anything.  This way writing the documentation is easier than cheating!

**Comment by carlocamilloni** [comment]
@gtribello at this point there is one single regtest still failing that is multicolvar/rt19 one solution is to add useCustomisableComponents to ValueVessel.cpp but maybe there is a solution that is more direct than the workaround, please let me know so that I can then merge this branch

**Comment by gtribello** [comment]
@carlocamilloni you should be able to get everything to work if you change this from earlier:

if( custom && cstring.find("customizable")!=std::string::npos ) return true;

to 

if( custom && cstring.find("**customize**")!=std::string::npos ) return true;  

This will find the customized in the cstring with useCustomComponents and the customize in the cstring for MultiColvarBase.

Sorry for the confusion
