### ISSUE TITLE
-multi absent in Gromacs 2019

### ISSUE THREAD

**Issue by spiwokv** [plumed/plumed2#516]
Dear all,
Maybe I'm panicking but as far as I was able to trace the option -multi was removed from Gromacs 2019. This would disable PT-MTD, BE-MTD etc. Is there any workaround?
All the best
Vojtech

**Comment by maxbonomi** [comment]
From the release notes:

Removed gmx mdrun -multi
The implementation of gmx mdrun -multidir is more reliable and works with more features. Nobody was willing to maintain the duplicate functionality.

**Comment by spiwokv** [comment]
Thanks!
