### ISSUE TITLE
DISTANCES multicolvar modifies atom positions

### ISSUE THREAD

**Issue by mnmelo** [plumed/plumed2#527]
Hi PLUMED devs!

When using a DISTANCES multicolvar the atom positions accessible via that mcolvar become distorted. This breaks subsequent uses of other multicolvars such as INCYLINDER. I'm running a build from the latest commit (b7009ae) but had the same problem in the 2.5.3 release.

A MWE:
```
blc0: GROUP ATOMS=3277  # this atom sits at (11.220,3.160,6.340)
ca: GROUP NDX_FILE=index.ndx NDX_GROUP=CA  # 12 atoms
dca: DISTANCES GROUPA=ca GROUPB=blc0 
DUMPMULTICOLVAR STRIDE=1 FILE=dump_mcolv.xyz DATA=dca
DUMPATOMS STRIDE=1 FILE=dump_atoms.xyz ATOMS=ca
```
Running `plumed driver` on a two-frame .xtc file produces the output below (only dumps of the first frame are shown). Atom positions reported by DUMPMULTICOLVAR don't match the correct ones reported by DUMPATOMS:
```
#dump_mcolv.xyz
12
 15.417680 10.278460 16.632021
X 10.764999 3.795000 6.005000 1.699970
X 11.585000 3.510000 8.545000 4.524489
X 10.530000 3.775000 6.260000 1.855505
X 11.125000 4.015000 5.955000 1.884967
X 10.740000 4.155000 6.065000 2.276884
X 11.804999 4.485000 5.895000 3.030429
X 10.454999 4.495000 5.950000 3.174618
X 9.279999 2.985000 8.560000 5.906818
X 9.309999 6.275000 6.175000 7.315339
X 11.510000 4.270000 5.910000 2.450388
X 12.045000 3.570000 8.565000 4.816368
X 9.325000 3.475000 8.390000 5.618807
```
```
#dump_atoms.xyz - these match the input file
12
 15.417680 10.278460 16.632021
X 10.309999 4.430000 5.670000
X 11.950000 3.860000 10.750000
X 9.840000 4.390000 6.180000
X 11.030000 4.870000 5.570000
X 10.260000 5.150000 5.790000
X 12.389999 5.810000 5.450000
X 9.690000 5.830000 5.560000
X 7.340000 2.810000 10.780000
X 7.400000 9.389999 6.010000
X 11.800000 5.380000 5.480000
X 12.870000 3.980000 10.790000
X 7.430000 3.790000 10.440000
```

Running with or without `NOPBC` produces the same sort of erroneous results. The related XYDISTANCES or XDISTANCES also have the same problem. Interestingly, the calculated distance (4th column in dump_mcolv.xyz) is correct.

Am I missing something obvious? Any input is appreciated!

**Comment by gtribello** [comment]
This is not a bug it is a feature.  Whether it makes any sense or not is open to debate.

So the positions output by DUMPMULTICOLVAR are the geometric centres of the distances.  So if i run the command:

d1: DISTANCES GROUPA=1 GROUPB=2,3,4
DUMPMULTICOLVAR DATA=d1 etc

The output file from DUMPMULTICOLVAR contains:

0.5*( x_1 + x_2 ) D(x_1,x_2)
0.5*( x_1 + x_3 ) D(x_1,x_3)
0.5*( x_1 + x_4 ) D(x_1,x_4) 

where x_1, x_2, x_3 and x_4 are the coordinates of each of the atoms and where D is a function that calculates the distance between the two atoms.

The reason it is implemented this way is connected to the fact that I can do commands like this:

d1: DISTANCES GROUPA=1,2 GROUPB=3,4,5

This will output 6 distances.  I thus cannot do a one-to-one assignment of these six distances to the five atomic positions that have been input into the command.

Underneath all this there is a question as to what we mean by "the position" of a distance.  For a coordination number it is clear how to assign "the position".  "The position" of any coordination number value you compute is equal to the position of the central atom.  What do we mean by the position of a distance though.  The location to where we assign a particular distance is arbitrary.  When I wrote the original code I chose to place the distance at the centre of the bond.

If you would like to do something different then I have a new branch of PLUMED where I have allowed the user more control over where to assign these positions.  If you get in touch with me I can point you to that and help you get things set up.

I hope this helps
Gareth

**Comment by mnmelo** [comment]
Thanks for the input, @gtribello. I guess it makes some sense, although for my application I'd rather it was the full list of either GROUPA or GROUPB atom position.

Also thanks for offering your new code! Before bugging you with that maybe you could recommend an alternative to my approach that doesn't need code modifications? (also serves as reference for whoever looks for this)

What I need to do is clear counterions off a circular patch of membrane surface directly underneath my protein. I don't just want to use a cylinder centered on the protein, as that will clear counterions in the solvent bulk when the protein is away from the membrane.
Ideally I'd define a cylinder with center x,y coords same as the protein COM, and z coord same as the headgroups' COM. By choosing a proper radius and height I'd only affect the counterions in the vicinity of the headgroups. Unfortunately, I found no way to construct a virtual atom to serve as the cylinder center (a virtual atom with x, y from one atom and z from another). Is there one?

My second idea -- that brought me here -- was to use INCYLINDER together with ZDISTANCES:
I measure the ZDISTANCES of the counterions to the headgroups' COM and on that multicolvar I apply the INCYLINDER relative to the protein x,y position within a set radius. I then count the number of elements with value (read, z-distance to the headgroups' COM) between -0.5 and +0.5 nm. I could then force that number to zero. It seemed it'd work, but here we are...
Any thoughts?

**Comment by gtribello** [comment]
Hello

I think you can do this like this:

# Calculate the z-component of the distance between the counter ions and the COM of the headgroup.
z1: ZDISTANCES GROUPA=headgroup GROUPB=couterions
# Now select those counter ions that are within a certain distance of the membrane
z1t: MCOLVAR_TRANSFORM DATA=z1 SWITCH={RATIONAL R_0=0.1}
# Calculate the xy-distance between the protein and the counter ions
xyd: XYDISTANCES GROUPA=protein GROUPB=counterions
# Now transform this with a switching function to get the ions in the cylinder
xyds: MCOLVAR_TRANSFORM DATA=xyds SWITCH={RATIONAL R_0=0.1}
# And take the product of the two transformed distance
pp: MCOLVAR_PRODUCT DATA=zt1,xyds SUM

The quantity you have here is pp.sum, which should be a measure of the number of counter ions in the region of interest.

I hope this helps
Gareth

**Comment by mnmelo** [comment]
Thanks, @gtribello! I think that will work, indeed. Will post back with results.
