### ISSUE TITLE
backup files are empty when running over multiple MPI processes

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#530]
This bug is present since a long time

**Comment by GiovanniBussi** [comment]
I've never observed it... is it reproducible?

**Comment by carlocamilloni** [comment]
Yes also locally on my laptop running alanine dipeptide using one or two processors

**Comment by GiovanniBussi** [comment]
Is this with multiple replicas or with one replica and multiple processes
per replica?

Can it be reproduced with driver?

**Comment by carlocamilloni** [comment]
One replica with multiple processes, I will check with driver asap

**Comment by GiovanniBussi** [comment]
If so it would be ideal to have a regtest! I thought there was one but
probably there isn't

**Comment by carlocamilloni** [comment]
I pushed the test that will fail

**Comment by carlocamilloni** [comment]
fixed by 2e6bf6c4b5343940827db4d699b60b45713d93dd
