### ISSUE TITLE
partial-tempering non GNU awk (mawk 1.3.3)  probem 

### ISSUE THREAD

**Issue by hmacdope** [plumed/plumed2#536]
Plumed partial-tempering doesn't work, (error line 173) with mawk 1.3.3 which ships default with Ubuntu Disco Dingo (19.04+). No error when using GNU awk (gawk).

**Comment by GiovanniBussi** [comment]
This is a known issue. I added this to the doc of 2.4 and 2.5 and, in the coming 2.6, I forced the usage of `gawk`.
