### ISSUE TITLE
Missing vim folder in plumed executable folder

### ISSUE THREAD

**Issue by carajillu** [plumed/plumed2#538]
Hi all,

This seems like a very minor bug. When I try to do a fresh installation of plumed, the first time it fails because it doesn't find a folder called vim inside the folder where the program is installed. This is teh last bit of the installation output, where the error appears:

if test -f ../../vim/scripts.vim ; then cp ../../vim/scripts.vim  "/home/joan/local/plumed2_carajillu/lib/plumed/vim/" ; fi
cp: cannot create regular file '/home/joan/local/plumed2_carajillu/lib/plumed/vim/': Not a directory
Makefile:247: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/joan/github/plumed2_carajillu/src/lib'
Makefile:11: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/joan/github/plumed2_carajillu/src'
Makefile:35: recipe for target 'install' failed
make: *** [install] Error 2

Then I manually create /home/joan/local/plumed2_carajillu/lib/plumed/vim/ and run the installation again and it installs it fine. A test with driver runs fine too.

Thanks,
Joan

**Comment by GiovanniBussi** [comment]
@carajillu thanks for reporting! This is a bit strange. If you look at these three lines
 
https://github.com/plumed/plumed2/blob/c090f11cc5ae6e71d6f6320a54f1ad9e0043dc16/src/lib/Makefile#L308-L310

The directory should be created when the help and or syntax directories are copied with tar. Anyway, it is easy to add a mkdir in the previous line, I will make it.
