### ISSUE TITLE
CLOCK_MONOTONIC is not portable

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#539]
@carlocamilloni can you replace CLOCK_MONOTONIC in `src/isdb/Metainference.cpp` with something else? It is not available on older OSX and with some compilers it gives troubles. In particular, I noticed the problem in [conda builds on travis-ci](https://travis-ci.org/plumed/plumed2/jobs/630130846). I think it should be possible to replace it with [high_resolution_clock](https://en.cppreference.com/w/cpp/chrono/high_resolution_clock).

**Comment by carlocamilloni** [comment]
High resolution clock is deprecated but a steadyclock seems to be working well, I am uploading a patch soon

Sent from my iPhone

**Comment by GiovanniBussi** [comment]
(I checked the conda build, it works now)
