### ISSUE TITLE
Double check cppcheck fix

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#540]
@gtribello @valsson can you please double check this commit f83b50f6b851f5168f90bdb2468b82ac66770077?

I noticed a warning raised by a newer version of cppcheck (1.90) related to the fact that if in the constructor you call a virtual function the compiler will not be able to actually call the implementation of the derived class since the derived class has not been constructed yet. Thus, the implementation of the base class will be used instead.

I fixed the warning by explicitly writing that the base class implementation should be called.

This does not change the result (the base class implementation was called before the commit and will be called after the commit) but I wanted to double check with you that this is the intended behavior and not a bug.

Please confirm if it's ok. Thanks!

Giovanni

**Comment by GiovanniBussi** [comment]
Confirmed by @gtribello (see f83b50f)

**Comment by valsson** [comment]
This is fine for me, see f83b50f
