### ISSUE TITLE
API version in PLUMED 2.6 incompatible with LAMMPS interface. 

### ISSUE THREAD

**Issue by valsson** [plumed/plumed2#555]
This is more of an issue with the LAMMPS interface, but I still report it here. 
@PabloPiaggi and @gtribello should be relevant persons to fix this. 

We just noticed that when then the API version was increased to 7 in v2.6 and master in https://github.com/plumed/plumed2/commit/4a6445e03a611ff6be5b7552db8dfa52ad0ba382, the LAMMPS interface doesn't work any more as it has a check for the API version that gives an error if the API version is higher than 6 (lines 79-82 in https://github.com/lammps/lammps/blob/master/src/USER-PLUMED/fix_plumed.cpp). 

It seems to be fixed in just increasing the allowed API version to 7 in the LAMMPS interface. I guess that is the fix for this issue.

**Comment by GiovanniBussi** [comment]
It's actually weird that they enforce a version smaller than something
rather than larger than something... I guess it's a typo in the LAMMPS
interface

**Comment by GiovanniBussi** [comment]
I opened a PR on the LAMMPS repository. I close this one.

Thanks Omar!

**Comment by nisargjoshi10** [comment]
I'm running into this error. Do we have solution for this error?

**Comment by GiovanniBussi** [comment]
I reported this but LAMMPS developers prefer to enforce a maximum PLUMED
version as well.

See here: https://github.com/lammps/lammps/pull/1878

Giovanni

**Comment by PabloPiaggi** [comment]
> I'm running into this error with PLUMED 2.7. Do we have solution any solution for it?

According to the source code of the master branch of LAMMPS (see [this line](https://github.com/lammps/lammps/blob/master/src/USER-PLUMED/fix_plumed.cpp#L81)) only PLUMED versions 2.5, 2.6, 2.7, and 2.8 (does it exist?) are allowed. Perhaps you are using an older version of LAMMPS? In any case, as @valsson suggests you can change [this line](https://github.com/lammps/lammps/blob/master/src/USER-PLUMED/fix_plumed.cpp#L81) by hand and solve your problem.
