### ISSUE TITLE
RMSD problem in Linux conda-forge py-plumed

### ISSUE THREAD

**Issue by dwhswenson** [plumed/plumed2#561]
This might be a PLUMED problem, or an MDTraj problem, or a NumPy problem, or just a lack of me understanding some subtle point of Python (but it's pretty darn subtle). In any case, worth posting here in case other PLUMED users come across the same issue, and in case it's some minor bug in the py-plumed bindings.

Context is that we're (finally!) adding PLUMED CV's to OpenPathSampling core (they've been an external plug-in for a while, now they'll ship with the main code). We have a test that compares PLUMED RMSD to MDTraj RMSD. It uses MDTraj to load a PDB trajectory, and then passes info to PLUMED to calculate the RMSD.

We've been getting incorrect values when using py-plumed on Linux, downloaded from conda-forge. I was completely unable to reproduce the problem on macOS. It was only a problem for the RMSD example (other examples tested distances, angles, etc.) The fix we found boils down to:

```python
positions = frame.xyz[0].astype(np.float64)  # must bind to a name first
plmd.cmd("setPositions", positions)
# plmd.cmd("setPositions", frame.xyz[0].astype(np.float64))  # gives incorrect results!
```

I do not understand why it is necessary to bind to a name first. I would assume this is a bug, but I'm not sure whose bug it is. You can follow the track of us puzzling this out in https://github.com/openpathsampling/openpathsampling/pull/910. The attached zip file includes a simplified example.

CC: @apdealbao

[plumed_rmsd.zip](https://github.com/plumed/plumed2/files/4376876/plumed_rmsd.zip)

**Comment by GiovanniBussi** [comment]
PLUMED stores the pointer passed to `"setPositions"` and then accesses it later when you use `"calc"`. I am not sure what python does with garbage collection and/or reference counting, but you should make sure that the pointer is still valid. My guess is that, if you pass a temporary, the pointer points to something that is deleted immediately after the `"setPositions"` call, but I might be wrong.

**Comment by GiovanniBussi** [comment]
@dwhswenson I guess this is solved so I close it, feel free to reopen it if you think there's a problem.
