### ISSUE TITLE
Exchange ratio in HREX

### ISSUE THREAD

**Issue by AnguseZhang** [plumed/plumed2#574]
Dear plumed team, 
    I used the HREX patch with gromacs-2018.8. However, I have some questions about the exchange ratio. In the paper "Hamiltonian replica exchange in GROMACS: a flexible implementation", it says the exchange ratio can be calculated by. 

<img width="762" alt="截屏2020-06-01上午2 48 37" src="https://user-images.githubusercontent.com/38939321/83360250-7d4e2180-a3b2-11ea-8ec9-1d96beda0286.png">

I tried to use rerun to calculate the ratio manually according to the formula:
`$ ( -U_i(r_j) + U_i(r_i) ) * \beta_i +   ( -U_j(r_i) + U_j(r_j) ) * \beta_j $`
and compare it with the result printed by plumed , which is labeled  as "dplumed". 

**HOWEVER, they are different !** 

![1](https://user-images.githubusercontent.com/38939321/83360436-e2eedd80-a3b3-11ea-8a38-1401d60f715c.png)

I spent a lot of time to debug , but when I simply tried to replace the formula with 

`$ ( -U_j(r_i) + U_i(r_i) ) * \beta_i +   ( -U_i(r_j) + U_j(r_j) ) * \beta_j $`

They become the same! 

![2](https://user-images.githubusercontent.com/38939321/83360573-d7e87d00-a3b4-11ea-890f-d62230c5b4da.png)

I looked for the code, and I found in "gromacs-2018.8.diff/src/programs/mdrun/repl_ex.cpp", the exchange ratio is calculated here.

<img width="1198" alt="截屏2020-06-01上午2 53 09" src="https://user-images.githubusercontent.com/38939321/83360333-09f8df80-a3b3-11ea-9516-469d0510c084.png">

SO I want to ask , what is the expected output of the `adb*re` and `bdb*re`? Are they correct according to the formula presented by the paper? 

Could you please give me some instructions? Thanks a lot ! The codes you have been developing and maintaining are really helpful and powerful, so I really appreciate it. 

@GiovanniBussi

**Comment by GiovanniBussi** [comment]
@AnguseZhang cmd `getDeltaBias i` should return `U_i(r_j)-U_i(r_i)`, that is: "how much the energy of the current replica i will change if I replace its coordinates with those of replica j". So the calculation of `dplumed` that you quoted from the code looks correct.

If you check at how these delta bias are accumulated in the code it also seems correct.  In `void GREX::calculate()`, `localDeltaBias` is computed as I described above for the PLUMED biasing part. Variables `localUSwap` and `localUNow` similarly contain `U_i(r_j)` and `U_i(r_i)`, namely the part coming from GROMACS energy calculation and stored with instructions such as `plumed_cmd(plumedmain,"GREX cacheLocalUSwap",&hrex_enerd->term[F_EPOT]);`.

So, it looks everything is correct. Could you double check your check? Did you analyze your rerun on a replica exchange simulation (it is possible that coordinates are stored *after* the exchange, and so you would have to take that into account, or run in a regime where acceptance is so low that all exchanges are rejected).

Let us know if you manage to solve the problem or if you still think there is an issue in the code.

Thanks!

**Comment by AnguseZhang** [comment]
> @AnguseZhang cmd `getDeltaBias i` should return `U_i(r_j)-U_i(r_i)`, that is: "how much the energy of the current replica i will change if I replace its coordinates with those of replica j". So the calculation of `dplumed` that you quoted from the code looks correct.
> 
> If you check at how these delta bias are accumulated in the code it also seems correct. In `void GREX::calculate()`, `localDeltaBias` is computed as I described above for the PLUMED biasing part. Variables `localUSwap` and `localUNow` similarly contain `U_i(r_j)` and `U_i(r_i)`, namely the part coming from GROMACS energy calculation and stored with instructions such as `plumed_cmd(plumedmain,"GREX cacheLocalUSwap",&hrex_enerd->term[F_EPOT]);`.
> 
> So, it looks everything is correct. Could you double check your check? Did you analyze your rerun on a replica exchange simulation (it is possible that coordinates are stored _after_ the exchange, and so you would have to take that into account, or run in a regime where acceptance is so low that all exchanges are rejected).
> 
> Let us know if you manage to solve the problem or if you still think there is an issue in the code.
> 
> Thanks!

Thanks very much for your reply!  

I find that I have misunderstood: In my case, the temperatures in HREX are all 298K, and the temperatures in the formula should be the same , too.  After using 298K instead of instant temperature, it becomes normal. 

 I've verified the code behavior  by printing  all the variables before calculating  the `dplumed`. So my conclusion is that there is no problem with the code here. 

Thanks again for your time and instructions!
