### ISSUE TITLE
PLUMED metadynamics analysis

### ISSUE THREAD

**Issue by ekwan** [plumed/plumed2#575]
In the metadynamics analysis tutorial, some sample input for the `HILLS` file is given:

```
#! FIELDS time phi sigma_phi height biasf
#! SET multivariate false
#! SET min_phi -pi
#! SET max_phi pi
```

What is the definition of the `biasf` column?  I am trying to convert Desmond output to a format suitable for PLUMED.

Also, how can I adjust the units of this analysis so it takes input and gives output in kcal/mol?

Thanks!

**Comment by GiovanniBussi** [comment]
This is the biasfactor used in [welltempered metadynamics](https://arxiv.org/abs/0803.3861) (called gamma [here](https://arxiv.org/abs/0910.4914)). If you used non-welltempered metadynamics, you should set this to -1.0.

**Comment by PhilipZhu** [comment]
When I ran LAMMPS with PLUMED, I got this HILL file as output, what does the line mean?
```
#! SET multivariate false
```
I wanted to do metadynamics with 3 CVs, would that require multivariate gaussian? If so, how can I set this?
