### ISSUE TITLE
Wrong LJ(SR) and Coulomb(SR) energy calculation in HREX

### ISSUE THREAD

**Issue by TablewareBox** [plumed/plumed2#579]
Dear PLUMED team,
I used the **HREX** patch with gromacs-2018.8. I’ve found that when using PLUMED HREX in gromacs 2018.8 (which supports **-rerun** option for perturbed mass), sometimes **LJ (SR)** and **Coulomb (SR)** are wrongly computed when `do_force()` is called at the second time.

In patched `md.cpp`, the first time, when replica exchange in HREX, reads

```
if (plumedswitch && bHREX) {
      gmx_enerdata_t *hrex_enerd;
      snew(hrex_enerd, 1);
      init_enerdata(top_global->groups.grps[egcENER].nr,ir->fepvals->n_lambda,hrex_enerd);
      ......
      do_force(fplog, cr, ir, step, nrnb, wcycle, top, groups,
               state->box, state->x, &state->hist,
               f, force_vir, mdatoms, hrex_enerd, fcd,
               state->lambda, graph,
               fr, vsite, mu_tot, t, ed, bBornRadii,
               GMX_FORCE_STATECHANGED |
               GMX_FORCE_DYNAMICBOX |
               GMX_FORCE_ALLFORCES |
               GMX_FORCE_VIRIAL |
               GMX_FORCE_ENERGY |
               GMX_FORCE_DHDL |
               GMX_FORCE_NS,
               ddOpenBalanceRegion, ddCloseBalanceRegion);

      fprintf(fplog, "\nLocalUSwap: %10.3e\n", hrex_enerd->term[F_EPOT]);
      plumed_cmd(plumedmain,"GREX cacheLocalUSwap",&hrex_enerd->term[F_EPOT]);
      sfree(hrex_enerd);
```
the second time reads (where the unpatched code computes energies and forces):

```
/* PLUMED */
        plumedNeedsEnergy=0;
        if(plumedswitch){
          int pversion=0;
          plumed_cmd(plumedmain,"getApiVersion",&pversion);
          long int lstep=step; plumed_cmd(plumedmain,"setStepLong",&lstep);
          plumed_cmd(plumedmain,"setPositions",&state->x[0][0]);
          plumed_cmd(plumedmain,"setMasses",&mdatoms->massT[0]);
          plumed_cmd(plumedmain,"setCharges",&mdatoms->chargeA[0]);
          plumed_cmd(plumedmain,"setBox",&state->box[0][0]);
          plumed_cmd(plumedmain,"prepareCalc",NULL);
          plumed_cmd(plumedmain,"setStopFlag",&plumedWantsToStop);
          int checkp=0; if(bCPT) checkp=1;
          if(pversion>3) plumed_cmd(plumedmain,"doCheckPoint",&checkp);
          plumed_cmd(plumedmain,"setForces",&f[0][0]);
          plumed_cmd(plumedmain,"isEnergyNeeded",&plumedNeedsEnergy);
          if(plumedNeedsEnergy) force_flags |= GMX_FORCE_ENERGY | GMX_FORCE_VIRIAL;
          clear_mat(plumed_vir);
          plumed_cmd(plumedmain,"setVirial",&plumed_vir[0][0]);
        }
        /* END PLUMED */
        do_force(fplog, cr, ir, step, nrnb, wcycle, top, groups,
                 state->box, state->x, &state->hist,
                 f, force_vir, mdatoms, enerd, fcd,
                 state->lambda, graph,
                 fr, vsite, mu_tot, t, ed, bBornRadii,
                 (bNS ? GMX_FORCE_NS : 0) | force_flags,
                 ddOpenBalanceRegion, ddCloseBalanceRegion);
        /* PLUMED */
        if(plumedswitch){
          if(plumedNeedsEnergy){
            msmul(force_vir,2.0,plumed_vir);
            plumed_cmd(plumedmain,"setEnergy",&enerd->term[F_EPOT]);
            plumed_cmd(plumedmain,"performCalc",NULL);
            msmul(plumed_vir,0.5,force_vir);
          } else {
            msmul(plumed_vir,0.5,plumed_vir);
            m_add(force_vir,plumed_vir,force_vir);
          }
          if(bDoReplEx) plumed_cmd(plumedmain,"GREX savePositions",NULL);
          if(plumedWantsToStop) ir->nsteps=step_rel+1;
          if(bHREX){
            fprintf(fplog, "\nLocalUNow: %10.3e\n", enerd->term[F_EPOT]);
            plumed_cmd(plumedmain,"GREX cacheLocalUNow",&enerd->term[F_EPOT]);
          }
        }
        /* END PLUMED */
```

Energy calculations are always correct when `do_force()` is called the first time. But when replica exchanging, the **LJ (SR)** and **Coulomb (SR)** parts of energy are calculated wrong for all the energy groups, when `do_force()` is called the second time, for not exchanged topology and coordinates.

However… When I use `-rerun`, the energies are all correct (which calls `do_force()` only once).

Figures and manually-added outputs are attached. I wonder why do these phenomena happen. It seems there is a bug here. Maybe calling `do_force()` twice causes the problem.

![image](https://user-images.githubusercontent.com/28854973/84020280-28fc0080-a9b5-11ea-8292-b4001bb4f0cf.png)

Fig 1,2 at `mdrun`, Fig 3,4 at `rerun`, Fig 5: energies at replica exchange (energy groups are “water” and “non-water”)

Could you please give me some instructions? Thanks a lot! The codes you have been developing and maintaining are really helpful and powerful, so I really appreciate it.

**Comment by GiovanniBussi** [comment]
Thanks for this reporting! This looks like a bug.

If I understand correctly:
- the energies of the exchanged coordinates that are computed before the actual exchange are correct
- the energies of the original coordinates are incorrect, but only at the exchange step.

The consequence would be that there is a single step every replex steps in which energies are not computed correctly, so the actual effect would only be measurable if exchanging very frequently. Thus:
- results with reasonable setups (exchanges every 100 or more steps) would be very mildly affected
- as a consequence, it is difficult to detect the error from incorrect sampling. One should do a careful debugging as you are doing.

Can you confirm that incorrect forces are also used? Is it possible that incorrect energies are written in the edr file (because they are stored somewhere else in the code) but the correct forces are used to propagate the system? This would make the bug totally harmless.

**Comment by TablewareBox** [comment]
> If I understand correctly: the energies of the exchanged coordinates that are computed before the actual exchange are correct; the energies of the original coordinates are incorrect, but only at the exchange step.

Exactly. 

But this matters because with the wrong `LocalUNow`, `adb` and `bdb` are very negative, which makes the probability of exchange always 1.0.

I've equilibrated the systems under scaled topologies in NPT ensemble for 100 ps, and setting `-replex 50` only for quickly debugging. I use `-replex 500` for production MD.

There are some interesting phenomena when I tried many `.mdp` settings:

- The problem doesn't appear when `dt = 0.001` and `rvdw & rcoulomb = 1.2`;
- The problem appears if `dt = 0.002` or `rvdw & rcoulomb = 0.8`, but without replica exchange no problem arises.

I'll check the forces and comment soon. Thanks a lot for your response!

**Comment by GiovanniBussi** [comment]
I see. So, if the artefacts affect the acceptance, then other people would have noticed it. I suspect this is kind of specific of the parameters you are using.

I am happy to help in solving the issue. Let us know if you find out more.

**Comment by TablewareBox** [comment]
Hi, I've found that:

- Forces at the exchange step are slightly different between mdrun results and rerun results

- but completely identical between these outputs when no exchange attempts.

I'll continue to check the code. Thanks for your help!

![image](https://user-images.githubusercontent.com/28854973/84099342-fb0dcf00-aa3b-11ea-90ff-9d47e349b3e5.png)

**Comment by TablewareBox** [comment]
![image](https://user-images.githubusercontent.com/28854973/84099455-3c05e380-aa3c-11ea-9e73-1b6cbcc0cec5.png)

Sorry image uploading is a little bit slow. Here I upload again.

**Comment by TablewareBox** [comment]
I solved the problem by adding another `do_force()` for unexchanged topologies, immediately after exchange back. Everything goes well now :D

Could you please help me check the reason? If this change is reasonable, you can update the code in the next version.

![image](https://user-images.githubusercontent.com/28854973/84142412-531df300-aa87-11ea-908e-dd649334992a.png)

![image](https://user-images.githubusercontent.com/28854973/84142733-e9521900-aa87-11ea-86d4-f884bc76b4b2.png)

![image](https://user-images.githubusercontent.com/28854973/84142814-0edf2280-aa88-11ea-9d11-9f8d13f29e3f.png)

**Comment by TablewareBox** [comment]
Hi, we found how the issue occurs. `LocalUNow` is calculated wrong because the **neighbor list** isn't updated after `LocalUSwap` calculation in HREX. It will result in the **neighbor list** to be that of the exchanged state when calculating `enerd`, then `LocalUNow`.

When we force `nstlist = 1` in `mdp` file, the problem vanished. Then we checked `bNS = (bFirstStep || bNStList || bExchanged || bNeedRepartition);` which determines whether **neighbor list** will be reconstructed in `do_force()`. It appears that:

- `bFirstStep = 1` only when the simulation starts;

- `bNStList = 1` only when step number can be divided by `nstlist`, which is changed to about 80 to achieve higher efficiency on GPU.

![image](https://user-images.githubusercontent.com/28854973/84904185-9a3c6180-b0e1-11ea-9072-19fa30974d5d.png)

- `bExchanged = 1` only when the step _**after**_ replica exchange. But we need a **neighbor list reconstruction** immediately after `LocalUSwap` calculation in HREX, which will **modify the neighbor list**. That's why adding another `do_force()` with **neighbor list reconstruction** for unexchanged topologies, immediately after exchange back works, in the last comment.

![image](https://user-images.githubusercontent.com/28854973/84904256-ad4f3180-b0e1-11ea-84f1-e3accb8bb49a.png)

We suggest that adding `bNS = 1;` after exchange back instead. This achieves the same effect to eliminate the exception.

![image](https://user-images.githubusercontent.com/28854973/84904371-d374d180-b0e1-11ea-9c98-5913e73cc956.png)

Thanks for your attention on the issue :D

**Comment by GiovanniBussi** [comment]
Wow thanks a lot!! This is very useful

**Comment by GiovanniBussi** [comment]
@TablewareBox just to confirm that I understand your fix:
- With the current code, replex should be a multiple of the stride for nstlist (as specified in the documentation). This is tricky, since nstlist is changed by GROMACS when using the GPU, but can still be verified a posteriori. This is what is suggested in the documentation. If one has followed that rule and performed the related checkes, there is no problem expected.
- Your fix would allow to release that constraint, perhaps paying some performance. In particular, neighbor lists will be forcedly updated every replex steps.

If this is confirmed, I would consider this as an enhancement rather than a bug fix (and will not worry about my old simulations ;-)).

Thanks again!

**Comment by TablewareBox** [comment]
> @TablewareBox just to confirm that I understand your fix. ...

Exactly. :D
