### ISSUE TITLE
Metadynamics using SAXS as CVs with openMM

### ISSUE THREAD

**Issue by sue-park** [plumed/plumed2#580]
Hi all,

I am trying to implement metadynamics using SAXS as CVs with openMM. I complied openMM 7.4.4 version, plumed 2.5 version and openMM-plumed plugin 1.0 version. I just wanted to test if Metadynamics can be performed with SAXS in openMM so that I created a 2D test system of 2000 LJ particles with 0.75 volume density. 

I was able to compute SAXS intensities not as CVs and check metadynamics function works in openMM. However, whenever I tried to utilize SAXS as CVs in metadynamics, I get segmentation fault. I am not sure if this is caused from my system, my bad parameter settings, or my openMM/plumed environment. 

I attached my example here. 

My primary goal is just to test SAXS as CVs in openMM. As long as I can make sure that my openmm/plumed environment works well for metadynamics with SAXs, it doesn't have to be this example. If there's anyone who knows the force field of the tutorial example (https://www.plumed.org/doc-v2.5/user-doc/html/isdb-2.html) and if you can provide it, that would be tremendously helpful too. 

Thanks,
Sue

[test.zip](https://github.com/plumed/plumed2/files/4749292/test.zip)

**Comment by carlocamilloni** [comment]
the test zip looks empty
the force field was amber14sb with parmbsc1

**Comment by sue-park** [comment]
Thanks for letting me the force field. I'll try to test the SAXS-metadynamics with this example in openMM. Here's the zip file again which contains actual example I used. 

[test.zip](https://github.com/plumed/plumed2/files/4767520/test.zip)
