### ISSUE TITLE
Bug in AMBER patch: passing PBCs with truncated octahedron 

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#584]
See [this post](https://groups.google.com/d/msgid/plumed-users/f1524b82-99ee-41bc-9ed3-686b17339140o%40googlegroups.com?utm_medium=email&utm_source=footer).

I want to make sure that @dvdesolve is aware of this, since he's the one who did most of the tests (and wrote the pmemd patch).

The proposed solution is to change these lines:

```
+      plumed_box(1,1) = sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(2,1) = sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(3,1) = sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(1,2) = -sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(2,2) = -sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(3,2) = sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(1,3) = sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(2,3) = -sqrt(1.0/3.0)*pbc_box(1)
+      plumed_box(3,3) = -sqrt(1.0/3.0)*pbc_box(1)
```
to:
```
+      plumed_box(1,1) = pbc_box(1)
+      plumed_box(2,1) = 0.0
+      plumed_box(3,1) = 0.0
+      plumed_box(1,2) = -pbc_box(1)/3.0
+      plumed_box(2,2) = sqrt(8.0/9.0)*pbc_box(1)
+      plumed_box(3,2) = 0.0
+      plumed_box(1,3) = -pbc_box(1)/3.0
+      plumed_box(2,3) = -sqrt(2.0/9.0)*pbc_box(1)
+      plumed_box(3,3) = sqrt(2.0/3.0)*pbc_box(1)
```

If this is confirmed as a correct fix, the change should be implemented:
- in PMEMD and SANDER (perhaps @dvdesolve could do it)
- in the plumed patch for PMEMD18 - as a bug fix (I can take care of this)

**Comment by dvdesolve** [comment]
Yep, I've seen messages in plumed-users group. Do we have simplest test case?

**Comment by dvdesolve** [comment]
I'll raise an issue on AMBER's GitLab too

**Comment by GiovanniBussi** [comment]
> Do we have simplest test case?

The user uploaded a setup, but I cannot run it (don't have amber installed). Should be easy to try. Thanks!

**Comment by dvdesolve** [comment]
we've merged proposed fix into main Amber source

**Comment by dvdesolve** [comment]
Updates for Amber20 already released on ambermd.org. So I think you can merge this too

**Comment by GiovanniBussi** [comment]
(Added notes)
[Truncated octahedron Amber.pdf](https://github.com/plumed/plumed2/files/5116759/Truncated.octahedron.Amber.pdf)
