### ISSUE TITLE
plumed does not list latest version of gromacs to patch

### ISSUE THREAD

**Issue by lsmainzer** [plumed/plumed2#585]
Hello!
I seem to have successfully installed PLUMED on my cluster. I used this release: https://github.com/plumed/plumed2/releases/download/v2.6.0/plumed-2.6.0.tgz

Now I am trying to patch my gromacs-2020.2 as described in https://www.plumed.org/doc-v2.6/user-doc/html/_installation.html#Patching

Unfortunately, when I run the "plumed patch -p" command, it does not list the 2020.2 version of gromacs:
PLUMED patching tool
1) amber18          3) gromacs-2019.4   5) namd-2.12        7) qespresso-5.0.2
2) gromacs-2018.8   4) gromacs-4.5.7    6) namd-2.13        8) qespresso-6.2

Could you please help me resolve this conundrum? From the documentation I expected the latest PLUMED to support gromacs-2020.2

Thank you very much.
-Liudmila Mainzer

**Comment by GiovanniBussi** [comment]
The online manual refers to the tip of the 2.6 branch, and already includes material that has not been included in a tagged release yet. You can either:
- download v2.6 from github or
- wait for v2.6.1 (due in a few days)
