### ISSUE TITLE
Useless call to getUnerlyingMultiValue()

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#594]
I noticed this warning on LGTM.

@gtribello can you double check? In principle the call to getUnerlyingMultiValue() can be removed, but I want to make sure this is not a bug.

![image](https://user-images.githubusercontent.com/4378974/86339505-f3fd6980-bc53-11ea-8eb3-e15f8ae70f52.png)

**Comment by gtribello** [comment]
Hello.  The calls to getUnderlyingMultiValue can be safely removed here.  I think it is a remnant of an old way that I had this stuff coded that I didn't delete.  Sorry about that.
