### ISSUE TITLE
How to use HREX to correctly calculate the free energy difference.

### ISSUE THREAD

**Issue by AnguseZhang** [plumed/plumed2#607]
Dear Plumed team, 
    I tried to use HREX to perform FEP-REST2.  If we choose a heat region (using plumed partial_tempering), the topologies between different replicas are different. However, when calculating potential energy difference (needed by BAR or MBAR) , Gromacs seems to only use the local topology to compare replicas with different lambdas. So the results from `dhdl.xvg` are incorrect. As a result, for months I have to use `rerun` to perform a correction and it's time-consuming. 
    I tried to fix the code by myself , but the code is too complicated and the progress is little.  Can you give me some instructions? Many thanks !

**Comment by GiovanniBussi** [comment]
Hi,

as far as I know, the only way to obtain the desired factors is using `mdrun -rerun`. It should not be too expensive though, since you can do it with a skipped trajectory.

Giovanni
