### ISSUE TITLE
MPI_walker of the metaD failed to read and taken into account of the previous HILL files

### ISSUE THREAD

**Issue by xiki-tempula** [plumed/plumed2#624]
I was trying to run well-tempered metadynamics calculations with 8 MPI walkers with Gromacs2019.4/plumed2.6.0. However, it seems that the HILLS are not read correctly when continuing the calculations. The plumed file look like this.

```
protein: CENTER ATOMS=46,113,179,283,381,449,616,678,768,865,937,1045
upper: XYDISTANCES ATOMS1=protein,1099 MEAN
upperc: DISTANCE ATOMS=protein,1099 COMPONENTS

lower: XYDISTANCES ATOMS1=protein,2659 MEAN
lowerc: DISTANCE ATOMS=protein,2659 COMPONENTS

UPPER_WALLS ARG=upper.mean AT=4.0 KAPPA=1000.0 LABEL=uwall
UPPER_WALLS ARG=lower.mean AT=4.0 KAPPA=1000.0 LABEL=lwall

upper_metad: METAD ARG=upperc.x,upperc.y ...
# Deposit a Gaussian every 500 time steps, with initial height equal to 1.2 kJ/mol
  PACE=500 HEIGHT=1 FILE=upper_HILLS
# the bias factor should be wisely chosen
  BIASFACTOR=6
# Gaussian width (sigma) should be chosen based on CV fluctuation in unbiased run
  SIGMA=0.2,0.2
# Gaussians will be written to file and also stored on grid
  GRID_MIN=-4.5,-4.5 GRID_MAX=4.5,4.5 WALKERS_MPI
...

lower_metad: METAD ARG=lowerc.x,lowerc.y ...
# Deposit a Gaussian every 500 time steps, with initial height equal to 1.2 kJ/mol
  PACE=500 HEIGHT=1 FILE=lower_HILLS
# the bias factor should be wisely chosen
  BIASFACTOR=6
# Gaussian width (sigma) should be chosen based on CV fluctuation in unbiased run
  SIGMA=0.2,0.2
# Gaussians will be written to file and also stored on grid
  GRID_MIN=-4.5,-4.5 GRID_MAX=4.5,4.5 WALKERS_MPI
...

PRINT STRIDE=2500 ARG=upperc.x,upperc.y,lowerc.x,lowerc.y FILE=COLVAR
```
Due to the constrain of the infrastructure, I had to run three times to reach the desired length. The code to continue the simulation looks like this.
`mdrun_mpi -deffnm prod -plumed ../plumed.dat -cpi -multidir walker_*`

However, I noticed that though the HILLS are being read when continuing the simulation

```
PLUMED: Action METAD
PLUMED:   with label upper_metad
PLUMED:   with arguments upperc.x upperc.y
PLUMED:   added component to this action:  upper_metad.bias
PLUMED:   Binsize not specified, 1/5 of sigma will be be used
PLUMED:   Gaussian width  0.200000 0.200000  Gaussian height 1.000000
PLUMED:   Gaussian deposition pace 500
PLUMED:   Gaussian file upper_HILLS
PLUMED:   Well-Tempered Bias Factor 6.000000
PLUMED:   Hills relaxation time (tau) 133.031389
PLUMED:   KbT 2.660628
PLUMED:   Grid min -4.5 -4.5
PLUMED:   Grid max 4.5 4.5
PLUMED:   Grid bin 225 225
PLUMED:   Grid uses spline interpolation
PLUMED:   Multiple walkers active using MPI communnication
PLUMED:   added component to this action:  upper_metad.work
PLUMED:   Restarting from upper_HILLS:      3879696 Gaussians read
PLUMED:   Bibliography [3][4][5]
PLUMED: Action METAD
PLUMED:   with label lower_metad
PLUMED:   with arguments lowerc.x lowerc.y
PLUMED:   added component to this action:  lower_metad.bias
PLUMED:   Binsize not specified, 1/5 of sigma will be be used
PLUMED:   Gaussian width  0.200000 0.200000  Gaussian height 1.000000
PLUMED:   Gaussian deposition pace 500
PLUMED:   Gaussian file lower_HILLS
PLUMED:   Well-Tempered Bias Factor 6.000000
PLUMED:   Hills relaxation time (tau) 133.031389
PLUMED:   KbT 2.660628
PLUMED:   Grid min -4.5 -4.5
PLUMED:   Grid max 4.5 4.5
PLUMED:   Grid bin 225 225
PLUMED:   Grid uses spline interpolation
PLUMED:   Multiple walkers active using MPI communnication
PLUMED:   added component to this action:  lower_metad.work
PLUMED:   Restarting from lower_HILLS:      3879696 Gaussians read
PLUMED:   You are using concurrent metadynamics
```
The Hill height peaked every time I restart the simulation, suggesting that the HILLS are not being read correctly. I restarted the calculations two time near the end of the 4 and 8.
![Screenshot 2020-10-19 at 15 28 32](https://user-images.githubusercontent.com/6242032/96464481-c565c780-121f-11eb-997d-6371a1b858ce.png)
Doing the same thing with non-MPI walker will give the right result.

**Comment by carlocamilloni** [comment]
are your hills file written inside the folder of the first walker? if so you need to write them in the main folder (FILE=../HILLS)

**Comment by xiki-tempula** [comment]
@carlocamilloni Thank you for the reply. Yes, you are right in that the HILL files are in the first walker folder. I think it might be good if a warning or error is issued.

**Comment by GiovanniBussi** [comment]
@carlocamilloni related to this issue, perhaps we can check from plumed that the PWD is the same on all processes? It should not be difficult, and could be used to issue a warning.

A further improvement would be to only consider the path set in process 0. All other processes will open a file relative to that path. I think it's easy: if the path starts with `/`, open it, otherwise open `pwd_proc_0/ + path`. What do you think?

**Comment by carlocamilloni** [comment]
You mean the PWD to read the files upon restarting? Yes sounds a good idea

**Comment by carlocamilloni** [comment]
@GiovanniBussi actually I am not sure is it that easy to do it robustly, in c++17 there is the function std::filesystem::path that would allow to handle this but I don't know if this is enough to move to c++17

**Comment by GiovanniBussi** [comment]
I would use `getcwd` as I did here. 
https://github.com/plumed/plumed2/blob/c5c6ba90c9b8398688192c076cbbfa94dec59221/src/tools/Tools.cpp#L419-L424

I think it's portable, we just have to protect it with an ifdef so that compilation will not fail on unusual platforms

**Comment by carlocamilloni** [comment]
done here: commit 1787f76
