### ISSUE TITLE
Problems with rendering of new manual

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#631]
I noticed some problem in the rendering of the manual for 2.7. In particular, these pages seem to be incorrectly interrupted:
https://www.plumed.org/doc-v2.7/user-doc/html/_r_e_w_e_i_g_h_t__w_h_a_m.html
https://www.plumed.org/doc-v2.7/user-doc/html/trieste-5.html
etc
(it seems the pattern is that there are problems with the test requires MPI, but I am not sure).

I am actually not able to reproduce the problem on my laptop, so there might be some subtle problem on the Travis-CI configuration. @gtribello any hints about where I should look at?

**Comment by carlocamilloni** [comment]
It is a problem with flushing, I tried to solve it and it worked in my Linux workstation but it does not on Travis 

Sent from my iPhone

**Comment by GiovanniBussi** [comment]
Urka! Is it possible that when you run with mpirun you have multiple replicas and thus they write multiple times on the example html file? This could be fixed making sure that only the first replica writes (checking Intercomm.Get_rank()).

**Comment by GiovanniBussi** [comment]
Maybe here: https://github.com/plumed/plumed2/blob/257b4a19700a4e82a4131d0f3ec4758c8b129dcc/src/cltools/GenExample.cpp#L118

One could make it such that other replicas open ofile as "/dev/null".

**Comment by carlocamilloni** [comment]
That is a good point

Sent from my iPhone

**Comment by GiovanniBussi** [comment]
@carlocamilloni if your fix works, we have to backport it to branch v2.7

**Comment by carlocamilloni** [comment]
Sure

**Comment by carlocamilloni** [comment]
unfortunately it does not seem to fix the problem

**Comment by GiovanniBussi** [comment]
I think this is still a problem. @gtribello do you know how to fix it? Input files with replicas basically screw up the page in which they are included
