### ISSUE TITLE
[Python Interface][Question] There are any examples of the Python interace in PLUMED

### ISSUE THREAD

**Issue by DanielWicz** [plumed/plumed2#632]
There is nothing about PLUME Python interace in the manuall, except installation. Are there any examples of using PLUMED's Python interaface ?

**Comment by GiovanniBussi** [comment]
I agree we should add it to the manual. Meanwhile I would suggest looking at the tests [here](https://github.com/plumed/plumed2/tree/master/python/test).

**Comment by gtribello** [comment]
I have included examples on how to use the python interface in PLUMED masterclass 6.  See:

https://www.plumed.org/doc-v2.7/user-doc/html/masterclass-21-6.html
