### ISSUE TITLE
Move from Travis-CI to GitHub actions

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#634]
Too bad. My prediction (#480) was [confirmed](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing). We need an alternative ASAP, also to build manual pages and so on.

I already played a bit around with GitHub Actions, and I know how to set them up. I will try later. The negative side is that they provide less different images, so it won't be possible to e.g. test old MacOS versions. And the test I made for PLUMED nest was slower than travis. However, I think we should be able to live with that.

I will try to make the transition in the next few days, but might need some help.

**Comment by GiovanniBussi** [comment]
[Here](https://docs.travis-ci.com/user/migrate/open-source-repository-migration) is is the official deadline:
> A. In an effort to ensure that all of our users - whether you build open-source, public or private repositories - receive regular feature updates, security patches and UX/UI enhancements, we are announcing that travis-ci.org will be officially closed down completely no later than December 31st, 2020, allowing us to focus all our efforts on bringing new features and fixes to travis-ci.com and all of our awesome users like yourself on the travis-ci.com domain.

**Comment by GiovanniBussi** [comment]
Update on this:
- I managed to have a basic set of tests starting with v2.4.
- Manual is building, we should check it it's ok.

Notice that some tests are failing because these ubuntu versions are newer than those on travis.
For v2.4/v2.5 I think it's fine to ignore the result:
https://github.com/plumed/plumed2/blob/21e4265021b8a8997c074e50724e1b69436f57bb/.github/workflows/ci.yml#L90
For v2.6 and up, there is still a test failing (`mapping/rt-adapt`) it should probably be fixed.

Still to do:
- Fix the failing test mentioned above
- Add the special manual stuff for v2.7
- Add some more test (perhaps a Docker contained with CentOS 7 would be good to test an older compiler), even only in v2.7
- Modify scripts that push documentation and coverage so as to work on GitHub actions
- Modify scripts that deploy conda binaries to work on GitHub actions
(the last two points should be done while concurrently switching off pushing from Travis).

**Comment by carlocamilloni** [comment]
Great! 
Thanks Giovanni!

**Comment by GiovanniBussi** [comment]
All done. Missing things:
- Fix the test failing on MacOS 10.15 @gtribello could you check why `mapping/rt-adapt` is failing?
- Add a test with Docker in a CentOS 7 container, to test an old compiler

Other comments:
- Jobs are now always the same ones, irrespectively if triggered by a push or by a pull request. Since the number of jobs that run in parallel is much higher wrt Travis, I think it's ok. If later it gets to slow we can change it.
- A few combinations that were present on Travis are still missing, but probably they are not so important
- "trieste-5" tutorial is still truncated (see #631)
- Coverage is now computed with -O0 (no optimization). This is feasible, since the maximum time is ~ 6h and this lasts for ~ 1h. It should be more precise.

**Comment by carlocamilloni** [comment]
I think that at this point we can remove the travis tests, these GitHub actions at least for now are more efficient, the only pity is the duplication of the tests when creating a pull request from a branch

**Comment by carlocamilloni** [comment]
@GiovanniBussi shall we move the coverage to the nightly build? this is the slowest and once per day could be enough

**Comment by GiovanniBussi** [comment]
I think it's not straightforward but can be done. The difficulty is that only master branch is built with crontab (and it's actually weekly now, but I can easily rename the current workflow `weekly` and add a `nightly` one).

Perhaps the solution is to:
- configure to run the coverage test only if the commit message contains some string (see [here](https://github.community/t/accessing-commit-message-in-pull-request-event/17158/7)), e.g. `[coverage]`.
- configure a bot that every night makes an empty commit on all the maintained branches with the message `[coverage]`.

I will check how easy it is.

**Comment by GiovanniBussi** [comment]
@carlocamilloni a much simpler alternative is to go back to `-O` optimization here (instead of `-O0`):
https://github.com/plumed/plumed2/blob/3701aa771227ead4ba8773e18b82d0f577c7e89c/.github/workflows/ci.yml#L91
This is what we were doing on Travis-CI. It depends on how accurate we need the coverage to be. Probably for the sake of identifying untested options this is more than sufficient.

**Comment by carlocamilloni** [comment]
Maybe we can start by moving back -O1 and then decide later if it may be worth to do something else
