### ISSUE TITLE
[Feature request] Quaternion to describe relative orientation between two molecules

### ISSUE THREAD

**Issue by fhh2626** [plumed/plumed2#645]
Dear plumed developers:

I wonder if it is possible to support quaternion to describe the relative orientation between two molecules, since part of the work has been done in the implementation of RMSD? 

I noticed someone has a fork (https://github.com/zharmad/plumed2/tree/orient-q) and successfully merged it with the master branch of the latest plumed. However, this version seems slow in free-energy calculations.

Thanks,
Haohao

**Comment by zharmad** [comment]
I never got around to submitting a pull request. What I can do more quickly is to check if can fast-forward it to the v2.6 or v2.7, since the fork itself is simple: it consists one one new file (Quaternion.cpp) and one edit (Vector.h).

**Comment by fhh2626** [comment]
> I never got around to submitting a pull request. What I can do more quickly is to check if can fast-forward it to the v2.6 or v2.7, since the fork itself is simple: it consists one one new file (Quaternion.cpp) and one edit (Vector.h).
> 
> More importantly, are you running free energy calculations on the relative orientations? I'm not sure if that gives you an accurate FES. IIRC there is something about the need to project the forces onto the unit 4D-sphere, which the implementation does not do.

Thanks for your very fast reply!
