### ISSUE TITLE
declare OpenMP reduction for std::vector

### ISSUE THREAD

**Issue by invemichele** [plumed/plumed2#657]
Following [this example](https://stackoverflow.com/questions/43168661/openmp-and-reduction-on-stdvector/43169193#43169193), I defined a custom OpenMP reduction, to avoid the `omp critical` part when adding up the derivatives vector, see https://github.com/invemichele/plumed2/commit/9f036ff045382bf82ffa4b4005d3e62c02af64b0

Everything seems to work fine, except for the centos7 action test that fails, I guess because it uses an old OpenMP version < 4.
Is this meant to be? should I go back to a more compatible OpenMP code?

Notice that a similar improvement can be made in various parts of the plumed code, and basically every `#pragma omp critical` directive could be removed. This to me seems like a good thing, but I am new to OpenMP, so there might also be some good reason not to do it.

**Comment by carlocamilloni** [comment]
The reason we are not using it is essentially for compatibility, we had issues in the past and it is not clear how stable are the implementation of openmp4. Does it scales better? In case I think we can protect it to avoid failures with older compilers



Sent from my iPhone

**Comment by PabloPiaggi** [comment]
I tried this last week and couldn't get the intel and intel-mpi compiler to build it. I can check the versions but I'm sure the compiler wasn't very old.

**Comment by invemichele** [comment]
ok, then it is better to avoid it, because the speedup is small.
In case someone else wants to test it I created a branch [here](https://github.com/invemichele/plumed2/tree/custom_omp_reductions) with the changes in Colvar.cpp, Metad.cpp and OPESmetad.cpp
