### ISSUE TITLE
Compute center of mass with PBC and trigonometric functions

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#66]
The typical solution employed now is to have a WHOLEMOLECULES statement so that any entity for which a COM is computed is going to be whole. An alternative approach is that of using periodic functions in scaled coordinates (see e.g. Calculating Center of Mass in an Unbounded 2D Environment, Journal of Graphics, GPU, and Game Tools Volume 13, Issue 4, 2008). It could be more expensive because of the trigonometric functions, but could be used also in cases where it is difficult to use WHOLEMOLECULES (e.g. when defining the center of mass of a membrane)

**Comment by aakognole** [comment]
I wanted to restrain COM of molecule at the center of the box and it is working. 
However when I used POSITION to print the coordinates of COM, I get random -ve signs in front of the x, y and z coordinates. 

INPUT -
a0: FIXEDATOM AT=4.388,4.388,4.388
b0: COM ATOMS=1-1747
pb: POSITION ATOM=b0
d0: DISTANCE ATOMS=a0,b0
r0: RESTRAINT ARG=d0 AT=0 KAPPA=2000
PRINT ARG=pb.x,pb.y,pb.z,d0,r0.bias STRIDE=10 FILE=center.dat

OUTPUT-
 53.000000 4.346674 -4.387779 4.388216 0.041337 1.708731
 53.020000 4.346733 -4.388073 -4.387946 0.041278 1.703858
 53.040000 4.346848 4.388313 -4.387433 0.041172 1.695141

**Comment by GiovanniBussi** [comment]
Please repost this on the mailing list, since it's a question useful for other users. You can refer to this issue with a link if you think it's useful

**Comment by GiovanniBussi** [comment]
This was closed in 19057e2c329bba37b6010348666cfca683f3a8e4
