### ISSUE TITLE
Small problem in visualizing doc

### ISSUE THREAD

**Issue by invemichele** [plumed/plumed2#671]
I noticed a weird minor bug in the sidebar of the documentation.

If I build the user-doc locally it displays correctly:
![Screenshot from 2021-02-22 11-16-56](https://user-images.githubusercontent.com/14904699/108694764-c2e1ea00-74ff-11eb-9d35-6e096840717c.png)

Instead on the plumed website this happens:
![Screenshot from 2021-02-22 11-16-00](https://user-images.githubusercontent.com/14904699/108694794-cd9c7f00-74ff-11eb-8a6a-9b523fcce305.png)

The sections `Overview`, `Installation`, etc... erroneously appear under the `Biases` menu. The same happens for other modules: ANN, FISST, etc..
I guess these sections should not appear (as when building locally), or even better be placed above the `Biases` menu.

It's just a minor visual thing, but maybe it has a simple solution.

**Comment by carlocamilloni** [comment]
@invemichele I think you should use \section instead of ##

**Comment by carlocamilloni** [comment]
I have modified all modules in master, lets' see if it works as expected..

**Comment by invemichele** [comment]
Thanks!
