### ISSUE TITLE
"cmd("isEnergyNeeded") should be only used after plumed initialization error" in gromacs 2019.4 + Plumed 2.6.2

### ISSUE THREAD

**Issue by ghost** [plumed/plumed2#676]
Dear all,

I'm using GROMACS 2019.6 patched for PLUMED 2.6.2. 

Everything is fine when conducting metadynamics. However, when I tried -rerun, error yielded:

Program:     gmx mdrun, version 2019.4

Unknown exception:
(exception type: N4PLMD14ExceptionErrorE)

+++ PLUMED error
+++ at PlumedMain.cpp:513, function virtual void PLMD::PlumedMain::cmd(const
string&, void*)
+++ assertion failed: initialized
+++ message follows +++
cmd("isEnergyNeeded") should be only used after plumed initialization

I didn't change any source code of Plumed or gromacs. 
Meanwhile, "export GMX_DISABLE_MODULAR_SIMULATOR=yes" cannot solve the problem.

has somebody else seen the same problem?

Thanks!

**Comment by therealchrisneale** [comment]
I have the same issue with Gromacs 2019.6 patched with plumed 2.7.2.

without the -plumed flag, gmx mdrun works fine. With that flag:

$ gmx mdrun -s PLUMED.tpr -rerun PLUMED.gro -nt 1 -plumed my.plumed.dat

Program:     gmx mdrun, version 2019.6

Unknown exception:
(exception type: N4PLMD14ExceptionErrorE)

+++ PLUMED error
+++ at PlumedMain.cpp:519, function virtual void PLMD::PlumedMain::cmd(const
string&, void*)
+++ assertion failed: initialized
+++ message follows +++
cmd("isEnergyNeeded") should be only used after plumed initialization

For more information and tips for troubleshooting, please check the GROMACS
website at http://www.gromacs.org/Documentation/Errors

**Comment by therealchrisneale** [comment]
Also, I just verified gromacs 2020.6 patched with plumed 2.7.2 has the same problem. It's related to -rerun with -plumed. I'm guessing it's because the viral and pressure terms are not computed with -rerun. I also verified export GMX_DISABLE_MODULAR_SIMULATOR=yes does not fix the issue with either gromacs 2020.6 or 2019.6

**Comment by namus** [comment]
I have encountered the same problem.

**Comment by carlocamilloni** [comment]
this is the same of #576
