### ISSUE TITLE
Compilation error with 2.7.1 (and 2.6.3)

### ISSUE THREAD

**Issue by wadudmiah** [plumed/plumed2#683]
Hi, 

I am trying to compile plumed 2.7.1 with the following environment: intel/mkl/2018.4 intel/2018.4 python/3.8.0 intel/mpi/2018.4
cmake/3.16.4. The configure line I am using is:
```
CXXFLAGS="-std=c++11" CXX=mpiicpc CC=mpiicc FC=mpiifort ./configure --prefix=$HOME/plumed-2.7.1
```
but I am getting the following compilation error:
```
compiling  ReweightWham.cpp
ReweightWham.cpp(139): error: namespace "std" has no member "begin"
    double minv = *min_element(std::begin(stored_biases), std::end(stored_biases));
                                    ^
ReweightWham.cpp(139): error: namespace "std" has no member "end"
    double minv = *min_element(std::begin(stored_biases), std::end(stored_biases));
                                                               ^
ReweightWham.cpp(139): error: identifier "min_element" is undefined
    double minv = *min_element(std::begin(stored_biases), std::end(stored_biases));
```
I have tried using `-std=c++17` (even though the requirement is just a C++ 11 compiler) and I still get the same compilation error. Any help will be appreciated :-)

**Comment by GiovanniBussi** [comment]
Hi,

my guess is that your intel compiler does not support c++11 library. Usually, the intel compiler needs a recent gcc to be available as well and uses the gcc library.

Which gcc version do you have? (check with `gcc --version` I guess)

**Comment by wadudmiah** [comment]
Hi @GiovanniBussi, 

The Intel compiler supports all the ways up to C++ 17, but the system installed gcc doesn't support C++ 11:
```
$ gcc --version
gcc (GCC) 4.4.7 20120313 (Red Hat 4.4.7-23)
```
How can I tall the Intel compiler to use newer header files? I have newer GCC versions (available as modules).

**Comment by GiovanniBussi** [comment]
I think the option is `-gcc-name`. But I remember I had troubles setting this. Usually, loading a gcc module (so that the modern gcc is available with name `gcc`) works.

**Comment by wadudmiah** [comment]
Hi @GiovanniBussi, 

Yes, you are right. Managed to fix it with your help - thanks!
