### ISSUE TITLE
is it possible for Plumed to read another input file?

### ISSUE THREAD

**Issue by thangckt** [plumed/plumed2#684]
Dear Developers,

I wonder if it is possible to let Plumed can read a "plumed code" contained in another file?
A function similar to the command "include" of LAMMPS, as this description: https://lammps.sandia.gov/doc/include.html

This function will be helpful when we want to initiatete some input parameters which automatically generated from MD engine into the Plumed code.

Thank you.

**Comment by GiovanniBussi** [comment]
@thangckt what do you mean with this?
> This function will be helpful when we want to initiatete some input parameters which automatically generated from MD engine into the Plumed code.

The LAMMPS command seems to do something similar to [INCLUDE](https://www.plumed.org/doc-v2.7/user-doc/html/includes.html). Is this what you need?

**Comment by thangckt** [comment]
Yes, it is.

Thank you for your showing. 
And sorry because I seem to bother, I didn't recognize this command on my first searching.
