### ISSUE TITLE
Configure: optional modules don't get enabled correctly

### ISSUE THREAD

**Issue by simonlichtinger** [plumed/plumed2#685]
On trying to configure plumed 2.7.1 to include drr and funnel, using the command-line 

`./configure --enable-boost_serialization --enable-modules=+drr+funnel --prefix=$HOME/opt `

the output of the configure script will claim:

configure: Optional modules are disabled by default
configure: Enabling module drr
configure: Enabling module funnel 

and after make and make install the output of ` plumed config module drr ` is "drr on".

However, DRR actions are not recognised in a plumed input script 

(producing "+++ PLUMED error
+++ at PlumedMain.cpp:706, function void PLMD::PlumedMain::readInputWords(const std::vector<std::__cxx11::basic_string<char> >&)
+++ message follows +++
ERROR
I cannot understand line: DRR LABEL=eabf ARG=phi,psi FULLSAMPLES=500 GRID_MIN=-pi,-pi GRID_MAX=pi,pi GRID_BIN=180,180 FRICTION=8.0,8.0 TAU=0.5,0.5 OUTPUTFREQ=50000 HISTORYFREQ=500000" on attempting to use the example script from the documentation)

and the plumed drr_tool command line tool is not available ( "ERROR: unknown command drr_tool. Use 'plumed help' for help" )

Not sure if I'm simply making a setup mistake, but if so, the documentation would need to be adapted to highlight it.

Many thanks for your help!
Simon

**Comment by GiovanniBussi** [comment]
The ddr module also requires boost to be available and enabled (with `--enable-boost_serialization`)

**Comment by simonlichtinger** [comment]
Thanks for your message. The boost libraries are installed and in the configure command as quoted above, I did set the flag. Or was it set incorrectly in that command? `./configure --enable-boost_serialization --enable-modules=+drr+funnel --prefix=$HOME/opt `

**Comment by HanatoK** [comment]
Hi Simon,

Could you post the config.log of your configuration and the result of 
running "plumed drr_tool --help"?

Best,

Haochuan Chen

**Comment by simonlichtinger** [comment]
Please find the config.log attached. 
[config.log](https://github.com/plumed/plumed2/files/6391841/config.log)

Having a quick look at that myself, it seems it failed to find the boost libraries. However, I installed them to $HOME/opt , here's the content of $HOME/opt/lib : 

:~/opt/lib$ ls
libboost_serialization.a          libboost_wserialization.a          libplumed.a         libplumedWrapper.a
libboost_serialization.so         libboost_wserialization.so         libplumedKernel.so  pkgconfig
libboost_serialization.so.1.55.0  libboost_wserialization.so.1.55.0  libplumed.so        plumed

**Comment by HanatoK** [comment]
@simonlichtinger 
Sorry, I just see the latest email instead of reading this original post.
From the log I can see that the header files `boost/archive/text_oarchive.hpp` of the boost serialization library is not found. I attach my log for a comparison.
[config.log](https://github.com/plumed/plumed2/files/6391875/config.log)

**Comment by simonlichtinger** [comment]
@HanatoK Thanks for your reply! I have now run with the additional flags in this command (the files are in $HOME/opt): `./configure --enable-boost_serialization --enable-modules=+drr+funnel --prefix=$HOME/opt LDFLAGS=-L/$HOME/opt/lib CPPFLAGS=-I/$HOME/opt/include` 

This produces the following config.log which seems to resolve the issue of finding the boost library: 
[config.log](https://github.com/plumed/plumed2/files/6392002/config.log)

However, following "make -j 12" and then "make install" (and the plumed binary is now the new one by last modified date), I am still getting the same issues as before, so for some reason the problem doesn't seem to be fixed ...

**Comment by HanatoK** [comment]
@simonlichtinger 
Could you run `ldd $HOME/opt/bin/plumed` to see if it is linked with `libboost_serialization.so`?

**Comment by simonlichtinger** [comment]
@HanatoK No, it does not seem to be. Here's the output:

~/opt$ ldd bin/plumed
        linux-vdso.so.1 (0x00007ffe1ad7b000)
        libplumedKernel.so => /biggin/b197/sjoh5255/opt/lib/libplumedKernel.so (0x00007f4aeb5d5000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4aeb3d1000)
        libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f4aeb048000)
        libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f4aeae30000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4aeaa3f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4aea822000)
        liblapack.so.3 => /usr/lib/x86_64-linux-gnu/liblapack.so.3 (0x00007f4ae9f9c000)
        libblas.so.3 => /usr/lib/x86_64-linux-gnu/libblas.so.3 (0x00007f4ae9d41000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4ae99a3000)
        libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f4ae9774000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4ae9555000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4aec245000)
        libopenblas.so.0 => /usr/lib/x86_64-linux-gnu/libopenblas.so.0 (0x00007f4ae72af000)
        libgfortran.so.4 => /usr/lib/x86_64-linux-gnu/libgfortran.so.4 (0x00007f4ae6ed0000)
        libquadmath.so.0 => /usr/lib/x86_64-linux-gnu/libquadmath.so.0 (0x00007f4ae6c90000)

The configure output now does seem to show it recognizes it. What could be going wrong?

**Comment by HanatoK** [comment]
@simonlichtinger 
I am not sure why it does not work, but here are some possible fixes:
1. For `LDFLAGS` I think `-L/$HOME/opt/lib -lboost_serialization` is necessary. (not only `-L/$HOME/opt/lib`)
2. Try `make clean` before compiling again.

**Comment by simonlichtinger** [comment]
Regarding 1) I had tried that. But 2) worked, and both plumed drr_tool --help runs and the "DRR" action is recognised.

I'll close this issue then, hoping then from here on things should work. Many thanks for your help!
