### ISSUE TITLE
Compilation failure due to missing include in src/lepton/Operation.h

### ISSUE THREAD

**Issue by akohlmey** [plumed/plumed2#693]
When compiling plumed version 2.7.1 on a Fedora 34 x86_64 machine with GCC version 11.1 compilation fails due to the `src/lepton/Operation.h` file using `std::numeric_limits()` without `#include <limits>`.

https://en.cppreference.com/w/cpp/types/numeric_limits

**Comment by GiovanniBussi** [comment]
@akohlmey thanks!

Are you aware of any static checker that can find these types of errors?

**Comment by akohlmey** [comment]
> @akohlmey thanks!
> 
> Are you aware of any static checker that can find these types of errors?

This was found simply by trying to compile after I upgraded my office desktop to Fedora 34 (which has a newer version of GCC and glibc and apparently some implicit include was removed).

For LAMMPS I occasionally use [Include What You Use (IWYU)](https://include-what-you-use.org/) to analyze the use of include files. This is the tool I know to be most likely to spot inconsistencies in include file handling. We have formulated some conventions for how we prefer that include files are used aligned with that tool: https://github.com/lammps/lammps/blob/master/doc/include-file-conventions.md

That has helped quite a bit to spot implicit or indirect include file dependencies (e.g. some include file depends on some other include file being included by the include that is listed before the file in question. Thus reversing the order will make compilations fail) and drop include files in favor of forward declarations where possible. This is made easier by using clang-format with the `SortIncludes` setting on `true`.

However,  IWYU is a far from perfect tool, so the output has to be analyzed carefully and you may need to use some special comments to "nudge" it into the right direction (if you grep through the LAMMPS sources for IWYU you'll see). Given the large number of files in LAMMPS this was very time consuming the first time.  Also, some of the ways how LAMMPS handles things are rather unexpected for the heuristics that IWYU employs, and its support for C++ versions of C library headers is a work in progress.  We have some CMake scripting to make it work reasonably well within our build system (CMake has a built in feature to generate the necessary JSON file reporting the compilation commands and flags). For traditional makefiles I don't know. Using CMake is far superior for supporting these kinds of development features (unit testing, code coverage, instrumentation with sanitizer libraries, IWYU support, etc.) and after a couple years of continued improvements of the scripts and settling on a minimum CMake version of 3.10 it has become so convenient that I rarely build LAMMPS the traditional way anymore.
