### ISSUE TITLE
unable to execute after installation

### ISSUE THREAD

**Issue by debanjansen48** [plumed/plumed2#695]
From terminal if I call plumd it returns
(base) debanjan@debanjan:~/Desktop$ plumed
Nothing to do. Use 'plumed help' for help

"Gromacs installed and in working condition
(base) debanjan@debanjan:~/Desktop$ gmx
                         :-) GROMACS - gmx, 2018.1 (-:

                            GROMACS is written by:
     Emile Apol      Rossen Apostolov      Paul Bauer     Herman J.C. Berendsen
    Par Bjelkmar    Aldert van Buuren   Rudi van Drunen     Anton Feenstra  
  Gerrit Groenhof    Aleksei Iupinov   Christoph Junghans   Anca Hamuraru   
 Vincent Hindriksen Dimitrios Karkoulis    Peter Kasson        Jiri Kraus    
  Carsten Kutzner      Per Larsson      Justin A. Lemkul    Viveca Lindahl  
  Magnus Lundborg   Pieter Meulenhoff    Erik Marklund      Teemu Murtola   
    Szilard Pall       Sander Pronk      Roland Schulz     Alexey Shvetsov  
   Michael Shirts     Alfons Sijbers     Peter Tieleman    Teemu Virolainen 
 Christian Wennberg    Maarten Wolf   
                           and the project leaders:
        Mark Abraham, Berk Hess, Erik Lindahl, and David van der Spo.."

but when I enter into MD directory it returns following error
(base) debanjan@debanjan:/usr/local/gromacs/bin$ sudo plumed patch -p
[sudo] password for debanjan:         
plumed: error while loading shared libraries: **libplumedKernel.so**: cannot open shared object file: No such file or directory

(base) debanjan@debanjan:~/Desktop$ whereis plumed
plumed: /usr/local/bin/plumed /usr/local/lib/plumed /home/debanjan/miniconda3/bin/plumed
(base) debanjan@debanjan:~/Desktop$ which plumed
/home/debanjan/miniconda3/bin/plumed

**Comment by debanjansen48** [comment]
Sir, My gromacs folder present in /usr/local/bin

i thought sudo may be required to patch MD engine so used sudo..

during compilation i am encountered by following error which I ignored initially
+ test ves/rt-td-uniform/ NOT APPLICABLE
+ check file ves/rt-td-uniform/report.txt for more information
+ test ves/rt-td-vonmises/ NOT APPLICABLE
+ check file ves/rt-td-vonmises/report.txt for more information
+ test ves/rt-VesDeltaF/ NOT APPLICABLE
+ check file ves/rt-VesDeltaF/report.txt for more information
+ test ves/rt-VesDeltaF-mwalkers/ NOT APPLICABLE
+ check file ves/rt-VesDeltaF-mwalkers/report.txt for more information
+ ERROR in test basic/rt-vimsyntax/
+ check file basic/rt-vimsyntax/report.txt for more information
+++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Final report:
+ 293 tests performed, 201 tests not applicable
+ 1 errors found
+ Find the bug!
+ To replace references, go to the test directory and
+ type 'make reset'
Makefile:14: recipe for target 'checkfail' failed
make[1]: *** [checkfail] Error 1
make[1]: Leaving directory '/home/debanjan/plumed-2.6.3/regtest'
Makefile:65: recipe for target 'check' failed
make: *** [check] Error 2
  

but it installed 
what are the mistakes I am doing during installation, I am unable to recognize plz help.

**Comment by debanjansen48** [comment]
After executing sudo make install it return following errors

cd install/python && rm -fr *.so plumed.cpp build && \
          unset CXX && unset CC && unset CFLAGS && unset CXXFLAGS && unset LDSHARED && \
          plumed_program_name=plumed \
          plumed_force_cython=yes \
          plumed_version=2.6.3 \
          plumed_include_dir=../../../wrapper \
          plumed_default_kernel="/usr/local/lib/libplumedKernel.so" \
          python setup.py build_ext -i
Traceback (most recent call last):
  File "setup.py", line 37, in <module>
    raise ImportError("PLUMED 2.6 only supports Python 3")
ImportError: **PLUMED 2.6 only supports Python 3**
Makefile:247: recipe for target 'install' failed
make[2]: *** [install] Error 1
make[2]: Leaving directory '/home/debanjan/plumed-2.6.3/src/lib'
Makefile:11: recipe for target 'install' failed
make[1]: *** [install] Error 2
make[1]: Leaving directory '/home/debanjan/plumed-2.6.3/src'
Makefile:35: recipe for target 'install' failed
make: *** [install] Error 2


(base) debanjan@debanjan:~/plumed-2.6.3$ python
**Python 3.8.2** (default, Mar 26 2020, 15:53:00) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>>

**Comment by GiovanniBussi** [comment]
I am afraid it is not possible to install plumed with sudo if, as in your case, python3 is not available to root user. If you need python wrappers, you should install python3 so that it is available to root user. Alternatively, you can reconfigure plumed to skip the compilation of python wrappers, with `./configure --disable-python`
