### ISSUE TITLE
Erro in Patching the file 

### ISSUE THREAD

**Issue by parazue** [plumed/plumed2#696]
PLUMED location: /usr/local/lib/plumed
diff file: /usr/local/lib/plumed/patches/gromacs-2020.4.diff
sourcing config file: /usr/local/lib/plumed/patches/gromacs-2020.4.config
ERROR: Preliminary test not passed.
It seems that this is not gromacs-2020.4, or you are in the wrong directory
If you are sure about what you are doing, use -f

Am getting the above error.  How to rectify it.

**Comment by GiovanniBussi** [comment]
The error message tells you that you are launching the command from the wrong directory.

Did you try to cd to the root directory of gromacs?

**Comment by parazue** [comment]
sir , i tried but it return error

i am sending the error

***@***.***:~$ plumed help
Usage: plumed [options] [command] [command options]
  plumed [command] -h|--help: to print help for a specific command
Options:
  [help|-h|--help]          : to print this help
  [--is-installed]          : fails if plumed is not installed
  [--has-mpi]               : fails if plumed is running without MPI
  [--has-dlopen]            : fails if plumed is compiled without dlopen
  [--load LIB]              : loads a shared object (typically a plugin
library)
  [--standalone-executable] : tells plumed not to look for commands
implemented as scripts
Commands:
  plumed completion : dump a function usable for programmable completion
  plumed driver : analyze trajectories with plumed
  plumed driver-float : analyze trajectories with plumed (single precision
version)
  plumed gentemplate : print out a template input for a particular action
  plumed info : provide informations about plumed
  plumed kt : print out the value of kT at a particular temperature
  plumed manual : print out a description of the keywords for an action in
html
  plumed pathtools : print out a description of the keywords for an action
in html
  plumed pdbrenumber : Modify atom numbers in a PDB, possibly using
hybrid-36 coding
  plumed pesmd : Langevin dynamics on PLUMED energy landscape
  plumed simplemd : run lj code
  plumed sum_hills : sum the hills with  plumed
  plumed selector : create lists of serial atom numbers
  plumed mklib : compile a .cpp file into a shared library
  plumed newcv : create a new collective variable from a template
  plumed vim2html : convert plumed input file to colored html using vim
syntax
  plumed config : inquire plumed about how it was configure
  plumed partial_tempering : scale parameters in a gromacs topology to
implement solute or partial tempering
  plumed patch : patch an MD engine
***@***.***:~$ plumed patch -p
PLUMED patching tool

1) amber18    4) gromacs-2020.4 7) namd-2.13
2) gromacs-2018.8   5) gromacs-4.5.7 8) qespresso-5.0.2
3) gromacs-2019.6   6) namd-2.12 9) qespresso-6.2
Choose the best matching code/version:4
MD engine: gromacs-2020.4
PLUMED location: /usr/local/lib/plumed
diff file: /usr/local/lib/plumed/patches/gromacs-2020.4.diff
sourcing config file: /usr/local/lib/plumed/patches/gromacs-2020.4.config
ERROR: Preliminary test not passed.
It seems that this is not gromacs-2020.4, or you are in the wrong directory
If you are sure about what you are doing, use -f





*With Thanks & Regards,*
*Dr. PARASURAMAN.P*
*Assistant Professor of Pharmaceutical Chemistry,*
*Faculty of Pharmacy, *
*M.S. Ramaiah University of Applied Sciences,*
*University House, Gnanagangothri Campus,*
*New BEL Road, M.S. R Nagar,*
*Bengaluru-560054, Karnataka, India.*

*Mobile No.: +91-9629396767*
*Home page
<http://www.msruas.ac.in/staff/fph_pharmachem#Parasuraman>.  Research Gate
<https://www.researchgate.net/profile/Parasuraman_Pavadai> . LinkedIN
<https://www.linkedin.com/in/dr-parasuraman-pavadai-a7713547/> . Google
Scholar <https://scholar.google.co.in/citations?hl=en&user=JwIroG8AAAAJ>*

*"Success is the result of perfection, hard work, learning from failure,
loyalty, and persistence"*

**Comment by parazue** [comment]
***@***.***:~$ whereis gromacs
gromacs: /usr/local/gromacs
***@***.***:~$ cd /usr/local/gromacs
***@***.***:/usr/local/gromacs$ ls
bin  include  lib  share
***@***.***:/usr/local/gromacs$ plumed patch -p
PLUMED patching tool

1) amber18    4) gromacs-2020.4 7) namd-2.13
2) gromacs-2018.8   5) gromacs-4.5.7 8) qespresso-5.0.2
3) gromacs-2019.6   6) namd-2.12 9) qespresso-6.2
Choose the best matching code/version:4
MD engine: gromacs-2020.4
PLUMED location: /usr/local/lib/plumed
diff file: /usr/local/lib/plumed/patches/gromacs-2020.4.diff
sourcing config file: /usr/local/lib/plumed/patches/gromacs-2020.4.config
ERROR: Preliminary test not passed.
It seems that this is not gromacs-2020.4, or you are in the wrong directory
If you are sure about what you are doing, use -f

is there any straight forward way to install it???




*With Thanks & Regards,*
*Dr. PARASURAMAN.P*
*Assistant Professor of Pharmaceutical Chemistry,*
*Faculty of Pharmacy, *
*M.S. Ramaiah University of Applied Sciences,*
*University House, Gnanagangothri Campus,*
*New BEL Road, M.S. R Nagar,*
*Bengaluru-560054, Karnataka, India.*

*Mobile No.: +91-9629396767*
*Home page
<http://www.msruas.ac.in/staff/fph_pharmachem#Parasuraman>.  Research Gate
<https://www.researchgate.net/profile/Parasuraman_Pavadai> . LinkedIN
<https://www.linkedin.com/in/dr-parasuraman-pavadai-a7713547/> . Google
Scholar <https://scholar.google.co.in/citations?hl=en&user=JwIroG8AAAAJ>*

*"Success is the result of perfection, hard work, learning from failure,
loyalty, and persistence"*
