### ISSUE TITLE
libplumedKernel.so: cannot open 

### ISSUE THREAD

**Issue by kimlabSchatterjee** [plumed/plumed2#700]
I am explaining the instillation steps
1. after downloading from git I extracted all the staffs and entered into the plumed folder

2. I issued the command  ./configure  --enable-modules=all --enable-pdfdoc=yes --enable-boost_graph=yes --enable-boost_serialization=yes --enable-fftw=yes --enable-af_cuda=yes --enable-af_cpu=yes --enable-python=no

3.  make -j8
4. sudo make install#
###(however I used ./configure  --prefix=$HOME/opt. certainly i did not required sudo to install. I also tried ./configure  --prefix=/opt/plumed for which i need to use sudo)

I Set environmental variable 
 export PLUMED_KERNEL=/usr/local/lib/libplumedKernel.so
export PLUMED_USE_LEPTON=yes
PLUMED_VIMPATH=/usr/local/lib/plumed/vim
but when i call plumed it returns following error. I am unable to figure it out. 

**plumed: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory**

kindly help me to solve the issue.

once it installed I want to extract gromacs zipped file. after entering insnide  the extracted gromacs folder I want to use plumed patch -p command . Then  using cmake i will build gromacs

please help to resolve the issue.

**Comment by GiovanniBussi** [comment]
Can you confirm the file `/usr/local/lib/libplumedKernel.so` exist (with `ls /usr/local/lib/libplumedKernel.so`)? Maybe you should use `PLUMED_KERNEL=$HOME/opt/lib/libplumedKernel.so`?

**Comment by kimlabSchatterjee** [comment]
(base) kimlab@kimlab:~/Desktop$ whereis libplumedKernel.so
libplumedKernel: /usr/local/lib/libplumedKernel.so
(base) kimlab@kimlab:~/Desktop$ plumed
plumed: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory
(base) kimlab@kimlab:~/Desktop$ ls /usr/local/lib/libplumedKernel.so
/usr/local/lib/libplumedKernel.so
(base) kimlab@kimlab:~/Desktop$ plumed
plumed: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory

also put this line "PLUMED_KERNEL=$HOME/opt/lib/libplumedKernel.so" in bashrc but no work :(

**Comment by GiovanniBussi** [comment]
So, if $HOME/opt/lib/libplumedKernel.so exist I guess what does not exist
is one of the dependencies

Try:
```
ldd $HOME/opt/lib/libplumedKernel.so
```
It might tell you which of the dependencies is not found. You should then
add its path to env var LD_LIBRARY_PATH

Giovanni

**Comment by kimlabSchatterjee** [comment]
(base) kimlab@kimlab:~/Desktop$ ls $HOME/opt/lib/libplumedKernel.so
/home/kimlab/opt/lib/libplumedKernel.so
(base) kimlab@kimlab:~/Desktop$ ldd $HOME/opt/lib/libplumedKernel.so
	linux-vdso.so.1 (0x00007ffe607dd000)
	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007f54a588e000)
	libboost_serialization.so.1.65.1 => /usr/lib/x86_64-linux-gnu/libboost_serialization.so.1.65.1 (0x00007f54a5650000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f54a5433000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f54a522f000)
	libmpi_cxx.so.20 => /usr/lib/x86_64-linux-gnu/libmpi_cxx.so.20 (0x00007f54a5015000)
	libmpi.so.20 => /usr/lib/x86_64-linux-gnu/libmpi.so.20 (0x00007f54a4d23000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f54a4985000)
	libgomp.so.1 => /usr/lib/x86_64-linux-gnu/libgomp.so.1 (0x00007f54a4756000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f54a453e000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f54a431f000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f54a3f2e000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f54a6b0f000)
	libopen-rte.so.20 => /usr/lib/x86_64-linux-gnu/libopen-rte.so.20 (0x00007f54a3ca6000)
	libopen-pal.so.20 => /usr/lib/x86_64-linux-gnu/libopen-pal.so.20 (0x00007f54a39f4000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f54a37ec000)
	libhwloc.so.5 => /usr/lib/x86_64-linux-gnu/libhwloc.so.5 (0x00007f54a35af000)
	libutil.so.1 => /lib/x86_64-linux-gnu/libutil.so.1 (0x00007f54a33ac000)
	libnuma.so.1 => /usr/lib/x86_64-linux-gnu/libnuma.so.1 (0x00007f54a31a1000)
	libltdl.so.7 => /usr/lib/x86_64-linux-gnu/libltdl.so.7 (0x00007f54a2f97000)
unable to figure it out...

**Comment by GiovanniBussi** [comment]
Did you check if the problem is solved removing some of the configured options:
```
./configure --enable-modules=all --enable-pdfdoc=yes --enable-boost_graph=yes --enable-boost_serialization=yes --enable-fftw=yes --enable-af_cuda=yes --enable-af_cpu=yes --enable-python=no
```
I would try to remove arrayfire and boost to see if some of them is causing the problem

**Comment by kimlabSchatterjee** [comment]
./configure  --enable-modules=all --enable-FEATURE=yes  --enable-python=n
make 
make install

(base) kimlab@kimlab:~/Desktop$ whereis plumed
plumed: /usr/local/bin/plumed /usr/local/lib/plumed
(base) kimlab@kimlab:~/Desktop$ 



(base) kimlab@kimlab:~/Downloads/plumed-2.5.7$ plumed
plumed: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory

imlab@kimlab:~/Desktop$ whereis  libplumedKernel.so
libplumedKernel: /usr/local/lib/libplumedKernel.so


(base) kimlab@kimlab:~/Desktop$ whereis  libplumedKernel.so
libplumedKernel: /usr/local/lib/libplumedKernel.so

(base) kimlab@kimlab:~/Desktop$ export plumed=/usr/local/lib/libplumedKernel.so
(base) kimlab@kimlab:~/Desktop$ plumed
plumed: error while loading shared libraries: libplumedKernel.so: cannot open shared object file: No such file or directory
(base) kimlab@kimlab:~/Desktop$ 


I am facing same issue...

I am from south Korea, Due to some other work i was bit late to reply. Kindly accept my apology. Plz help me.

**Comment by GiovanniBussi** [comment]
I don't understand. Did you install on `/usr/local/` or on `$HOME/opt`?

Please do:
```
which plumed
```
to know where plumed is. Let's say it is in `pippo/bin`, do
```
ldd pippo/lib/libplumedKernel.so
```

**Comment by kimlabSchatterjee** [comment]
(base) kimlab@kimlab:~/Desktop$ which plumed
/usr/local/bin/plumed
(base) kimlab@kimlab:~/Desktop$ ldd pippo/lib/libplumedKernel.so
ldd: pippo/lib/libplumedKernel.so: No such file or directory
(base) kimlab@kimlab:~/Desktop$ whereis libplumedKernel.so
libplumedKernel: /usr/local/lib/libplumedKernel.so
(base) kimlab@kimlab:~/Desktop$

**Comment by GiovanniBussi** [comment]
Did you read this sentence?
> Let's say it is in pippo/bin,

In your case, please type
```
ldd /usr/local/lib/libplumedKernel.so
```

**Comment by carlocamilloni** [comment]
this is for the mailing list, anyway double check your install path
