### ISSUE TITLE
Low utilization of GPU

### ISSUE THREAD

**Issue by J-You** [plumed/plumed2#701]
Hi all,

I installed plumed-2.6.1 with GPU package successfully.
But the utilization of GPU is low, around 5%.
I run the lammps by the command: `mpirun -np 8 lmp_mpi -sf gpu -pk gpu 2 -in in.plumed`
The utilization is high for the run without plumed.

Thanks for your any help.

**Comment by J-You** [comment]
Hello,
Do you have any suggestion?

**Comment by GiovanniBussi** [comment]
@J-You did you check first on the LAMMPS mailing list or GitHub? I am afraid this is a bit out of control on the PLUMED side.

**Comment by J-You** [comment]
Thanks for your response.

**Comment by PabloPiaggi** [comment]
Hi @J-You , are you doing expensive calculations on Plumed? Plumed runs only on the CPUs so the GPUs would be idle during the calculation done using Plumed. If this is the case there are several things that you can try to speed up the calculation.

**Comment by J-You** [comment]
Hi @PabloPiaggi.
I want to simulate crystallization, like your published works. Maybe it needs expensive computation cost?
Could you please introduce more details about the method of acceleration?
Thanks for your response.

**Comment by PabloPiaggi** [comment]
There is a good explanation in the manual. See this [link](https://www.plumed.org/doc-master/user-doc/html/_performances.html). Without knowing the collective variable you are using I can only suggest to have a look at multiple time stepping. You can also search the [mailing list](https://groups.google.com/g/plumed-users) for related posts. Also, this question is probably more appropriate for the mailing list than for a github issue.

**Comment by J-You** [comment]
Thanks for your answer. It makes me a lot.
