### ISSUE TITLE
Failure regtests OPES

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#716]
@invemichele can you check this?
https://github.com/plumed/plumed2/runs/2997927043
```
+++++++++++++++++++++++++++++++++++++++++++++++++++++
+ Test session ended at Tue Jul  6 10:56:39 UTC 2021
+ ERROR in test opes/rt-opes_metad_explore-restart/
+ check file opes/rt-opes_metad_explore-restart/report.txt for more information
+ ERROR in test opes/rt-opes_metad_explore/
+ check file opes/rt-opes_metad_explore/report.txt for more information
+++++++++++++++++++++++++++++++++++++++++++++++++++++
```

There was not error when the PR was tested a few days ago, I guess this is an incompatibility between your first and second PR. Thanks!

**Comment by GiovanniBussi** [comment]
Sorry, it's the other way round: the PR on master was fixing things. I close this issue

**Comment by invemichele** [comment]
Yes, the splitting of the code between v2.7 and v2.8 that I ended up with it's a little unfortunate... But hopefully from now on I will only have to modify v2.8 and not both, and things will be more straight forward!
