### ISSUE TITLE
Issue with GRID_MIN/GRID_MAX in HISTOGRAM action

### ISSUE THREAD

**Issue by valsson** [plumed/plumed2#717]
By chance, I noticed an issue with `GRID_MIN/GRID_MAX` in `HISTOGRAM` action.

It is possible to give a random string as a value to `GRID_MIN/GRID_MAX` and the code still runs without an error. Instead, it seems to take 0.0 as the grid value. 

For example, you can see this in `regtest/analysis/rt-histo`: 

If you use 

HISTOGRAM ...
  ARG=x
  GRID_MIN=0.0
  **GRID_MAX=blabla**
  GRID_BIN=ffa
  BANDWIDTH=0.1
  LABEL=hA1
... HISTOGRAM

Gives 

#! FIELDS x hA1 dhA1_x
#! SET normalisation    1.0000
#! SET min_x 0.0
**#! SET max_x blabla**
#! SET nbins_x  100
#! SET periodic_x false
   0.0000   1.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000
   0.0000   0.0000   0.0000

I guess it would be better to add a check on either the parsing of GRID_MIN/GRID_MAX that the parameters gives are proper numbers. Or maybe better in the `setBounds` function in `gridtools/HistogramOnGrid.cpp` to avoid this problem happening elsewhere.

**Comment by valsson** [comment]
I note that using 

GRID_MIN=-pi
GRID_MAX=pi

Works as expected

**Comment by GiovanniBussi** [comment]
@gtribello could it be related to the fact that [these conversions](https://github.com/plumed/plumed2/blob/master/src/gridtools/GridVessel.cpp#L95-L96) do not check the returned bool?

**Comment by gtribello** [comment]
@GiovanniBussi yes I think if you check the returned bool and put in an error then the problem will be fixed.

**Comment by GiovanniBussi** [comment]
What scares me is the output of this command:
```
git grep "Tools::convert"
```

**Comment by GiovanniBussi** [comment]
In many cases it is used to convert numbers to strings (e.g. for printing) and that's fine. But when it is used for reading an input it could have this problem.

**Comment by GiovanniBussi** [comment]
I confirm (in `regtest/basic/rt21/plumed.dat`) that if I change:
```
m1g: METAD ARG=r1g HEIGHT=0.1 PACE=10000000 SIGMA=1.0  FILE=H1G GRID_MIN=0.0 GRID_MAX=20.0 GRID_BIN=100
```
to
```
m1g: METAD ARG=r1g HEIGHT=0.1 PACE=10000000 SIGMA=1.0  FILE=H1G GRID_MIN=bla GRID_MAX=20.0 GRID_BIN=100
```
The result is not affected. This is actually very annoying... Thanks @valsson for pointing this out!
