### ISSUE TITLE
Plumed Spack package (2.7.1, 2.6.3, 2.5.7)

### ISSUE THREAD

**Issue by w8jcik** [plumed/plumed2#718]
Spack is a package manager for clusters. It has Plumed package and it can install Gromacs patched with Plumed.

For example:
```
spack install plumed@2.7.1
spack install gromacs@2021+cuda~mpi+plumed
```

I have added recent Plumed release to that packages

https://github.com/spack/spack/pull/24912/files

An issue is that `plumed` package have no maintainer. I received suggestion to become a maintainer. Unfortunatelly I don't use it much and I don't feel competent for this.

a) Maybe someone here would want to add herself/himself as a maintainer. It means receiving reviews of changes to that package.
b) If not, maybe someone from Plumed team could review that Pull Request from a link above and leave a comment if the change is correct or not.

**Comment by w8jcik** [comment]
**Update:**
- Pull Request in question have been mergedIf you have a minute maybe you cound still take a look if I got versioning of Plumed correctly. Also maybe you would like to consider adding some Plumed-related person as a maintainer there. Good packaging improves popularity of projects. Other than this, this issue can be closed.

**Comment by GiovanniBussi** [comment]
@w8jcik thanks for you report. I am personally maintaining MacPorts and Conda packages for PLUMED, and a few other people in our community are maintaining AUR and FreeBSD packages. I think that the optimum is if there's someone that is actually using spack and plumed and wants to jump in. I will open a separate ticket for this.
