### ISSUE TITLE
Someone maintaining PLUMED Spack package

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#719]
As mentioned in #718, it might be good if anyone wants to become a maintainer for the spack PLUMED package.

I leave this issue open in case anyone is interested.

**Comment by marcodelapierre** [comment]
Hi @GiovanniBussi , as per our email conversation, I might be able to pick this one up soon.

**Comment by marcodelapierre** [comment]
Just to add some more perspective, I have the impression the Spack recipe for Plumed *per se* should not be too hard to keep updated.
One more challenging aspect, though, might be ensuring that Spack recipes for QM/MD codes using Plumed do enable a working interface with it.
I will update this as I take a deeper dive in Spack.

**Comment by GiovanniBussi** [comment]
@marcodelapierre feel free to ask for help or to review the recipe here. Thanks again!

**Comment by GiovanniBussi** [comment]
Spack is now included in https://repology.org so it is now possible to check if [plumed version](https://repology.org/project/plumed/information) is up to date. I added a badge to the README file (50bdf83ac56778e97372a1d981882b25636ee642)

**Comment by marcodelapierre** [comment]
We had some delays with the setup of our new supercomputer, but ...I will be starting to work on Spack recipes quite soon now

**Comment by marcodelapierre** [comment]
Added myself as maintainer in this PR: https://github.com/spack/spack/pull/29743

**Comment by w8jcik** [comment]
Another update https://github.com/spack/spack/pull/30787/files

**Comment by marcodelapierre** [comment]
Working on this PR that adds optional modules and improves the way they can be handled as Spack variant: https://github.com/spack/spack/pull/29743

**Comment by marcodelapierre** [comment]
PR https://github.com/spack/spack/pull/29743 got merged on 30 June . I am now the maintainer of the Plumed recipe in Spack.
@GiovanniBussi I think this issue can be closed then.
