### ISSUE TITLE
SASA does not compile with recent INTEL compilers on GitHub Actions

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#721]
@andrea-arsiccio I add this issue in case you want to solve this.

After recent intel compilers updated (I think this first appeared a few weeks ago), your source files trigger and internal error of the compiler:
```
icpc: error #10106: Fatal error in /opt/intel/oneapi/compiler/2021.2.0/linux/bin/intel64/../../bin/intel64/mcpcom, terminated by kill signal
compilation aborted for sasa_HASEL.cpp (code 1)
```

I first tried to get rid of the problem [downgrading intel compiler](cc47166331617ae5f967b5727033884468f5ecbb) but now the problem appeared again. I am momentarily [switching off the testing of your module](50ecd12f3ad0837379f3fca5544a8ead0c66c9b7) when we test the intel compiler.

If you want to fix this, please try to install the latest intel compiler on your machine and see if you can reproduce the problem. To show that it is fixed, you could make a pull request were you did `git revert 50ecd12f3ad0837379f3fca5544a8ead0c66c9b7` to re-enable SASA testing and see if the GitHub Action intel build succeeds.

**Comment by GiovanniBussi** [comment]
@andrea-arsiccio I suspect the problem is with the initializer list used to allocate the maps, that exceeds the compiler memory. You can try to replace:
```
  haselmap = {
    { "ALA_N", {
        "1.55",
        "1.028",
        "H",
        "CA",
        "Z",
        "Z",
      }
    },
...
};
```
with
```
  haselmap["ALA_N"]={"1.55","1.028","H","CA","Z","Z",};
  haselmap["ALA_CA"]={"1.7","2.149","N","C","CB","Z",};
...
```

**Comment by andrea-arsiccio** [comment]
Hello,
sorry for the late reply.
Sure, I will try to fix the issue, and send a new pull request as soon as
possible. Thanks a lot as usual for the helpful suggestions!
Best regards,
Andrea

Il giorno lun 19 lug 2021 alle ore 14:27 Giovanni ***@***.***>
ha scritto:
