### ISSUE TITLE
Having pressure as an available CV

### ISSUE THREAD

**Issue by xiki-tempula** [plumed/plumed2#724]
Sometimes, it is desirable to include pV in the CV. The Volume is currently available and it might also be good to have pressure as an available CV as well.

**Comment by GiovanniBussi** [comment]
Sorry, it is not very clear to me what do you mean with having the pressure as a variable.

Do you mean the **external** pressure? That's actually a constant, and you can easily put it in the input file, though we could indeed pass it from the MD code as we do for the temperature.

Or do you mean the **internal** pressure?

**Comment by xiki-tempula** [comment]
Sorry for the confusion. It is the internal pressure.
Say if we run gmx energy, one could extract the pressure from the MD run.

**Comment by GiovanniBussi** [comment]
The point is that the derivatives of **internal pressure** wrt positions and cell box are non trivial. I guess the configurational part would depend on second derivatives of energy wrt positions. So I don't think they could be used in biased collective variables, which is the main thing that plumed does.

Does it make sense?

**Comment by xiki-tempula** [comment]
Thanks. 
It would be nice to have it along with the CB but I could later recover it from the energy.edr file, so it is not a problem.
