### ISSUE TITLE
There may be a problem with RMSD calculation?

### ISSUE THREAD

**Issue by thangckt** [plumed/plumed2#729]
Dear Developer, 

I try to calculate RMSD in a simple crystal, but the results look strange
For example, I have 2 different states saved in 2 .pdb files, as figure
![Untitled](https://user-images.githubusercontent.com/46436648/129518221-a249b707-d4ad-4215-aa8f-0b09782e72ff.png)
in which, PBC is applying for all dimensions of the simulation box. The atom-id is identical in 2 states. 
sate_1 differs from state_2 just the space in the middle, all other thing is the same
Then I use state_1 as input in MD run and perform the trial calculation of RMSD using input as follow:
##########
rmsd1: RMSD REFERENCE=state_1.pdb TYPE=SIMPLE    		
rmsd2: RMSD REFERENCE=state_2.pdb TYPE=SIMPLE     	
PRINT  ARG=rmsd2,rmsd1	 FILE=colvar.txt   STRIDE=500
##########

It can be understood that rmsd1 compares the state_1 to itself. But the result returned like this:
##########
#! FIELDS time rmsd2 rmsd1
 0.000000 106.467080 111.639103
 500.000000 106.466279 111.638238
 1000.000000 106.465296 111.637277
 1500.000000 106.466635 111.638512
 2000.000000 106.466916 111.638950
 2500.000000 106.466664 111.638701
...........
###############
It seems that RMSD between 2 different states is smaller than RMSD computed for 1 state itself. This is strange. I am running MD as 1K, so the difference due to thermal vibration is very small, thus the value of rmsd1 should also approach 0 (or a very small value since 2 configurations involved in RMSD-calculation is almost identical)
Whether there is a problem with the code to compute RMSD?

**Comment by GiovanniBussi** [comment]
Did you try to ignore PBC in RMSD calculation?
```
rmsd1: RMSD REFERENCE=state_1.pdb TYPE=SIMPLE NOPBC
```

**Comment by thangckt** [comment]
Dear Prof. @GiovanniBussi 

I did with option: NOPBC
and the result is like this:
############
#! FIELDS time rmsd2 rmsd1
 0.000000 8.213048 8.274106
 500.000000 8.214926 8.276070
 1000.000000 8.214528 8.275759
 1500.000000 8.214526 8.275567
 2000.000000 8.214969 8.275661
 2500.000000 8.214517 8.275422
############
the value is almost the same for 2 different reference structures. This is a really unexpected result.

**Comment by GiovanniBussi** [comment]
Another possible issue is that the MD code is moving atoms to different periodic images (this happens at least with GROMACS). You can try to use `DUMPATOMS` in the plumed input file to know where atoms are located. If these atoms are in a different image wrt to what you expect, you might try to play with `WHOLEMOLECULES` to fix them.

**Comment by thangckt** [comment]
Dear Prof. @GiovanniBussi,

Thank you so much for your instruction.
As I understand, WHOLEMOLECULES will re-arrange atoms in some way. 
So how we can specify the atoms' positions in the reference .pdb file to accommodate to shift?
I mean I don't know how to rearrange atoms in the PDB file to get the right expect RMSD value?

I the case as I described initially when I apply WHOLEMOLECULES, the result is the same as my calculation without NOPBC reported above (even use NOPBC option or not, the results are the same)

Any other way that I can get expect RMSD value?

Thank you so much

**Comment by GiovanniBussi** [comment]
This is expected, by default `RMSD` applies PBCs as if it was `WHOLEMOLECULES` applied to atoms in order. You can change the behavior by changing the order in which atoms are sorted. You can read [this chapter](https://arxiv.org/abs/1812.08213) to learn more about PBCs in PLUMED.

I would recommend:
- using `DUMPATOMS` before `WHOLEMOLECULES` to know where atoms are stored in the MD code
- understand how `WHOLEMOLECULES` affect those positions by also using `DUMPATOMS` **after** `WHOLEMOLECULES`
- if you switch to `master` branch of PLUMED, there's a new feature implemented by @maxbonomi to automatize the construction of this list based on the pdb provided in `MOLINFO` [here](https://www.plumed.org/doc-master/user-doc/html/_m_o_l_i_n_f_o.html). If you pass `WHOLE` to `MOLINFO`, and later apply `WHOLEMOLECULES` with `EMST`, the order will be picked.

**Comment by thangckt** [comment]
Dear Prof. @GiovanniBussi,

I think WHOLEMOLECULES cannot be applied in this case, since my system is simply an atomic-sytem. 
I am not be awared of how can WHOLEMOLECULES be applied in a single atomic system?
However, I still try applying WHOLEMOLECULES for all atoms in my system, and the picture below shows snapshots by DUMPATOMS with (2) and without (1) applying WHOLEMOLECULES. 
![Untit2](https://user-images.githubusercontent.com/46436648/130036463-73903fcd-5d61-4e49-a23a-62ca542db0c8.png)

WHOLEMOLECULES does not help in this case

**Comment by invemichele** [comment]
I think RMSD might not be the best tool for you, because in your system all atoms are identical. Check out [multicolvars](https://www.plumed.org/doc-v2.7/user-doc/html/mcolv.html) such as the [ENVIRONMENTSIMILARITY](https://www.plumed.org/doc-v2.7/user-doc/html/_e_n_v_i_r_o_n_m_e_n_t_s_i_m_i_l_a_r_i_t_y.html) or the [GRADIENT](https://www.plumed.org/doc-v2.7/user-doc/html/_g_r_a_d_i_e_n_t.html) one, for example

**Comment by thangckt** [comment]
Dear @invemichele,
Thank you so much for your recommand.
But such multicovars are not useful for my purpose.
RMSD measure the evoluation of a system from a ref.configuration, so I don't think there is any problem if all atoms in system are identical? Can you explain your concern?
Also, I need to learn how to compute RMSD correctly using Plumed for this kind of system regardless other CV.

**Comment by GiovanniBussi** [comment]
I agree with @invemichele comment especially if your atoms can swap. But if they are in a fixed arrangement, using RMSD should not be a problem provided you apply PBC correctly. I assumed a solid given the regular lattice, but I might be wrong.

**Comment by thangckt** [comment]
Dear @GiovanniBussi @invemichele 

Thank you so much for your instructions
I think the problem is not about choice CV, but about understanding the communication between PLUMED and MD-engine
This is important to help users know what they should do to get an expected calculation
Since MD-engine wrap atoms at PBC, the CV compute in PLUMED may different to what users think.
The problem I described for RMSD here may also the problem for other CV such as: COM, DISTANCE,...which affects by the wrapping of atoms at boundaries of box.

**Comment by GiovanniBussi** [comment]
@thangckt that's true, indeed I would definitely suggest using `DUMPATOMS` and apply `NOPBC` to CVs so that any relocation made by PLUMED can be monitored.

Notice that the problem is not in the communication of coordinates, but in how the MD engine stores them. Usually (at least this is the case with GROMACS) trajectory files suffer from the same issue.

Please let us know if you have any proposal on how to improve the documentation or the code.

**Comment by thangckt** [comment]
after discussions, 
I realize that there is no problem with the PLUMED code. 
The problem is that I don't know how to specify a correct "reference .pdb" file as a compulsory input to compute RMSD.
That is why I fail to get expect RMSD value.
I cannot solve this problem and eventually gave up using this CV, so I would like to close this topic.
Thank you so much for your help.
