### ISSUE TITLE
Nonstandard argument --print-prog-name=

### ISSUE THREAD

**Issue by doctaweeks** [plumed/plumed2#731]
Not all compilers implement --print-prog-name= as used in configure. (IBM's XL is an example of this.) As used in configure, this can result in AR_CR being "silently" set to "cr" which will ultimately cause the compilation to fail. It appears this may be possible because the previous conftest binary is not removed, only the input files: `rm -f conftest-*` This all likely applies to the LD_RO section as well.

**Comment by GiovanniBussi** [comment]
Thanks @doctaweeks I double checked the configure script now and the relevant lines are [here](https://github.com/plumed/plumed2/blob/957a36cd0fa7ab8d6203de84543154954d3e43c5/configure.ac#L1102-L1137) and [here](https://github.com/plumed/plumed2/blob/957a36cd0fa7ab8d6203de84543154954d3e43c5/configure.ac#L1144-L1180). Are you suggesting that if we change `rm -f conftest-*` to `rm -f conftest*` things would work correctly with XL compiler?
