### ISSUE TITLE
plumed 2.8.0

### ISSUE THREAD

**Issue by yuhaihaiyu** [plumed/plumed2#734]
Dear professors
     I would like to know when plumed 2.8.0 version containing sasa module is published

**Comment by yuhaihaiyu** [comment]
Dear developers
I am glad to use the SASA module to implement my calculation in PLUMED, and I am not sure that in the current version PLUMED contains this function as well as how can I use it. Thanks for your reply so much.

**Comment by GiovanniBussi** [comment]
@yuhaihaiyu 2.8 will be released later this year. Meanwhile you can test master branch from GitHub, which is anyway regularly tested so should work correctly.

**Comment by yuhaihaiyu** [comment]
Thanks for your reply, professor Giovanni. Another issue is the master branch from Github can implement&nbsp; SASA function, is it right? because i wish to use this module.


Sincerely


Best wishes




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年8月30日(星期一) 下午3:21
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [plumed/plumed2] plumed 2.8.0 (#734)





 
@yuhaihaiyu 2.8 will be released later this year. Meanwhile you can test master branch from GitHub, which is anyway regularly tested so should work correctly.
 
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
