### ISSUE TITLE
allow GROMACS log files to report that the code is patched by PLUMED

### ISSUE THREAD

**Issue by mabraham** [plumed/plumed2#737]
In GROMACS, we have for a few years enabled users to do `cmake -DGMX_VERSION_STRING_OF_FORK=PLUMED` and that will show up in the GROMACS version string e.g. in log files. This is useful for users running their own forks making sense of their log files later on, as well as for developers reading forum posts or bug reports knowing what versions were used. Troubleshooting GROMACS users' performance questions can go much better if the co-existence of PLUMED is known.

In PLUMED's approach, it seems straightforward to patch the relevant cmake file in GROMACS that declares that variable so that its default value is `PLUMED` and the GROMACS mechanism will work the same way. Is such a patch to PLUMED welcome? If so, I will prepare it.

Would the PLUMED developers prefer also that the PLUMED version appear there? If so, is there a mechanism for that to be updated each time the PLUMED version is updated?

**Comment by GiovanniBussi** [comment]
@mabraham it would be great.

Technically, for GROMACS, we still have this patching hack in place, so there are two relevant pieces of information for users:
- which PLUMED version was used for patching
- which PLUMED version is loaded at run time (they might differ)

For this reason, I would suggest to show the former in the GROMACS log and the latter in the PLUMED log (as we are already doing).

In PLUMED, the script that takes care of patching is written in bash and is [here](https://github.com/plumed/plumed2/blob/master/patches/patch.sh). It does not have access to the PLUMED version, but that's easy to fix on our side. In addition, for each specific MD code that might be patched, there is a configuration file like [this one](https://github.com/plumed/plumed2/blob/master/patches/gromacs-2021.config) that we source and we use to add further bash commands.

I would propose the follwing:
- I take care of making a shell variable containing the PLUMED version available in the script
- You suggest some simple awk command that could be used to insert that version string in the relevant cmake file. Consider that our patch is expected to be applied on the source root (and not on the build root) directory. The command might look something like this:
```
mv src/Cmake.txt src/Cmake.txt.preplumed # this is to allow reverting
awk -v version="$PLUMED_VERSION" '{if($1=="whatever") print($0,version) src/Cmake.txt.preplumed > src/Cmake.txt
```
- I then incorporate those commands in the our configuration file.

What do you think?

**Comment by mabraham** [comment]
Sounds great. The awk approach gives you the necessary flexibility to interpolate the PLUMED version!

**Comment by GiovanniBussi** [comment]
Actually adding the PLUMED_VERSION is straightforward (I already added this to PLUMED v2.7 and master)
