### ISSUE TITLE
the difference between the implementation of Replica Exchange in GROMACS and plumed

### ISSUE THREAD

**Issue by z-gong** [plumed/plumed2#750]
Dear developers, I have a question about the replica-exchange implementation in GROMACS and plumed.
For the **T-REMD** and **lambda-REMD** (with FEP) implemented in GROMACS, the exchange happens at the **_end_** of the step.

```
        bExchanged = FALSE;
        if (bDoReplEx)
        {
            bExchanged = replica_exchange(fplog, cr, ms, repl_ex, state_global, enerd, state, step, t);
        }
```

But for **H-REMD** implemented with plumed, if I understand the code and the paper (_Hamiltonian replica exchange in GROMACS: a flexible implementation_) correctly, the coordinates of two neighbors are exchanged at the **_begining_** of one step to calculate the energy difference. After that coordinates are exchanged back and a normal MD integration is performed. Then the real exchange is tried on the updated coordinates, but the acceptance probability is based on the energy difference calculated **_before_** the integration.

Could you elaborate on the difference between these two implementations? I cannot figure out why the energy difference has to be calculated at the beginning of the step for -hrex.

https://github.com/plumed/plumed2/blob/72ce4899ce213618c50d55ce2859085b1538b02f/patches/gromacs-2020.6.diff/src/gromacs/mdrun/md.cpp#L976-L982

![image](https://user-images.githubusercontent.com/379616/140013206-d606bc9e-c9cc-4d28-9a7f-6bb26d711504.png)

**Comment by GiovanniBussi** [comment]
Hi! I think your interpretation is correct.

If I remember correctly, GROMACS computes the energy (and forces) at the beginning of the step, and these energies are then used to compute the acceptance for T-REMD (or hrex). This implies that also the standard T-REMD suffers of this "bug". But if you think about it, there is no issue in swapping trajectories after having evolved them or before. What is important is that all energy contributions are computed consistently. I think that all terms (force field energy and plumed biases) are consistent, in the current implementation.

Let me know if it's convincing. Thanks!

**Comment by z-gong** [comment]
> But if you think about it, there is no issue in swapping trajectories after having evolved them or before. What is important is that all energy contributions are computed consistently.

Yes, that's right. The ensemble will be correct on matter the energy calculations are before or after the integration. Thank you for your explanation!
