### ISSUE TITLE
Warnings in SASA code

### ISSUE THREAD

**Issue by GiovanniBussi** [plumed/plumed2#751]
@andrea-arsiccio could you please double check these two warnings from cppcheck 2.6.1?
```
[sasa/sasa_LCPO.cpp:779] (warning) :containerOutOfBounds: Either the condition 'LCPOparam[i].size()>0' is redundant or LCPOparam[i] size can be 1. Expression 'LCPOparam[i][1]' cause access out of bounds.
[sasa/sasa_LCPO.cpp:928] (warning) :containerOutOfBounds: Either the condition 'LCPOparam[i].size()>0' is redundant or LCPOparam[i] size can be 1. Expression 'LCPOparam[i][1]' cause access out of bounds.
```

Thanks.

Giovanni

**Comment by andrea-arsiccio** [comment]
Hello,
thank you very much for pointing this out.

I have double checked the lines indicated by cppcheck, and modified the
code accordingly.

Thank you very much, please let me know if this solved the issue.
Best regards,
Andrea


Il giorno sab 6 nov 2021 alle ore 00:31 Giovanni ***@***.***>
ha scritto:
