### ISSUE TITLE
Is multidimensional WHAM possible with Plumed?

### ISSUE THREAD

**Issue by jstoppelman** [plumed/plumed2#756]
Hello, is the native WHAM code associated with Plumed capable of working with multiple CVs/dimensions?

**Comment by GiovanniBussi** [comment]
The WHAM code associate with Plumed (either in some of the tutorials, or in the library itself) is binless, so that there is no notion of "dimensionality". You can combine simulations done with arbitrarily different bias potentials, so yes you can use it for multiple CVs if you wish.
