### ISSUE TITLE
A new plumed release to support Gromacs 2021.4

### ISSUE THREAD

**Issue by xiki-tempula** [plumed/plumed2#769]
I'm interested in using gromacs/plumed on a new HPC with CUDA 11.5.

The plumed 2.7.2 which patches the Gromacs 2021 doesn't support CUDA 11.5 and I have checked that Gromacs 2021.4 supports CUDA 11.5.

So I was wondering if we could have a plumed release supporting the new gromacs.

**Comment by GiovanniBussi** [comment]
@xiki-tempula I think PLUMED supports GROMACS 2021.4. What do you mean with "The plumed 2.7.2 which patches the Gromacs 2021 doesn't support CUDA 11.5"?

**Comment by xiki-tempula** [comment]
@GiovanniBussi Thank you for the reply. 
When I did `plumed patch -p`, I could only find Gromacs 2021.

**Comment by GiovanniBussi** [comment]
That's gromacs 2021.4 indeed. In the coming plumed release (2.7.3) the name will be fixed, but it's the same patch

**Comment by xiki-tempula** [comment]
@GiovanniBussi I see, Thank you.
