### ISSUE TITLE
Plumed: libplumedKernel.so issue

### ISSUE THREAD

**Issue by mtoxic91** [plumed/plumed2#780]
I am trying to install gromacs-plumed. I have installed plumed with mpi and it gave me this message. 
![Plumed](https://user-images.githubusercontent.com/97069385/147993637-bfad0d67-a3ad-4969-84fa-c6f2b839cc77.png)

After the plumed patch, I am having a problem with "make" command when installing gromacs. It seems like I have some issue with libplumedKernel.so file. How can I fix the problem? I am using a cluster from my university. Thank you.

![Gromacs install](https://user-images.githubusercontent.com/97069385/147993646-7e62a4c5-c1fd-4f15-93f4-ff0b1ebb6618.PNG)

**Comment by GiovanniBussi** [comment]
I think that you didn't add `/sw/contrib/plumed-2.7.3/lib` to your `LD_LIBRARY_PATH` variable.

If for some reason you cannot or do not want to do this, you can solve the problem using the `-rpath` option as suggested. However, if you are installing each software in its own directory I would suggest using module files and/or set by hand the `LD_LIBRARY_PATH`.

In case this does not solve your problem please reopen this issue.

Regards,
Giovanni
