### ISSUE TITLE
 Install plumed2.7.4 compile(make) error

### ISSUE THREAD

**Issue by PAN-JIN-MEI** [plumed/plumed2#809]
tar zxvf plumed-2.7.4.tgz        
cd plumed-2.7.4                       
./configure --prefix=/home/jinmei/program/gromacs-2021/plumed/plumed
make

**The following error occurs**

PlumedMain.cpp:(.text+0x5bcf): warning: the use of `tmpnam' is dangerous, better use `mkstemp'
/usr/bin/ld: //usr/local/lib/libfftw3.a(assert.o): relocation R_X86_64_PC32 against symbol `stdout@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: Bad value
collect2: error: ld returned 1 exit status
Makefile:465: recipe for target 'libplumedKernel.so' failed
make[4]: *** [libplumedKernel.so] Error 1
make[4]: Leaving directory '/home/jinmei/program/gromacs-2021/plumed/plumed-2.7.4/src/lib'
Makefile:110: recipe for target 'all' failed
make[3]: *** [all] Error 2
make[3]: Leaving directory '/home/jinmei/program/gromacs-2021/plumed/plumed-2.7.4/src/lib'
Makefile:8: recipe for target 'lib' failed
make[2]: *** [lib] Error 2
make[2]: Leaving directory '/home/jinmei/program/gromacs-2021/plumed/plumed-2.7.4/src'
Makefile:32: recipe for target 'lib' failed
make[1]: *** [lib] Error 2
make[1]: Leaving directory '/home/jinmei/program/gromacs-2021/plumed/plumed-2.7.4'
Makefile:21: recipe for target 'all' failed
make: *** [all] Error 2

**compile(make) error, how to solve this problem.**

**Comment by GiovanniBussi** [comment]
You should install fftw as shared libraries, or disable fftw while configuring (`./configure --disable-fftw`), at the price of disabling some feature.
