### ISSUE TITLE
How to PLUMED 2.8 for HPC cluster?

### ISSUE THREAD

**Issue by hima111997** [plumed/plumed2#828]
I want to build PLUMED 2.8 for HPC cluster. is it possible and how?

Thanks

**Comment by GiovanniBussi** [comment]
@hima111997 can you formulate the question in a more specific manner?

Did you find any problem?

Did you follow the [manual](https://www.plumed.org/doc-v2.8/user-doc/html/_installation.html), and read with care the section with title `Installing PLUMED on a cluster` with specific hints?
