### ISSUE TITLE
Plumed patch for gromacs 2022.1

### ISSUE THREAD

**Issue by andreashlarsen** [plumed/plumed2#849]
Hi, I want to patch plumed in Gromacs 2022. According to issue #822 , there should be a gromacs2022 patch, but it is not in patches/ folder (as of 18 Aug 2022). The latest version is gromacs 2021.5. 

looks like 2022 patch was removed back in June:
https://github.com/plumed/plumed2/commit/2bd213fef7cef074e674e95de97bb45749f147ed

are there plans for making that patch available again?

Best regards, Andreas

**Comment by GiovanniBussi** [comment]
Hi! I think @carlocamilloni implemented it first but then realized there was some problem. We will be back on that when one of us will have time to test it again and find the problem.
