### ISSUE TITLE
Protect main brach

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#877]
@GiovanniBussi @maxbonomi @gtribello do you see the message from GitHub? I think we should protect the main branch, any reason not do it?

**Comment by GiovanniBussi** [comment]
I didn't see the message... is this just to avoid force push or to enforce that tests are passing?

**Comment by GiovanniBussi** [comment]
I added the basic protection (only force push are forbidden). Did you want to force pull requests to pass checks as well?

**Comment by carlocamilloni** [comment]
No I think this is enough.
