### ISSUE TITLE
Possible incompatibility issue for PLUMED with GROMACS GPU-resident mode

### ISSUE THREAD

**Issue by meneshail** [plumed/plumed2#878]
Dear PLUMED developers,

I'm here to report a possible incompatibility issue about running GROMACS in a GPU-resident manner (```-update gpu```) with PLUMED.  Basically, it seems the GPU-resident mode does all GROMACS innate updates and restraints on the GPU side,  and only does GPU-CPU data synchronization when necessary, which is insufficient for PLUMED to compute real-time potential and forces.

### What I did

I tested an implementation of steered MD with GROMACS and PLUMED (adapted from [string-method-swarms-trajectories](https://github.com/delemottelab/string-method-swarms-trajectories)). I used alanine dipeptide for the test and tried to add time-dependent harmonic restraints to the Phi and Psi dihedral simultaneously, to induce a conformation change from (-1.5, 1.3) to (1.4, -1.0) in 100ps.
I used two ways to add such harmonic restraints, namely, GROMACS ```pull code``` and PLUMED ```MOVINGRESTRAINT```, and plotted the CVs evolution along the trajectory respectively.

### What I found

With all major computations performed on GPU (nb, pme, bonded, update), PLUMED generated noisy trajectories and almost failed to make that push. While if I used CPU to do the update and let GPU do the rest, or simply use CPU for all, PLUMED worked just fine (except for using CPU and large restraining constant kappa, where GROMACS warned about ‘relative constraint deviation after LINCS’ and ran into segmentation fault). In all circumstances, the GROMACS ```pull code``` works perfectly.
I have uploaded the trajectory plots of the two methods under different kappa as three figures. And it should be clear that PLUMED works abnormally when using GPU doing all jobs.

<p float="left">
<img src="https://aws1.discourse-cdn.com/standard20/uploads/bioexcel1/original/2X/8/8fa33d7bbd32e0c6d162eb695ce77e5c02846726.png" alt="GPU_for_all" width="250"/>

<img src="https://aws1.discourse-cdn.com/standard20/uploads/bioexcel1/original/2X/d/d499a3d091d5f7088b5268f84c4c789daae9fb90.png" alt="CPU_for_all" width="250"/>

<img src="https://aws1.discourse-cdn.com/standard20/uploads/bioexcel1/original/2X/4/48543cbcd0173f61086f80e48ca1d484a28e44c8.png" alt="CPU_for_update,_GPU_for_others" width="250"/>
</p>

### Discussion on the GROMACS forum

I raised this question on the GROMACS forum last week, where the developers had some discussions and agreed on the possible GPU-CPU synchronization issue. (see [
Is using GPU for mdrun `update` generally incompatible with PLUMED plugin?](https://gromacs.bioexcel.eu/t/is-using-gpu-for-mdrun-update-generally-incompatible-with-plumed-plugin/5147) and [
PLUMED compatibility with GPU resident mode](https://gromacs.bioexcel.eu/t/plumed-compatibility-with-gpu-resident-mode/5149)  . I suppose it's better to also raise this issue here and see if we could work out a solution.

### Possible solution

I guess it should be enough to force the GPU-CPU synchronization done after every time step, so that PLUMED will always get the updated coordinates info. Although this could to a certain extent counteract the advantages of running GPU-resident MD, I guess this is still somehow faster than doing all the updates and restraints back to CPU (that is `-update cpu`) ? As for further optimization, maybe we could only pass selected info to the CPU, instead of everything in the water box.

This is my report on the issue. Do you think the current reasoning is fair? If so, is it possible and necessary to make such modifications? 

Thanks,
Yuyang

**Comment by al42and** [comment]
FYI, starting from GROMACS 2023, the GPU-resident mode will be the default. 

I'm extremely unfamiliar with PLUMED, but I think patching https://gitlab.com/gromacs/gromacs/-/blob/release-2023/src/gromacs/taskassignment/decidegpuusage.cpp#L588 to return `false` would be a solution.

**Comment by carlocamilloni** [comment]
There may be cases when using plumed with -update gpu could still be ok, for example when using plumed to perform on-the-fly analysis, in this case I guess it would be enough to set the stride of plumed action equal to the neighbours list update  . For the moment I added a warning then -plumed is used together with -update gpu.

**Comment by carlocamilloni** [comment]
> FYI, starting from GROMACS 2023, the GPU-resident mode will be the default.
> 
> I'm extremely unfamiliar with PLUMED, but I think patching https://gitlab.com/gromacs/gromacs/-/blob/release-2023/src/gromacs/taskassignment/decidegpuusage.cpp#L588 to return `false` would be a solution.

Thanks, this is also an easy workaround
