### ISSUE TITLE
nan potential energy with rest2

### ISSUE THREAD

**Issue by aminsagar** [plumed/plumed2#881]
Dear PLUMED users/developers,

I am trying to run REST2 simulations on a simple peptide. I generated the scaled topologies using partial_tempering which I used to generate tpr files for gromacs. 
The initial equilibration (10 ns) where I don't allow any exchanges works fine.
However, when I allow exchanges, at some random point, sometimes after more than 50 ns, gromacs aborts with an error

Internal error  (bug):
Step X. The total potential energy is nan, which is not finite. The LJ and electrostatic 
contributions to the energy are 0 and 0, respectively. A non-finite potential energy can be 
caused by overlapping interactions in bonded interactions or very large or Nan coordinate values. Usually this is caused by a badly- or non-equilibrated initial configuration, incorrect interactions or parameters in the topology.

I have equilibrated the system for quite a long  time and it doesn't seem to help. I can't find any nan values in the log files of any of the replicas. I would be really thankful for any suggestions about what could be causing this error.

plumed version 2.8.1
gromacs version 2022.3
command: 
```mpirun -np 15 gmx_mdrun -multidir rep0 ..... -s rex.tpr -deffnm rex -hrex -plumed plumed.dat -replex 500 -nb gpu -bonded gpu -pme gpu -update gpu```

Best,
Amin.

**Comment by GiovanniBussi** [comment]
Discussion moved to [mailing list](https://groups.google.com/d/msgid/plumed-users/aa430f5b-ca85-4abc-bae2-eeca69c262a2n%40googlegroups.com?utm_medium=email&utm_source=footer).
