### ISSUE TITLE
Centos 7 and rt-make-c11

### ISSUE THREAD

**Issue by carlocamilloni** [plumed/plumed2#897]
There is a build issue on centos7 @GiovanniBussi do you have any clue?

plumed/wrapper/Plumed.h:1531:5: error: expected expression before ‘const’
and other

**Comment by GiovanniBussi** [comment]
Looks like the testing system does not understand anymore that Centos7 does not support C11.

It is weird that 2 weeks ago it was working. At [this build](https://github.com/plumed/plumed2/actions/runs/3932699625/jobs/6725570096):
```
make[3]: Entering directory `/home/plumed/plumed2/regtest/basic/rt-make-c11'
Mon Jan 16 17:53:25 UTC 2023
Running regtest in /home/plumed/plumed2/regtest/basic/rt-make-c11
++ Test type: make
++ Arguments: 
++ Processors: 0
/home/plumed/plumed2/regtest/basic/rt-make-c11/tmp
NOT_APPLICABLE (CC does not support c11)
```

Do you know when it started failing?

**Comment by carlocamilloni** [comment]
yes I think it happen when I regenerated the configure con my Mac
