### ISSUE TITLE
segmentation fault with `ROWSUMS` of `ALIGNED_MATRIX`

### ISSUE THREAD

**Issue by tuoping** [plumed/plumed2#908]
When I was running plumed with `ROWSUMS` of `ALIGNED_MATRIX`, I ran into segmentation fault. The plumed file is attached below:
```bash
UNITS LENGTH=A TIME=ps ENERGY=eV

MOLECULES ...
 MOL1=1900,1906
 MOL2=1932,2006
 MOL3=1792,1977
 MOL4=1956,1978
 MOL5=1979,1981
 MOL6=1775,1980
 MOL7=1983,1989
 MOL8=1837,1986
 LABEL=m3
... MOLECULES

ALIGNED_MATRIX ...
 ATOMS=m3
 SWITCH={RATIONAL R_0=7.0} ORIENTATION_SWITCH={RATIONAL R_0=0.5}
 LABEL=mat
... ALIGNED_MATRIX
row: ROWSUMS MATRIX=mat MEAN


PRINT STRIDE=1 FILE=COLVAR ARG=*
FLUSH STRIDE=1

```
The plumed version is v2.8.1

**Comment by gtribello** [comment]
Hello

I am not sure when I am going to get a chance to fix the segmentation fault in the master version of plumed2.  For your purposes you might be able to get around the problem by making use of a development branch of plumed2.  You can get the branch by using the following commands:

git clone https://github.com/plumed/plumed2.git
git checkout hack-the-tree

The branch is not very well documented but what you need to understand is that in this version of the code we can pass round vectors and matrices.  So for your input you are going to want to do the following:

UNITS LENGTH=A TIME=ps ENERGY=ev

c1: CENTER ATOMS=1900,1906
c2: CENTER ATOMS=1932,2006
c3: CENTER ATOMS=1792,1977
c4 CENTER  ATOMS=1956,1978
c5: CENTER ATOMS=1979,1981
c6: CENTER ATOMS=1775,1980
c7: CENTER ATOMS=1983,1989
c8: CENTER ATOMS=1837,1986
gc: GROUP ATOMS=c1,c2,c3,c4,c5,c6,c7,c8

# This gets the vector connecting the start and end of each molecule
m3: DISTANCES 
   COMPONENTS
   ATOMS1=1900,1906
  ATOMS2=1932,2006
  ATOMS3=1792,1977
  ATOMS4=1956,1978
  ATOMS5=1979,1981
  ATOMS6=1775,1980
  ATOMS7=1983,1989
  ATOMS8=1837,1986
...

# Get the length of all the molecules (output is a vector)
norm2: COMBINE ARG1=m3.x ARG2=m3.y ARG3=m3.z COMBINE POWERS=2,2,2  
norm: CUSTOM ARG=norm2 FUNC=sqrt(x) PERIODIC=NO

# Now create a vector of all ones
ones: CONSTANT_VALUE VALUES=1,1,1
# And lets make a matrix that we will use to normalise the distances
norm_mat: DOT ARG1=norm ARG2=ones 

# Make a matrix containing all the vector distances
vecs: STACK ARG1=m3.x ARG2=m3.y ARG3=m3.z 
# And normalise it by doing a Hadamard product with our normalising matrix
normv: CUSTOM ARG1=vecs ARG2=norm_mat FUNCTION=x/y PERIODIC=NO
# Now transport the matrix
normvT: TRANSPOSE ARG=normv

# This is the contact matrix
cmat: CONTACT_MATRIX GROUP=gc SWITCH={RATIONAL R_0=7.0}
# This is the matrix of dot products between directors of molecules
dmat:  DOT ARG1=normv ARG2=normvT
# Now lets put a switching function on the dot product
swfunc: MORE_THAN ARG=dmat SWITCH={RATIONAL R_0=0.5}
# And the final aligned matrix (Hadamard product of contact matrix and transformed dot product matrix)
mat: CUSTOM ARG1=cmat ARG2=swfunc FUNC=x*y PERIODIC=NO

# Now to do the row sums (Notice the row sum is the product of our matrix with a vector of ones)
vvv: CONSTANT_VALUE VALUES=1,1,1,1,1,1,1,1
row: DOT ARG1=mat ARG2=vvv # Output here is a vector
# And finally calculate the mean
row_m: MEAN ARG=row PERIODIC=NO

PRINT STRIDE=1 ARG=row_m FILE=colvar

I hope this helps
