### ISSUE TITLE
Passing `int` pointer in Python interface

### ISSUE THREAD

**Issue by hmcezar** [plumed/plumed2#916]
Before 0f85feb I used to pass an `int` pointer, for example, to get the API version using:

```python
plumed_version = np.zeros(1, dtype=np.intc)
p = plumed.Plumed()
p.cmd("getApiVersion", plumed_version)
```

However, now I get:
```bash
TypeError: 
+++ PLUMED error
+++ message follows +++
This command expects a type with size 4. Received type has size 8 instead
If you are sure your code is correct you can disable this check with export PLUMED_TYPESAFE_IGNORE=yes
In case this is necessary, please report an issue to developers of PLUMED and of the MD code
See also https://github.com/plumed/plumed2/pull/653
```

How should I pass a pointer to Plumed in this case? This is just one of the cases, for example, `p.cmd("setAtomsGatindex", indices)` also requires a pointer to an `int` array. I know I could use the `array` library but using `numpy` is way more convenient in my application.

I don't know if this is a bug, but the error message could be clearer, anyways, because I tried using `np.short` to see if it worked, and I got:
```bash
ValueError: ndarrys should be np.double, np.intc, or np.int_
```

**Comment by GiovanniBussi** [comment]
@hmcezar yes it's a bug... I made a mistake in passing the sizeof np integers. Should be fixed now. Thanks for reporting, and sorry for letting this (stupid) mistake sneak into 2.9 beta!

**Comment by hmcezar** [comment]
Thank you for the fix!
