### ISSUE TITLE
PLUMED error

### ISSUE THREAD

**Issue by zhoujingyu13687306871** [plumed/plumed2#936]
dear author:
  I used gromacs 2020 + plumed 2.7.1 to run the job before, and found that when the calculation continued, there would be no GPU utilization, and the performance was very slow。
  
  so I turn to  gromacs2022.5+plumed2.8.2  do umbrella sampling, but the following error occurs during the running process. I will provide you with the script and log. Please take a look at what caused it?
  

scripts：
![image](https://github.com/plumed/plumed2/assets/47057417/bfa981c7-5e32-4b14-8848-49adc3f7775f)

plumed.dat:

##
RESTART
UNITS LENGTH=A Energy=kcal/mol
MOLINFO STRUCTURE=meta.pdb

WHOLEMOLECULES ENTITY0=1-96 ENTITY1=97-108 ENTITY2=109-120 ENTITY3=121-132 ENTITY4=133-144 ENTITY5=145-156 ENTITY6=157-168 ENTITY7=169-180 ENTITY8=181-192 ENTITY9=193-204 ENTITY10=205-216 ENTITY11=217-228 ENTITY12=229-240 ENTITY13=241-252 ENTITY14=253-264 ENTITY15=265-276 ENTITY16=277-288 ENTITY17=289-300 ENTITY18=301-312 ENTITY19=313-324 ENTITY20=325-336 ENTITY21=337-348 ENTITY22=349-360 ENTITY23=361-372 ENTITY24=373-384 ENTITY25=385-396 ENTITY26=397-408 ENTITY27=409-420 ENTITY28=421-432 ENTITY29=433-444 ENTITY30=445-456 ENTITY31=457-468 ENTITY32=469-480 ENTITY33=481-492 ENTITY34=493-504 ENTITY35=505-516 ENTITY36=517-528 ENTITY37=529-540 ENTITY38=541-552 ENTITY39=553-564 ENTITY40=565-576

c1: CENTER ATOMS=41-48
c2: CENTER ATOMS=49-56
c3: COM ATOMS=97-576
pp: PROJECTION_ON_AXIS AXIS_ATOMS=c1,c2 ATOM=c3 NOPBC
a: CENTER ATOMS=41-56
b: FIXEDATOM AT=100.00,126.00,100.00
an: ANGLE ATOMS=a,b,c3 NOPBC

RESTRAINT ARG=an AT=0.0 KAPPA=50000.0
#UPPER_WALLS ARG=pp.proj AT=0.62    KAPPA=500 EXP=2 EPS=1 OFFSET=0 LABEL=wall1
#LOWER_WALLS ARG=pp.proj AT=0.60    KAPPA=500 EXP=2 EPS=1 OFFSET=0 LABEL=wall2
#UPPER_WALLS ARG=pp.ext AT=50.00    KAPPA=500 EXP=2 EPS=1 OFFSET=0 LABEL=wall3
#LOWER_WALLS ARG=pp.ext AT=48.00    KAPPA=500 EXP=2 EPS=1 OFFSET=0 LABEL=wall4

METAD ...
 LABEL=metad
 ARG=pp.proj,pp.ext
 PACE=50
 HEIGHT=0
 SIGMA=0,0
 BIASFACTOR=-1
 GRID_MAX=100,100
 GRID_MIN=-100,-100
 TEMP=300
 FILE=HILLS
...

PRINT ARG=an FILE=an.txt STRIDE=100
PRINT ARG=pp.proj,pp.ext FILE=cv.txt STRIDE=100
FLUSH STRIDE=1000

output log:

[cv.log](https://github.com/plumed/plumed2/files/11479967/cv.log)

**Comment by carlocamilloni** [comment]
plumed does not like your PDB file
