### ISSUE TITLE
question about tutorials

### ISSUE THREAD

**Issue by loilisxka** [plumed/plumed2#937]
Dear Contributor:
I'm trying to do metadynamics with plumed+gromacs following the tutorial in the documentation at https://www.plumed.org/doc-v2.8/user-doc/html/lugano-3.html.
But in the process of running the command, I encountered the following error "This group-scheme .tpr file can no longer be run by mdrun. Please update to the Verlet scheme, or use an earlier version of GROMACS if necessary."This seems to be caused by the compilation error of the topol.tpr file, so I would like to ask if you can provide me with the compilation files of grompp, such as .mdp and .gro files.
Looking forward to your reply, if you can provide documents, I would appreciate it.

**Comment by carlocamilloni** [comment]
I would suggest you to use the masterclasses material that is more updated

**Comment by loilisxka** [comment]
Thanks for your reply, I have tried using this latest tutorial "https://www.plumed.org/doc-v2.8/user-doc/html/master-_i_s_d_d-2.html". But I still encountered the same problem. I think this error is mainly caused by the fact that gromacs2022.5 no longer supports group-scheme. So I want to request mdp these original files, and then use the grompp command to recompile and generate .tpr files.
I'm currently doing some phase change structure sampling with gromacs+cp2k+plumed, so I have to use a newer version of gromacs. I would be very grateful if you could provide the documents, it is very important to me.
Looking forward to your reply
