### ISSUE TITLE
MDAnalysis API leads to Internal error (bug) / segfault

### ISSUE THREAD

**Issue by Clownshift** [plumed/plumed2#939]
Hi Devs,

I am using gromacs-2022.5 with the plumed patch 2.8.2. I stumbled upon a weird issue, which I do not understand at all. 

Ultimately, I want to use SASA as a collective variable for a simulation of a protein. However, I have a weird problem with the python API.

**Problem description:**
I have equilibrated my system in NVT and NPT (without plumed) and now I want to start my enhanced sampling simulation. If I start the simulation regularly (without plumed), it runs without an error. However, if I select an atomgroup with the MDAnalysis API, the simulation crashes within a few steps. Interestingly, I do not even use the atom group for anything, I only define this group. The plumed file looks like this (yes, currently this is the whole content):

```
MOLINFO STRUCTURE=start_rename.pdb PYTHON_BIN=python3 MOLTYPE=protein
OW: GROUP ATOMS={@mda:{name OW}}
```

The error I get is this:

```
Function:    void checkPotentialEnergyValidity(int64_t, const gmx_enerdata_t&, const t_inputrec&)

Internal error (bug):
Step 0: The total potential energy is 1.08195e+26, which is extremely high.
The LJ and electrostatic contributions to the energy are 1.08195e+26 and
-9.40546e+06, respectively. A very high potential energy can be caused by
overlapping interactions in bonded interactions or very large coordinate
values. Usually this is caused by a badly- or non-equilibrated initial
configuration, incorrect interactions or parameters in the topology.
```
However, if I repeatedly try to start the simulation I do not always get this error. Sometimes, I only get a segmentation fault, without any error message.
_______________________________________________
If I start the simulation like this, it works:
`gmx mdrun -s npt.tpr -deffnm npt`

If I start the simulation like this, it dies:
`gmx mdrun -s npt.tpr -deffnm npt -plumed plumed.dat`

Is this a bug in plumed?
Otherwise, any ideas for debugging are appreciated.

**Comment by carlocamilloni** [comment]
yes it may be, you can try to unpatch and repatch gromacs using the patch that is in plumed master branch

**Comment by Clownshift** [comment]
Hi,
Thanks for the quick reply!

I did patch it with 2.7.6 before, but actually I reverted the patch (`plumed patch -R`) before I reapplied the 2.8.2 patch.

I will try to revert the 2.8.2 patch and then patch and recompile with the current master branch. 
If that doesn't work, I might actually recompile gromacs from scratch and apply the 2.8.2 patch.
I know that in terms of debugging, it would probably be good to do it the other way around, but I don't want to be too invasive on this machine. (Currently, I expect an issue with my installation rather than an actual bug, so I think for you it does not make a difference for now, or does it?)
After all that, I will report on the result. This might take a while, because the machine is currently still running with other jobs that I don't want to interrupt...

**Comment by Clownshift** [comment]
Update on this matter:
I tried a fresh installation of gromacs-2022.5 with the plumed patch version 2.8.2 (on a different machine) and I have the problem there, too:
- simulation without plumed `gmx mdrun -s npt.tpr` : no visible problems
- simulation with plumed `gmx mdrun -s npt.tpr -plumed plumed.dat`: either segfaults immediately, or runs for a few steps, but the protein blows up.

Content of plumed.dat:
```
MOLINFO STRUCTURE=start.pdb PYTHON_BIN=python3 MOLTYPE=protein
OW: GROUP ATOMS={@mda:{name OW}}
```

I did not try the current master branch, yet. This is what I will do next.

**Comment by GiovanniBussi** [comment]
@Clownshift two probably silly questions:
- Did you try without the `OW: GROUP ATOMS={@mda:{name OW}}` line?
- Did you try with an empty plumed.dat file?

Your input should not do anything. However, the second line will launch a separate process with a python interpreter. It should not interfere with GROMACS, but who knows. The first line instead should just read a file. I don't know how it could interfere with GROMACS.

Thanks!

**Comment by Clownshift** [comment]
Thanks for the super quick reply! I just tried both your suggestions. (I only ran the simulations for a few picoseconds, but the above described issues happen basically immediately...)

> * Did you try without the `OW: GROUP ATOMS={@mda:{name OW}}` line?
If I comment this out, it runs with no errors or visible problems whatsoever.

> * Did you try with an empty plumed.dat file?
Also that works without any issues.

**Comment by Clownshift** [comment]
I will still go ahead and apply a patch from the current master branch and give you an update.

**Comment by Clownshift** [comment]
By the way, I did not describe that very precisely before: If I start the simulation repeatedly, sometimes it actually runs for a few steps. If I look at this trajectory the protein unfolds immediately. (This is completely unexpected, since it is a stable globular protein actually). 

I am not sure, if that helps to understand the issue...

**Comment by GiovanniBussi** [comment]
I think it's independent of the patch. There's something wrong in launching a separate process from plumed. I think there's no obvious solution to this, I guess it depends on the exact configuration.

It might be useful if you post for future reference as much information as possible about your system. E.g.:
- how you installed MDAnalysis
- exact compilers and MPI version used for gromacs and plumed.
- operating system 


As a practical solution, I suggest to use python to create a comma separated list of atom numbers and then insert it in the plumed input. Be careful that numbering starts from 1 (not from 0)

**Comment by GiovanniBussi** [comment]
Also notice that the plumed selectors can be used as well. It's less flexible than MDAnalysis though

**Comment by Clownshift** [comment]
Alright, some specs about the machine I am currently working on.

OS: Ubuntu 20.04. 
Python installation: Anaconda3 (conda version 22.9) I use a conda environment in which I installed MDAnalysis.
gcc version: 9.4 
CUDA version: 11.5
GMX version: 2022.5 (with CUDA)
Both GMX and plumed have been compiled without MPI. I used the same compiler versions for GMX and for plumed.

**Comment by Clownshift** [comment]
> Also notice that the plumed selectors can be used as well. It's less flexible than MDAnalysis though

Okay, thanks for the alternative solutions.

**Comment by Clownshift** [comment]
Just for completeness:
I patched gromacs 2022.5 with plumed version 2.9b and the problem still persists...

branch: https://github.com/plumed/plumed2/tree/v2.9
last commit: https://github.com/plumed/plumed2/commit/610cb32070c855b4e1b210b7bd6732d631dee756

**Comment by Clownshift** [comment]
> I think it's independent of the patch. There's something wrong in launching a separate process from plumed. I think there's no obvious solution to this, I guess it depends on the exact configuration.


Based on your comment, I will give up on trying to reinstall, but will workaround this issue, as you suggested above.

If I can do some additional tests that would help you to figure out this issue, feel free to ask.

**Comment by Clownshift** [comment]
For reference:
I solved the issue with a gromacs ndx-file that I generated with MDAnalysis. Very solid workaround.

I assume that the issue is caused by my particular installation. Therefore, I close this issue.
