### ISSUE TITLE
Debug: Unexpected results on RfaH-CTD conformation transition using Amber22+Plumed2.8.1

### ISSUE THREAD

**Issue by freeenergylab** [plumed/plumed2#978]
Hi @maxbonomi @GiovanniBussi @gtribello @carlocamilloni,

I have performed metadynamics simulations on RfaH-CTD transformation, referring to your tutorial:
https://www.plumed.org/doc-master/user-doc/html/masterclass-21-4.html
![image](https://github.com/plumed/plumed2/assets/9461715/854756da-9db1-4cf1-9e0f-19d84276ca1d)

Attached are my input files and analysis files. 
[files.tar.gz](https://github.com/plumed/plumed2/files/12840076/files.tar.gz)

The sampled structures can be seen:
![image](https://github.com/plumed/plumed2/assets/9461715/e9c47bd6-78df-4095-a849-c45928317891)
where, the grey region is sampled by one 1000-ns metadynamics simulation; the blue region is sampled by one 500-ns equilibrium simulation from beta structure; and the green region is sampled by one 500-ns equilibrium simulation from alpha structure.

The Gaussian hill height changes along simulation time:
![image](https://github.com/plumed/plumed2/assets/9461715/751eca66-b399-4fa5-a3e7-8c6ecdca6f01)

The free energy surface is obtained from the `HILLS` file by the command:
`plumed sum_hills --hills HILLS --outfile fes.1000ns.dat --mintozero`
Then, the free energy surface is:
![image](https://github.com/plumed/plumed2/assets/9461715/03b61bc2-a7cb-4fa5-b129-cd42280462ff)

**But,** the free energy surface is obtained by the `reweighting` option:
`plumed driver --noatoms --plumed plumed_reweight.dat`
the `plumed_reweight.dat` can be checked in the attached files.
Then, the free energy surface is:
![image](https://github.com/plumed/plumed2/assets/9461715/f608bb8a-c3dc-4abc-96a6-289795cea68d)

Both free energy surfaces from the `HILLS` file and by the `reweighting` option can not be consistent. **I do not know why it is.**
Could you help me about it? Thanks a lot.

Pengfei Li

**Comment by freeenergylab** [comment]
Could somebody help me about this issue? Many thanks!

**Comment by carlocamilloni** [comment]
This is not an issue, it is a topic to be discussed in the forum. Anyway fes in the range of um hundreds of kj/mol are meaningless, show them in a proper range (when submitting to the mailing list)

**Comment by freeenergylab** [comment]
Thanks for your suggestion. @carlocamilloni I fixed this range and updated issue message.
